// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admincontent.sql

package dbq

import (
	"context"
	"database/sql"
	"time"

	"peetraining-server/internal/dbtypes"
)

const grantedGrading = `-- name: GrantedGrading :one
SELECT g.id, g.score, g.full_score, g.rubric_snapshot, g.point_results, a.answer_text, q.stem, q.qtype
FROM gradings g JOIN attempts a ON a.id = g.attempt_id JOIN questions q ON q.id = a.question_id
WHERE g.id = ? AND g.owner_user_id = ?
`

type GrantedGradingParams struct {
	ID          uint64
	OwnerUserID uint64
}

type GrantedGradingRow struct {
	ID             uint64
	Score          sql.NullString
	FullScore      sql.NullString
	RubricSnapshot dbtypes.NullJSON
	PointResults   dbtypes.NullJSON
	AnswerText     sql.NullString
	Stem           string
	Qtype          QuestionsQtype
}

// 异议那次批改：题目、采分点快照（来源、识别出的、用户补充后的）、作答原文、逐点结果与分数。
func (q *Queries) GrantedGrading(ctx context.Context, arg GrantedGradingParams) (GrantedGradingRow, error) {
	row := q.db.QueryRowContext(ctx, grantedGrading, arg.ID, arg.OwnerUserID)
	var i GrantedGradingRow
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.FullScore,
		&i.RubricSnapshot,
		&i.PointResults,
		&i.AnswerText,
		&i.Stem,
		&i.Qtype,
	)
	return i, err
}

const grantedMaterial = `-- name: GrantedMaterial :one

SELECT id, format, page_count, status, created_at FROM materials WHERE id = ? AND owner_user_id = ?
`

type GrantedMaterialParams struct {
	ID          uint64
	OwnerUserID uint64
}

type GrantedMaterialRow struct {
	ID        uint64
	Format    MaterialsFormat
	PageCount uint32
	Status    MaterialsStatus
	CreatedAt time.Time
}

// 后台授权查看（PRD 10.1、ADR 0006）：只有这里的查询读用户内容原文。调用方必须先经 notify.RecordAccess 校验授权、
// 记 content_access_logs 并通知用户，再用授权所属的用户 ID 读（每条查询都带归属条件）。
func (q *Queries) GrantedMaterial(ctx context.Context, arg GrantedMaterialParams) (GrantedMaterialRow, error) {
	row := q.db.QueryRowContext(ctx, grantedMaterial, arg.ID, arg.OwnerUserID)
	var i GrantedMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Format,
		&i.PageCount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const grantedMaterialPages = `-- name: GrantedMaterialPages :many
SELECT page_no, text FROM material_pages WHERE material_id = ? AND owner_user_id = ? ORDER BY page_no LIMIT 30
`

type GrantedMaterialPagesParams struct {
	MaterialID  uint64
	OwnerUserID uint64
}

type GrantedMaterialPagesRow struct {
	PageNo uint32
	Text   string
}

func (q *Queries) GrantedMaterialPages(ctx context.Context, arg GrantedMaterialPagesParams) ([]GrantedMaterialPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, grantedMaterialPages, arg.MaterialID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GrantedMaterialPagesRow{}
	for rows.Next() {
		var i GrantedMaterialPagesRow
		if err := rows.Scan(&i.PageNo, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
