// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adminconfig.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const aICostSince = `-- name: AICostSince :one
SELECT CAST(COALESCE(SUM(cost_micro_yuan), 0) AS SIGNED) FROM ai_calls WHERE created_at >= ?
`

func (q *Queries) AICostSince(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, aICostSince, createdAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const aIStatsByVersion = `-- name: AIStatsByVersion :many
SELECT capability, model, prompt_version, COUNT(*) AS calls, CAST(SUM(success) AS SIGNED) AS ok,
  CAST(COALESCE(SUM(cost_micro_yuan), 0) AS SIGNED) AS cost, CAST(COALESCE(AVG(latency_ms), 0) AS SIGNED) AS latency
FROM ai_calls WHERE created_at >= ? GROUP BY capability, model, prompt_version
`

type AIStatsByVersionRow struct {
	Capability    string
	Model         string
	PromptVersion string
	Calls         int64
	Ok            int64
	Cost          int64
	Latency       int64
}

// 7.8 AI 任务：按能力与「模型 + 提示词版本」统计调用次数、成功率、单次成本、耗时（ai_calls 不存输入输出原文）。
func (q *Queries) AIStatsByVersion(ctx context.Context, createdAt time.Time) ([]AIStatsByVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, aIStatsByVersion, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AIStatsByVersionRow{}
	for rows.Next() {
		var i AIStatsByVersionRow
		if err := rows.Scan(
			&i.Capability,
			&i.Model,
			&i.PromptVersion,
			&i.Calls,
			&i.Ok,
			&i.Cost,
			&i.Latency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAdminSessionsFor = `-- name: DeleteAdminSessionsFor :exec
DELETE FROM admin_sessions WHERE admin_id = ?
`

func (q *Queries) DeleteAdminSessionsFor(ctx context.Context, adminID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteAdminSessionsFor, adminID)
	return err
}

const deleteFlagUsers = `-- name: DeleteFlagUsers :exec
DELETE FROM feature_flag_users WHERE flag_key = ?
`

func (q *Queries) DeleteFlagUsers(ctx context.Context, flagKey string) error {
	_, err := q.db.ExecContext(ctx, deleteFlagUsers, flagKey)
	return err
}

const deleteUnsentAnnouncement = `-- name: DeleteUnsentAnnouncement :execrows
DELETE FROM announcements WHERE id = ? AND sent_at IS NULL
`

func (q *Queries) DeleteUnsentAnnouncement(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnsentAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgreement = `-- name: GetAgreement :one
SELECT id, kind, version, title, body, change_summary, effective_at, published_at, created_at FROM agreements WHERE id = ?
`

func (q *Queries) GetAgreement(ctx context.Context, id uint64) (Agreement, error) {
	row := q.db.QueryRowContext(ctx, getAgreement, id)
	var i Agreement
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Title,
		&i.Body,
		&i.ChangeSummary,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRuleParam = `-- name: GetRuleParam :one
SELECT param_key, value, description, version, updated_by, updated_at FROM rule_params WHERE param_key = ?
`

func (q *Queries) GetRuleParam(ctx context.Context, paramKey string) (RuleParam, error) {
	row := q.db.QueryRowContext(ctx, getRuleParam, paramKey)
	var i RuleParam
	err := row.Scan(
		&i.ParamKey,
		&i.Value,
		&i.Description,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgreement = `-- name: InsertAgreement :execlastid
INSERT INTO agreements (kind, version, title, body, change_summary, effective_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAgreementParams struct {
	Kind          AgreementsKind
	Version       string
	Title         string
	Body          string
	ChangeSummary sql.NullString
	EffectiveAt   time.Time
}

func (q *Queries) InsertAgreement(ctx context.Context, arg InsertAgreementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAgreement,
		arg.Kind,
		arg.Version,
		arg.Title,
		arg.Body,
		arg.ChangeSummary,
		arg.EffectiveAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertAnnouncement = `-- name: InsertAnnouncement :execlastid
INSERT INTO announcements (title, body, audience, with_popup, scheduled_at, created_by) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAnnouncementParams struct {
	Title       string
	Body        string
	Audience    json.RawMessage
	WithPopup   bool
	ScheduledAt sql.NullTime
	CreatedBy   sql.NullInt64
}

func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAnnouncement,
		arg.Title,
		arg.Body,
		arg.Audience,
		arg.WithPopup,
		arg.ScheduledAt,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertFlagUser = `-- name: InsertFlagUser :exec
INSERT IGNORE INTO feature_flag_users (flag_key, user_id) SELECT ?, id FROM users WHERE id = ?
`

type InsertFlagUserParams struct {
	FlagKey string
	ID      uint64
}

func (q *Queries) InsertFlagUser(ctx context.Context, arg InsertFlagUserParams) error {
	_, err := q.db.ExecContext(ctx, insertFlagUser, arg.FlagKey, arg.ID)
	return err
}

const listAIRollouts = `-- name: ListAIRollouts :many
SELECT capability, stable_model, stable_prompt, candidate_model, candidate_prompt, candidate_percent, updated_by, updated_at FROM ai_rollouts ORDER BY capability
`

func (q *Queries) ListAIRollouts(ctx context.Context) ([]AiRollout, error) {
	rows, err := q.db.QueryContext(ctx, listAIRollouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiRollout{}
	for rows.Next() {
		var i AiRollout
		if err := rows.Scan(
			&i.Capability,
			&i.StableModel,
			&i.StablePrompt,
			&i.CandidateModel,
			&i.CandidatePrompt,
			&i.CandidatePercent,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, display_name, phone, roles, status, must_change_password, last_login_at, created_at FROM admin_users ORDER BY id
`

type ListAdminsRow struct {
	ID                 uint64
	Username           string
	DisplayName        string
	Phone              string
	Roles              json.RawMessage
	Status             AdminUsersStatus
	MustChangePassword bool
	LastLoginAt        sql.NullTime
	CreatedAt          time.Time
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminsRow{}
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Phone,
			&i.Roles,
			&i.Status,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAgreements = `-- name: ListAllAgreements :many
SELECT id, kind, version, title, change_summary, effective_at, published_at, created_at FROM agreements ORDER BY kind, id DESC
`

type ListAllAgreementsRow struct {
	ID            uint64
	Kind          AgreementsKind
	Version       string
	Title         string
	ChangeSummary sql.NullString
	EffectiveAt   time.Time
	PublishedAt   sql.NullTime
	CreatedAt     time.Time
}

func (q *Queries) ListAllAgreements(ctx context.Context) ([]ListAllAgreementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAgreements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAgreementsRow{}
	for rows.Next() {
		var i ListAllAgreementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Title,
			&i.ChangeSummary,
			&i.EffectiveAt,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, title, body, audience, with_popup, scheduled_at, sent_at, sent_count, created_by, created_at FROM announcements ORDER BY id DESC LIMIT 100
`

func (q *Queries) ListAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Audience,
			&i.WithPopup,
			&i.ScheduledAt,
			&i.SentAt,
			&i.SentCount,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppVersions = `-- name: ListAppVersions :many
SELECT platform, latest_version, min_version, download_url, release_notes, updated_at FROM app_versions ORDER BY platform
`

func (q *Queries) ListAppVersions(ctx context.Context) ([]AppVersion, error) {
	rows, err := q.db.QueryContext(ctx, listAppVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppVersion{}
	for rows.Next() {
		var i AppVersion
		if err := rows.Scan(
			&i.Platform,
			&i.LatestVersion,
			&i.MinVersion,
			&i.DownloadUrl,
			&i.ReleaseNotes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamDates = `-- name: ListExamDates :many
SELECT exam_year, label, first_exam_start, first_exam_end, subject_exam_date, updated_at FROM exam_dates ORDER BY exam_year
`

func (q *Queries) ListExamDates(ctx context.Context) ([]ExamDate, error) {
	rows, err := q.db.QueryContext(ctx, listExamDates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamDate{}
	for rows.Next() {
		var i ExamDate
		if err := rows.Scan(
			&i.ExamYear,
			&i.Label,
			&i.FirstExamStart,
			&i.FirstExamEnd,
			&i.SubjectExamDate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlagsFull = `-- name: ListFeatureFlagsFull :many
SELECT f.flag_key, f.description, f.enabled_for_all, f.updated_at,
  CAST(COALESCE((SELECT GROUP_CONCAT(u.user_id ORDER BY u.user_id) FROM feature_flag_users u WHERE u.flag_key = f.flag_key), '') AS CHAR) AS user_ids
FROM feature_flags f ORDER BY f.flag_key
`

type ListFeatureFlagsFullRow struct {
	FlagKey       string
	Description   string
	EnabledForAll bool
	UpdatedAt     time.Time
	UserIds       interface{}
}

func (q *Queries) ListFeatureFlagsFull(ctx context.Context) ([]ListFeatureFlagsFullRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureFlagsFull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeatureFlagsFullRow{}
	for rows.Next() {
		var i ListFeatureFlagsFullRow
		if err := rows.Scan(
			&i.FlagKey,
			&i.Description,
			&i.EnabledForAll,
			&i.UpdatedAt,
			&i.UserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleParamsFull = `-- name: ListRuleParamsFull :many

SELECT param_key, value, description, version, updated_by, updated_at FROM rule_params ORDER BY param_key
`

// 管理后台：配置与系统（T29：7.8、7.9、7.15）。这里只有配置表，不涉及用户内容。
func (q *Queries) ListRuleParamsFull(ctx context.Context) ([]RuleParam, error) {
	rows, err := q.db.QueryContext(ctx, listRuleParamsFull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuleParam{}
	for rows.Next() {
		var i RuleParam
		if err := rows.Scan(
			&i.ParamKey,
			&i.Value,
			&i.Description,
			&i.Version,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishAgreement = `-- name: PublishAgreement :execrows
UPDATE agreements SET published_at = ? WHERE id = ? AND published_at IS NULL
`

type PublishAgreementParams struct {
	PublishedAt sql.NullTime
	ID          uint64
}

func (q *Queries) PublishAgreement(ctx context.Context, arg PublishAgreementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, publishAgreement, arg.PublishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetAdminPassword = `-- name: ResetAdminPassword :exec
UPDATE admin_users SET password_hash = ?, must_change_password = 1 WHERE id = ?
`

type ResetAdminPasswordParams struct {
	PasswordHash string
	ID           uint64
}

func (q *Queries) ResetAdminPassword(ctx context.Context, arg ResetAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, resetAdminPassword, arg.PasswordHash, arg.ID)
	return err
}

const sumStat = `-- name: SumStat :one
SELECT CAST(COALESCE(SUM(value), 0) AS DECIMAL(18,4)) FROM stats_hourly WHERE metric = ? AND dimension = '' AND bucket >= ? AND bucket <= ?
`

type SumStatParams struct {
	Metric   string
	Bucket   time.Time
	Bucket_2 time.Time
}

// 聚合表里某指标在一段时间的和（如活跃用户日累计、收入）。
func (q *Queries) SumStat(ctx context.Context, arg SumStatParams) (string, error) {
	row := q.db.QueryRowContext(ctx, sumStat, arg.Metric, arg.Bucket, arg.Bucket_2)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAdmin = `-- name: UpdateAdmin :execrows
UPDATE admin_users SET display_name = ?, phone = ?, roles = ?, status = ? WHERE id = ?
`

type UpdateAdminParams struct {
	DisplayName string
	Phone       string
	Roles       json.RawMessage
	Status      AdminUsersStatus
	ID          uint64
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAdmin,
		arg.DisplayName,
		arg.Phone,
		arg.Roles,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAgreementDraft = `-- name: UpdateAgreementDraft :execrows
UPDATE agreements SET title = ?, body = ?, change_summary = ?, effective_at = ? WHERE id = ? AND published_at IS NULL
`

type UpdateAgreementDraftParams struct {
	Title         string
	Body          string
	ChangeSummary sql.NullString
	EffectiveAt   time.Time
	ID            uint64
}

func (q *Queries) UpdateAgreementDraft(ctx context.Context, arg UpdateAgreementDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAgreementDraft,
		arg.Title,
		arg.Body,
		arg.ChangeSummary,
		arg.EffectiveAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFeatureFlag = `-- name: UpdateFeatureFlag :execrows
UPDATE feature_flags SET enabled_for_all = ?, updated_by = ? WHERE flag_key = ?
`

type UpdateFeatureFlagParams struct {
	EnabledForAll bool
	UpdatedBy     sql.NullInt64
	FlagKey       string
}

func (q *Queries) UpdateFeatureFlag(ctx context.Context, arg UpdateFeatureFlagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFeatureFlag, arg.EnabledForAll, arg.UpdatedBy, arg.FlagKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRuleParam = `-- name: UpdateRuleParam :execrows
UPDATE rule_params SET value = ?, version = version + 1, updated_by = ? WHERE param_key = ? AND version = ?
`

type UpdateRuleParamParams struct {
	Value     json.RawMessage
	UpdatedBy sql.NullInt64
	ParamKey  string
	Version   uint32
}

// 乐观锁：version 不一致说明别人刚改过，返回 0 行。
func (q *Queries) UpdateRuleParam(ctx context.Context, arg UpdateRuleParamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRuleParam,
		arg.Value,
		arg.UpdatedBy,
		arg.ParamKey,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAIRollout = `-- name: UpsertAIRollout :exec
INSERT INTO ai_rollouts (capability, stable_model, stable_prompt, candidate_model, candidate_prompt, candidate_percent, updated_by) VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE stable_model = VALUES(stable_model), stable_prompt = VALUES(stable_prompt), candidate_model = VALUES(candidate_model),
  candidate_prompt = VALUES(candidate_prompt), candidate_percent = VALUES(candidate_percent), updated_by = VALUES(updated_by)
`

type UpsertAIRolloutParams struct {
	Capability       string
	StableModel      string
	StablePrompt     string
	CandidateModel   sql.NullString
	CandidatePrompt  sql.NullString
	CandidatePercent uint8
	UpdatedBy        sql.NullInt64
}

func (q *Queries) UpsertAIRollout(ctx context.Context, arg UpsertAIRolloutParams) error {
	_, err := q.db.ExecContext(ctx, upsertAIRollout,
		arg.Capability,
		arg.StableModel,
		arg.StablePrompt,
		arg.CandidateModel,
		arg.CandidatePrompt,
		arg.CandidatePercent,
		arg.UpdatedBy,
	)
	return err
}

const upsertAppVersion = `-- name: UpsertAppVersion :exec
INSERT INTO app_versions (platform, latest_version, min_version, download_url, release_notes) VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE latest_version = VALUES(latest_version), min_version = VALUES(min_version), download_url = VALUES(download_url), release_notes = VALUES(release_notes)
`

type UpsertAppVersionParams struct {
	Platform      AppVersionsPlatform
	LatestVersion string
	MinVersion    string
	DownloadUrl   string
	ReleaseNotes  sql.NullString
}

func (q *Queries) UpsertAppVersion(ctx context.Context, arg UpsertAppVersionParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppVersion,
		arg.Platform,
		arg.LatestVersion,
		arg.MinVersion,
		arg.DownloadUrl,
		arg.ReleaseNotes,
	)
	return err
}

const upsertExamDate = `-- name: UpsertExamDate :exec
INSERT INTO exam_dates (exam_year, label, first_exam_start, first_exam_end, subject_exam_date) VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE label = VALUES(label), first_exam_start = VALUES(first_exam_start), first_exam_end = VALUES(first_exam_end), subject_exam_date = VALUES(subject_exam_date)
`

type UpsertExamDateParams struct {
	ExamYear        uint16
	Label           string
	FirstExamStart  time.Time
	FirstExamEnd    time.Time
	SubjectExamDate time.Time
}

func (q *Queries) UpsertExamDate(ctx context.Context, arg UpsertExamDateParams) error {
	_, err := q.db.ExecContext(ctx, upsertExamDate,
		arg.ExamYear,
		arg.Label,
		arg.FirstExamStart,
		arg.FirstExamEnd,
		arg.SubjectExamDate,
	)
	return err
}
