// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const adminBatchCodes = `-- name: AdminBatchCodes :many
SELECT id, code_tail, status, used_by, used_at FROM redeem_codes WHERE batch_id = ? ORDER BY id LIMIT 2000
`

type AdminBatchCodesRow struct {
	ID       uint64
	CodeTail string
	Status   RedeemCodesStatus
	UsedBy   sql.NullInt64
	UsedAt   sql.NullTime
}

// 批次明细：码只存哈希，明细显示末 3 位、状态、使用人与时间。
func (q *Queries) AdminBatchCodes(ctx context.Context, batchID uint64) ([]AdminBatchCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, adminBatchCodes, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminBatchCodesRow{}
	for rows.Next() {
		var i AdminBatchCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.CodeTail,
			&i.Status,
			&i.UsedBy,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminDisableBatch = `-- name: AdminDisableBatch :execrows
UPDATE redeem_batches SET status = 'disabled' WHERE id = ? AND status = 'active'
`

func (q *Queries) AdminDisableBatch(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminDisableBatch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDisputeReasons = `-- name: AdminDisputeReasons :many
SELECT reason, COUNT(*) AS n FROM disputes WHERE created_at >= CAST(? AS DATETIME) GROUP BY reason
`

type AdminDisputeReasonsRow struct {
	Reason DisputesReason
	N      int64
}

func (q *Queries) AdminDisputeReasons(ctx context.Context, since time.Time) ([]AdminDisputeReasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminDisputeReasons, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminDisputeReasonsRow{}
	for rows.Next() {
		var i AdminDisputeReasonsRow
		if err := rows.Scan(&i.Reason, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminDisputeStats = `-- name: AdminDisputeStats :one

SELECT
  (SELECT COUNT(*) FROM disputes WHERE created_at >= CAST(? AS DATETIME)) AS disputes,
  (SELECT COUNT(*) FROM gradings WHERE created_at >= CAST(? AS DATETIME) AND trigger_reason IN ('submit', 'pending_resubmit') AND status = 'done') AS gradings,
  (SELECT COUNT(*) FROM disputes WHERE created_at >= CAST(? AS DATETIME) AND score_after IS NOT NULL AND score_after <> score_before) AS changed,
  (SELECT COUNT(*) FROM disputes WHERE created_at >= CAST(? AS DATETIME) AND score_after IS NOT NULL) AS rechecked,
  (SELECT CAST(COALESCE(AVG(TIMESTAMPDIFF(SECOND, created_at, resolved_at)), 0) AS SIGNED) FROM disputes WHERE created_at >= CAST(? AS DATETIME) AND resolved_at IS NOT NULL) AS avg_seconds
`

type AdminDisputeStatsParams struct {
	Since time.Time
}

type AdminDisputeStatsRow struct {
	Disputes   int64
	Gradings   int64
	Changed    int64
	Rechecked  int64
	AvgSeconds int64
}

// ---------- 7.6 批改异议 ----------
func (q *Queries) AdminDisputeStats(ctx context.Context, arg AdminDisputeStatsParams) (AdminDisputeStatsRow, error) {
	row := q.db.QueryRowContext(ctx, adminDisputeStats,
		arg.Since,
		arg.Since,
		arg.Since,
		arg.Since,
		arg.Since,
	)
	var i AdminDisputeStatsRow
	err := row.Scan(
		&i.Disputes,
		&i.Gradings,
		&i.Changed,
		&i.Rechecked,
		&i.AvgSeconds,
	)
	return i, err
}

const adminFailedMaterials = `-- name: AdminFailedMaterials :many
SELECT id FROM materials WHERE owner_user_id = ? AND status IN ('failed', 'partial') ORDER BY id DESC LIMIT 20
`

// 解析失败或部分失败的资料（只取 ID，用于重新解析）。
func (q *Queries) AdminFailedMaterials(ctx context.Context, ownerUserID uint64) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, adminFailedMaterials, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminFeedbackStats = `-- name: AdminFeedbackStats :one

SELECT
  (SELECT COUNT(*) FROM feedbacks WHERE status = 'open') AS open_count,
  (SELECT CAST(COALESCE(AVG(TIMESTAMPDIFF(SECOND, created_at, replied_at)), 0) AS SIGNED) FROM feedbacks WHERE replied_at IS NOT NULL AND created_at >= CAST(? AS DATETIME)) AS avg_reply_seconds,
  (SELECT CAST(COALESCE(AVG(satisfaction), 0) * 100 AS SIGNED) FROM feedbacks WHERE satisfaction IS NOT NULL AND created_at >= CAST(? AS DATETIME)) AS satisfaction_x100
`

type AdminFeedbackStatsParams struct {
	Since time.Time
}

type AdminFeedbackStatsRow struct {
	OpenCount        int64
	AvgReplySeconds  int64
	SatisfactionX100 int64
}

// ---------- 7.7 用户反馈 ----------
func (q *Queries) AdminFeedbackStats(ctx context.Context, arg AdminFeedbackStatsParams) (AdminFeedbackStatsRow, error) {
	row := q.db.QueryRowContext(ctx, adminFeedbackStats, arg.Since, arg.Since)
	var i AdminFeedbackStatsRow
	err := row.Scan(&i.OpenCount, &i.AvgReplySeconds, &i.SatisfactionX100)
	return i, err
}

const adminFeedbackTypes = `-- name: AdminFeedbackTypes :many
SELECT ftype, COUNT(*) AS n FROM feedbacks WHERE created_at >= CAST(? AS DATETIME) GROUP BY ftype ORDER BY n DESC
`

type AdminFeedbackTypesRow struct {
	Ftype FeedbacksFtype
	N     int64
}

func (q *Queries) AdminFeedbackTypes(ctx context.Context, since time.Time) ([]AdminFeedbackTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, adminFeedbackTypes, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminFeedbackTypesRow{}
	for rows.Next() {
		var i AdminFeedbackTypesRow
		if err := rows.Scan(&i.Ftype, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminFindCode = `-- name: AdminFindCode :one
SELECT c.id, c.batch_id, c.code_tail, c.status, c.used_by, c.used_at, c.membership_id, b.name AS batch_name, b.tier, b.days, b.code_expires_at, b.status AS batch_status
FROM redeem_codes c JOIN redeem_batches b ON b.id = c.batch_id WHERE c.code_hash = ?
`

type AdminFindCodeRow struct {
	ID            uint64
	BatchID       uint64
	CodeTail      string
	Status        RedeemCodesStatus
	UsedBy        sql.NullInt64
	UsedAt        sql.NullTime
	MembershipID  sql.NullInt64
	BatchName     string
	Tier          RedeemBatchesTier
	Days          sql.NullInt16
	CodeExpiresAt time.Time
	BatchStatus   RedeemBatchesStatus
}

func (q *Queries) AdminFindCode(ctx context.Context, codeHash string) (AdminFindCodeRow, error) {
	row := q.db.QueryRowContext(ctx, adminFindCode, codeHash)
	var i AdminFindCodeRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CodeTail,
		&i.Status,
		&i.UsedBy,
		&i.UsedAt,
		&i.MembershipID,
		&i.BatchName,
		&i.Tier,
		&i.Days,
		&i.CodeExpiresAt,
		&i.BatchStatus,
	)
	return i, err
}

const adminGetBatch = `-- name: AdminGetBatch :one
SELECT id, name, tier, days, quantity, code_expires_at, channel, status, created_by, created_at FROM redeem_batches WHERE id = ?
`

func (q *Queries) AdminGetBatch(ctx context.Context, id uint64) (RedeemBatch, error) {
	row := q.db.QueryRowContext(ctx, adminGetBatch, id)
	var i RedeemBatch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.Days,
		&i.Quantity,
		&i.CodeExpiresAt,
		&i.Channel,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const adminGetCodeForUpdate = `-- name: AdminGetCodeForUpdate :one
SELECT id, status, used_by, membership_id FROM redeem_codes WHERE id = ? FOR UPDATE
`

type AdminGetCodeForUpdateRow struct {
	ID           uint64
	Status       RedeemCodesStatus
	UsedBy       sql.NullInt64
	MembershipID sql.NullInt64
}

func (q *Queries) AdminGetCodeForUpdate(ctx context.Context, id uint64) (AdminGetCodeForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetCodeForUpdate, id)
	var i AdminGetCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UsedBy,
		&i.MembershipID,
	)
	return i, err
}

const adminGetDispute = `-- name: AdminGetDispute :one
SELECT d.id, d.owner_user_id, d.grading_id, d.regrade_id, d.reason, d.allow_access, d.score_before, d.score_after, d.status, d.attribution, d.created_at, d.resolved_at
FROM disputes d WHERE d.id = ?
`

type AdminGetDisputeRow struct {
	ID          uint64
	OwnerUserID uint64
	GradingID   uint64
	RegradeID   sql.NullInt64
	Reason      DisputesReason
	AllowAccess bool
	ScoreBefore sql.NullString
	ScoreAfter  sql.NullString
	Status      DisputesStatus
	Attribution NullDisputesAttribution
	CreatedAt   time.Time
	ResolvedAt  sql.NullTime
}

func (q *Queries) AdminGetDispute(ctx context.Context, id uint64) (AdminGetDisputeRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetDispute, id)
	var i AdminGetDisputeRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.GradingID,
		&i.RegradeID,
		&i.Reason,
		&i.AllowAccess,
		&i.ScoreBefore,
		&i.ScoreAfter,
		&i.Status,
		&i.Attribution,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const adminGetFeedback = `-- name: AdminGetFeedback :one
SELECT f.id, f.owner_user_id, f.ftype, f.content, f.allow_access, f.status, f.reply, f.replied_at, f.created_at, f.related_material_id, f.screenshot_keys
FROM feedbacks f WHERE f.id = ?
`

type AdminGetFeedbackRow struct {
	ID                uint64
	OwnerUserID       uint64
	Ftype             FeedbacksFtype
	Content           string
	AllowAccess       bool
	Status            FeedbacksStatus
	Reply             sql.NullString
	RepliedAt         sql.NullTime
	CreatedAt         time.Time
	RelatedMaterialID sql.NullInt64
	ScreenshotKeys    dbtypes.NullJSON
}

func (q *Queries) AdminGetFeedback(ctx context.Context, id uint64) (AdminGetFeedbackRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetFeedback, id)
	var i AdminGetFeedbackRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Ftype,
		&i.Content,
		&i.AllowAccess,
		&i.Status,
		&i.Reply,
		&i.RepliedAt,
		&i.CreatedAt,
		&i.RelatedMaterialID,
		&i.ScreenshotKeys,
	)
	return i, err
}

const adminGetImportJob = `-- name: AdminGetImportJob :one
SELECT id, owner_user_id, mode, status, created_at, started_at, finished_at, billed_pages, reserved_pages, prompt_versions FROM import_jobs WHERE id = ?
`

type AdminGetImportJobRow struct {
	ID             uint64
	OwnerUserID    uint64
	Mode           ImportJobsMode
	Status         ImportJobsStatus
	CreatedAt      time.Time
	StartedAt      sql.NullTime
	FinishedAt     sql.NullTime
	BilledPages    uint32
	ReservedPages  uint32
	PromptVersions dbtypes.NullJSON
}

func (q *Queries) AdminGetImportJob(ctx context.Context, id uint64) (AdminGetImportJobRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetImportJob, id)
	var i AdminGetImportJobRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BilledPages,
		&i.ReservedPages,
		&i.PromptVersions,
	)
	return i, err
}

const adminGetUser = `-- name: AdminGetUser :one
SELECT u.id, u.phone, u.invite_code, u.status, u.created_at, u.last_active_at, u.nickname FROM users u WHERE u.id = ?
`

type AdminGetUserRow struct {
	ID           uint64
	Phone        string
	InviteCode   string
	Status       UsersStatus
	CreatedAt    time.Time
	LastActiveAt sql.NullTime
	Nickname     string
}

func (q *Queries) AdminGetUser(ctx context.Context, id uint64) (AdminGetUserRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetUser, id)
	var i AdminGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.InviteCode,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.Nickname,
	)
	return i, err
}

const adminGetUserPhone = `-- name: AdminGetUserPhone :one
SELECT phone FROM users WHERE id = ?
`

func (q *Queries) AdminGetUserPhone(ctx context.Context, id uint64) (string, error) {
	row := q.db.QueryRowContext(ctx, adminGetUserPhone, id)
	var phone string
	err := row.Scan(&phone)
	return phone, err
}

const adminImportDurations = `-- name: AdminImportDurations :many
SELECT TIMESTAMPDIFF(SECOND, started_at, finished_at) AS seconds FROM import_jobs
WHERE finished_at IS NOT NULL AND started_at IS NOT NULL AND created_at >= ? ORDER BY id DESC LIMIT 2000
`

func (q *Queries) AdminImportDurations(ctx context.Context, createdAt time.Time) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, adminImportDurations, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var seconds int32
		if err := rows.Scan(&seconds); err != nil {
			return nil, err
		}
		items = append(items, seconds)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminImportJobFiles = `-- name: AdminImportJobFiles :many
SELECT x.material_id, m.format, m.page_count, m.status AS material_status, x.step, x.status, x.attempts, x.fail_reason, x.failed_pages, x.updated_at
FROM import_job_materials x JOIN materials m ON m.id = x.material_id WHERE x.job_id = ? ORDER BY x.material_id
`

type AdminImportJobFilesRow struct {
	MaterialID     uint64
	Format         MaterialsFormat
	PageCount      uint32
	MaterialStatus MaterialsStatus
	Step           ImportJobMaterialsStep
	Status         ImportJobMaterialsStatus
	Attempts       uint8
	FailReason     sql.NullString
	FailedPages    dbtypes.NullJSON
	UpdatedAt      time.Time
}

// 任务详情只显示格式、页数、识别日志与失败环节，不显示文件名和内容（PRD 10.2 7.5）。
func (q *Queries) AdminImportJobFiles(ctx context.Context, jobID uint64) ([]AdminImportJobFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, adminImportJobFiles, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminImportJobFilesRow{}
	for rows.Next() {
		var i AdminImportJobFilesRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.Format,
			&i.PageCount,
			&i.MaterialStatus,
			&i.Step,
			&i.Status,
			&i.Attempts,
			&i.FailReason,
			&i.FailedPages,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminInsertBatch = `-- name: AdminInsertBatch :execlastid
INSERT INTO redeem_batches (name, tier, days, quantity, code_expires_at, channel, created_by) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AdminInsertBatchParams struct {
	Name          string
	Tier          RedeemBatchesTier
	Days          sql.NullInt16
	Quantity      uint32
	CodeExpiresAt time.Time
	Channel       string
	CreatedBy     sql.NullInt64
}

func (q *Queries) AdminInsertBatch(ctx context.Context, arg AdminInsertBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminInsertBatch,
		arg.Name,
		arg.Tier,
		arg.Days,
		arg.Quantity,
		arg.CodeExpiresAt,
		arg.Channel,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const adminInsertCode = `-- name: AdminInsertCode :exec
INSERT INTO redeem_codes (batch_id, code_hash, code_tail) VALUES (?, ?, ?)
`

type AdminInsertCodeParams struct {
	BatchID  uint64
	CodeHash string
	CodeTail string
}

func (q *Queries) AdminInsertCode(ctx context.Context, arg AdminInsertCodeParams) error {
	_, err := q.db.ExecContext(ctx, adminInsertCode, arg.BatchID, arg.CodeHash, arg.CodeTail)
	return err
}

const adminListBatches = `-- name: AdminListBatches :many
SELECT b.id, b.name, b.tier, b.days, b.quantity, b.code_expires_at, b.channel, b.status, b.created_by, b.created_at, (SELECT COUNT(*) FROM redeem_codes c WHERE c.batch_id = b.id AND c.status = 'used') AS used_count
FROM redeem_batches b WHERE (CAST(? AS UNSIGNED) = 0 OR b.id < CAST(? AS UNSIGNED)) ORDER BY b.id DESC LIMIT 50
`

type AdminListBatchesParams struct {
	BeforeID int64
}

type AdminListBatchesRow struct {
	ID            uint64
	Name          string
	Tier          RedeemBatchesTier
	Days          sql.NullInt16
	Quantity      uint32
	CodeExpiresAt time.Time
	Channel       string
	Status        RedeemBatchesStatus
	CreatedBy     sql.NullInt64
	CreatedAt     time.Time
	UsedCount     int64
}

func (q *Queries) AdminListBatches(ctx context.Context, arg AdminListBatchesParams) ([]AdminListBatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListBatches, arg.BeforeID, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListBatchesRow{}
	for rows.Next() {
		var i AdminListBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tier,
			&i.Days,
			&i.Quantity,
			&i.CodeExpiresAt,
			&i.Channel,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UsedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListDisputes = `-- name: AdminListDisputes :many
SELECT d.id, d.owner_user_id, d.reason, d.allow_access, d.score_before, d.score_after, d.status, d.attribution, d.created_at, d.resolved_at,
  CAST(IFNULL((SELECT g.id FROM content_access_grants g WHERE g.source = 'dispute' AND g.source_id = d.id AND g.revoked_at IS NULL AND g.expires_at > CAST(? AS DATETIME)), 0) AS UNSIGNED) AS grant_id
FROM disputes d
WHERE (CAST(? AS CHAR) = '' OR d.status = CAST(? AS CHAR)) AND (CAST(? AS UNSIGNED) = 0 OR d.id < CAST(? AS UNSIGNED))
ORDER BY d.id DESC LIMIT 50
`

type AdminListDisputesParams struct {
	Now      time.Time
	Status   interface{}
	BeforeID int64
}

type AdminListDisputesRow struct {
	ID          uint64
	OwnerUserID uint64
	Reason      DisputesReason
	AllowAccess bool
	ScoreBefore sql.NullString
	ScoreAfter  sql.NullString
	Status      DisputesStatus
	Attribution NullDisputesAttribution
	CreatedAt   time.Time
	ResolvedAt  sql.NullTime
	GrantID     int64
}

func (q *Queries) AdminListDisputes(ctx context.Context, arg AdminListDisputesParams) ([]AdminListDisputesRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListDisputes,
		arg.Now,
		arg.Status,
		arg.Status,
		arg.BeforeID,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListDisputesRow{}
	for rows.Next() {
		var i AdminListDisputesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Reason,
			&i.AllowAccess,
			&i.ScoreBefore,
			&i.ScoreAfter,
			&i.Status,
			&i.Attribution,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.GrantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListFeedbacks = `-- name: AdminListFeedbacks :many
SELECT f.id, f.owner_user_id, f.ftype, f.content, f.allow_access, f.status, f.created_at, f.replied_at, f.related_material_id
FROM feedbacks f
WHERE (CAST(? AS CHAR) = '' OR f.status = CAST(? AS CHAR)) AND (CAST(? AS UNSIGNED) = 0 OR f.id < CAST(? AS UNSIGNED))
ORDER BY f.id DESC LIMIT 50
`

type AdminListFeedbacksParams struct {
	Status   interface{}
	BeforeID int64
}

type AdminListFeedbacksRow struct {
	ID                uint64
	OwnerUserID       uint64
	Ftype             FeedbacksFtype
	Content           string
	AllowAccess       bool
	Status            FeedbacksStatus
	CreatedAt         time.Time
	RepliedAt         sql.NullTime
	RelatedMaterialID sql.NullInt64
}

// 反馈是用户写给客服的，列表显示内容；截图与关联资料要授权才能看。
func (q *Queries) AdminListFeedbacks(ctx context.Context, arg AdminListFeedbacksParams) ([]AdminListFeedbacksRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListFeedbacks,
		arg.Status,
		arg.Status,
		arg.BeforeID,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListFeedbacksRow{}
	for rows.Next() {
		var i AdminListFeedbacksRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Ftype,
			&i.Content,
			&i.AllowAccess,
			&i.Status,
			&i.CreatedAt,
			&i.RepliedAt,
			&i.RelatedMaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListImportJobs = `-- name: AdminListImportJobs :many
SELECT j.id, j.owner_user_id, j.mode, j.status, j.created_at, j.finished_at, j.billed_pages,
  (SELECT COUNT(*) FROM import_job_materials x WHERE x.job_id = j.id) AS files,
  (SELECT COUNT(*) FROM import_job_materials x WHERE x.job_id = j.id AND x.status = 'failed') AS failed_files,
  (SELECT COUNT(*) FROM import_job_materials x WHERE x.job_id = j.id AND x.status = 'partial') AS partial_files
FROM import_jobs j
WHERE EXISTS (SELECT 1 FROM import_job_materials x WHERE x.job_id = j.id AND x.status IN ('failed', 'partial'))
  AND (CAST(? AS UNSIGNED) = 0 OR j.id < CAST(? AS UNSIGNED))
ORDER BY j.id DESC LIMIT 50
`

type AdminListImportJobsParams struct {
	BeforeID int64
}

type AdminListImportJobsRow struct {
	ID           uint64
	OwnerUserID  uint64
	Mode         ImportJobsMode
	Status       ImportJobsStatus
	CreatedAt    time.Time
	FinishedAt   sql.NullTime
	BilledPages  uint32
	Files        int64
	FailedFiles  int64
	PartialFiles int64
}

// 失败与部分成功的任务。
func (q *Queries) AdminListImportJobs(ctx context.Context, arg AdminListImportJobsParams) ([]AdminListImportJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListImportJobs, arg.BeforeID, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListImportJobsRow{}
	for rows.Next() {
		var i AdminListImportJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Mode,
			&i.Status,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.BilledPages,
			&i.Files,
			&i.FailedFiles,
			&i.PartialFiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrders = `-- name: AdminListOrders :many

SELECT o.id, o.order_no, o.owner_user_id, o.tier, o.channel, o.amount_cents, o.status, o.paid_at, o.created_at,
  CAST(IFNULL((SELECT r.status FROM refunds r WHERE r.order_id = o.id ORDER BY r.id DESC LIMIT 1), '') AS CHAR) AS refund_status
FROM orders o
WHERE (CAST(? AS CHAR) = '' OR o.status = CAST(? AS CHAR)) AND (CAST(? AS UNSIGNED) = 0 OR o.owner_user_id = CAST(? AS UNSIGNED))
  AND (CAST(? AS UNSIGNED) = 0 OR o.id < CAST(? AS UNSIGNED))
ORDER BY o.id DESC LIMIT 50
`

type AdminListOrdersParams struct {
	Status   interface{}
	UserID   int64
	BeforeID int64
}

type AdminListOrdersRow struct {
	ID           uint64
	OrderNo      string
	OwnerUserID  sql.NullInt64
	Tier         OrdersTier
	Channel      OrdersChannel
	AmountCents  uint32
	Status       OrdersStatus
	PaidAt       sql.NullTime
	CreatedAt    time.Time
	RefundStatus interface{}
}

// ---------- 7.3 会员与订单 ----------
func (q *Queries) AdminListOrders(ctx context.Context, arg AdminListOrdersParams) ([]AdminListOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListOrders,
		arg.Status,
		arg.Status,
		arg.UserID,
		arg.UserID,
		arg.BeforeID,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOrdersRow{}
	for rows.Next() {
		var i AdminListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.OwnerUserID,
			&i.Tier,
			&i.Channel,
			&i.AmountCents,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.RefundStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminMaterialJob = `-- name: AdminMaterialJob :one
SELECT x.job_id FROM import_job_materials x WHERE x.material_id = ? ORDER BY x.job_id DESC LIMIT 1
`

// 反馈关联资料的最近一次解析任务（只取 ID）。
func (q *Queries) AdminMaterialJob(ctx context.Context, materialID uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, adminMaterialJob, materialID)
	var job_id uint64
	err := row.Scan(&job_id)
	return job_id, err
}

const adminOrderSummary = `-- name: AdminOrderSummary :one
SELECT
  (SELECT CAST(COALESCE(SUM(amount_cents), 0) AS SIGNED) FROM orders WHERE status IN ('paid', 'refunding') AND paid_at >= CAST(? AS DATETIME)) AS month_revenue,
  (SELECT COUNT(DISTINCT owner_user_id) FROM orders WHERE status IN ('paid', 'refunding')) AS paid_users,
  (SELECT COUNT(DISTINCT owner_user_id) FROM materials) AS imported_users,
  (SELECT COUNT(*) FROM refunds WHERE status = 'pending') AS pending_refunds
`

type AdminOrderSummaryRow struct {
	MonthRevenue   int64
	PaidUsers      int64
	ImportedUsers  int64
	PendingRefunds int64
}

func (q *Queries) AdminOrderSummary(ctx context.Context, monthStart time.Time) (AdminOrderSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, adminOrderSummary, monthStart)
	var i AdminOrderSummaryRow
	err := row.Scan(
		&i.MonthRevenue,
		&i.PaidUsers,
		&i.ImportedUsers,
		&i.PendingRefunds,
	)
	return i, err
}

const adminOrderUsage = `-- name: AdminOrderUsage :one
SELECT
  (SELECT CAST(COALESCE(SUM(m.page_count), 0) AS SIGNED) FROM materials m WHERE m.owner_user_id = CAST(? AS UNSIGNED) AND m.created_at >= CAST(? AS DATETIME)) AS pages,
  (SELECT COUNT(*) FROM gradings g WHERE g.owner_user_id = CAST(? AS UNSIGNED) AND g.created_at >= CAST(? AS DATETIME)) AS gradings,
  (SELECT COUNT(*) FROM attempts a WHERE a.owner_user_id = CAST(? AS UNSIGNED) AND a.answered_at >= CAST(? AS DATETIME)) AS answers,
  (SELECT COUNT(*) FROM materials m WHERE m.owner_user_id = CAST(? AS UNSIGNED) AND m.status IN ('failed', 'partial')) AS failed_materials
`

type AdminOrderUsageParams struct {
	UserID int64
	Since  time.Time
}

type AdminOrderUsageRow struct {
	Pages           int64
	Gradings        int64
	Answers         int64
	FailedMaterials int64
}

// 退款处理时显示用户使用情况（PRD 13.3）：开通后解析页数、批改次数、作答题数。
func (q *Queries) AdminOrderUsage(ctx context.Context, arg AdminOrderUsageParams) (AdminOrderUsageRow, error) {
	row := q.db.QueryRowContext(ctx, adminOrderUsage,
		arg.UserID,
		arg.Since,
		arg.UserID,
		arg.Since,
		arg.UserID,
		arg.Since,
		arg.UserID,
	)
	var i AdminOrderUsageRow
	err := row.Scan(
		&i.Pages,
		&i.Gradings,
		&i.Answers,
		&i.FailedMaterials,
	)
	return i, err
}

const adminParseByFormat = `-- name: AdminParseByFormat :many

SELECT m.format, m.status, COUNT(*) AS files, CAST(COALESCE(SUM(m.page_count), 0) AS SIGNED) AS pages
FROM materials m WHERE m.created_at >= ? AND m.status IN ('parsed', 'partial', 'failed') GROUP BY m.format, m.status
`

type AdminParseByFormatRow struct {
	Format MaterialsFormat
	Status MaterialsStatus
	Files  int64
	Pages  int64
}

// ---------- 7.5 资料解析监控 ----------
// 近一段时间按格式的解析结果与页数（扫描件单列：PDF 页里没有文字层的记为 image 格式之外的 scanned，见 material.format）。
func (q *Queries) AdminParseByFormat(ctx context.Context, createdAt time.Time) ([]AdminParseByFormatRow, error) {
	rows, err := q.db.QueryContext(ctx, adminParseByFormat, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminParseByFormatRow{}
	for rows.Next() {
		var i AdminParseByFormatRow
		if err := rows.Scan(
			&i.Format,
			&i.Status,
			&i.Files,
			&i.Pages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRedeemSummary = `-- name: AdminRedeemSummary :one

SELECT
  (SELECT COUNT(*) FROM redeem_codes) AS generated_count,
  (SELECT COUNT(*) FROM redeem_codes WHERE status = 'used') AS used_count,
  (SELECT COUNT(*) FROM redeem_codes c JOIN redeem_batches b ON b.id = c.batch_id WHERE c.status = 'unused' AND b.status = 'active' AND b.code_expires_at > CAST(? AS DATETIME)) AS available_count,
  (SELECT COUNT(*) FROM redeem_codes c JOIN redeem_batches b ON b.id = c.batch_id WHERE c.status = 'void' OR (c.status = 'unused' AND (b.status = 'disabled' OR b.code_expires_at <= CAST(? AS DATETIME)))) AS inactive_count
`

type AdminRedeemSummaryParams struct {
	Now time.Time
}

type AdminRedeemSummaryRow struct {
	GeneratedCount int64
	UsedCount      int64
	AvailableCount int64
	InactiveCount  int64
}

// ---------- 7.4 兑换码 ----------
func (q *Queries) AdminRedeemSummary(ctx context.Context, arg AdminRedeemSummaryParams) (AdminRedeemSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, adminRedeemSummary, arg.Now, arg.Now)
	var i AdminRedeemSummaryRow
	err := row.Scan(
		&i.GeneratedCount,
		&i.UsedCount,
		&i.AvailableCount,
		&i.InactiveCount,
	)
	return i, err
}

const adminRevokeUserTokens = `-- name: AdminRevokeUserTokens :exec
UPDATE refresh_tokens SET revoked_at = ? WHERE user_id = ? AND revoked_at IS NULL
`

type AdminRevokeUserTokensParams struct {
	RevokedAt sql.NullTime
	UserID    uint64
}

func (q *Queries) AdminRevokeUserTokens(ctx context.Context, arg AdminRevokeUserTokensParams) error {
	_, err := q.db.ExecContext(ctx, adminRevokeUserTokens, arg.RevokedAt, arg.UserID)
	return err
}

const adminSalesByTier = `-- name: AdminSalesByTier :many
SELECT tier, COUNT(*) AS orders, CAST(COALESCE(SUM(amount_cents), 0) AS SIGNED) AS revenue FROM orders
WHERE status IN ('paid', 'refunding') AND paid_at >= ? GROUP BY tier
`

type AdminSalesByTierRow struct {
	Tier    OrdersTier
	Orders  int64
	Revenue int64
}

func (q *Queries) AdminSalesByTier(ctx context.Context, paidAt sql.NullTime) ([]AdminSalesByTierRow, error) {
	rows, err := q.db.QueryContext(ctx, adminSalesByTier, paidAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSalesByTierRow{}
	for rows.Next() {
		var i AdminSalesByTierRow
		if err := rows.Scan(&i.Tier, &i.Orders, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSearchUsers = `-- name: AdminSearchUsers :many

SELECT u.id, u.phone, u.invite_code, u.status, u.created_at, u.last_active_at,
  (SELECT COUNT(*) FROM materials m WHERE m.owner_user_id = u.id) AS material_count,
  (SELECT COUNT(*) FROM questions q WHERE q.owner_user_id = u.id AND q.status = 'active') AS question_count,
  (SELECT GROUP_CONCAT(COALESCE(NULLIF(s.code, ''), s.name) ORDER BY s.sort_order SEPARATOR ' · ') FROM subjects s WHERE s.owner_user_id = u.id) AS subjects,
  EXISTS (SELECT 1 FROM memberships ms WHERE ms.owner_user_id = u.id AND ms.revoked_at IS NULL AND ms.starts_at <= CAST(? AS DATETIME) AND ms.ends_at > CAST(? AS DATETIME)) AS is_member
FROM users u
WHERE (CAST(? AS CHAR) = '' OR u.phone = CAST(? AS CHAR) OR u.invite_code = CAST(? AS CHAR) OR u.id = CAST(? AS UNSIGNED))
  AND (CAST(? AS CHAR) = ''
    OR (CAST(? AS CHAR) = 'paid' AND EXISTS (SELECT 1 FROM orders o WHERE o.owner_user_id = u.id AND o.status = 'paid'))
    OR (CAST(? AS CHAR) = 'quota_out' AND EXISTS (SELECT 1 FROM quota_counters c WHERE c.owner_user_id = u.id AND c.quota_type = 'parse_pages' AND c.period_key = 'total' AND c.used + c.reserved >= CAST(? AS SIGNED) + c.bonus))
    OR (CAST(? AS CHAR) = 'parse_failed' AND EXISTS (SELECT 1 FROM materials m WHERE m.owner_user_id = u.id AND m.status IN ('failed', 'partial')))
    OR (CAST(? AS CHAR) = 'no_material' AND NOT EXISTS (SELECT 1 FROM materials m WHERE m.owner_user_id = u.id)))
  AND (CAST(? AS UNSIGNED) = 0 OR u.id < CAST(? AS UNSIGNED))
ORDER BY u.id DESC LIMIT 50
`

type AdminSearchUsersParams struct {
	Now       time.Time
	Q         interface{}
	UserID    int64
	Filter    interface{}
	FreePages int64
	BeforeID  int64
}

type AdminSearchUsersRow struct {
	ID            uint64
	Phone         string
	InviteCode    string
	Status        UsersStatus
	CreatedAt     time.Time
	LastActiveAt  sql.NullTime
	MaterialCount int64
	QuestionCount int64
	Subjects      sql.NullString
	IsMember      bool
}

// ---------- 7.2 用户 ----------
// 搜索手机号、用户 ID、邀请码；筛选：付费、额度用完、解析失败、未导入资料。只返回计数与状态。
func (q *Queries) AdminSearchUsers(ctx context.Context, arg AdminSearchUsersParams) ([]AdminSearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminSearchUsers,
		arg.Now,
		arg.Now,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.UserID,
		arg.Filter,
		arg.Filter,
		arg.Filter,
		arg.FreePages,
		arg.Filter,
		arg.Filter,
		arg.BeforeID,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSearchUsersRow{}
	for rows.Next() {
		var i AdminSearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.InviteCode,
			&i.Status,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.MaterialCount,
			&i.QuestionCount,
			&i.Subjects,
			&i.IsMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetDisputeAttribution = `-- name: AdminSetDisputeAttribution :execrows
UPDATE disputes SET attribution = ?, status = ?, handled_by = ?, resolved_at = COALESCE(resolved_at, ?) WHERE id = ?
`

type AdminSetDisputeAttributionParams struct {
	Attribution NullDisputesAttribution
	Status      DisputesStatus
	HandledBy   sql.NullInt64
	ResolvedAt  sql.NullTime
	ID          uint64
}

func (q *Queries) AdminSetDisputeAttribution(ctx context.Context, arg AdminSetDisputeAttributionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminSetDisputeAttribution,
		arg.Attribution,
		arg.Status,
		arg.HandledBy,
		arg.ResolvedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminSetUserStatus = `-- name: AdminSetUserStatus :execrows
UPDATE users SET status = ? WHERE id = ? AND status <> 'deleting'
`

type AdminSetUserStatusParams struct {
	Status UsersStatus
	ID     uint64
}

func (q *Queries) AdminSetUserStatus(ctx context.Context, arg AdminSetUserStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminSetUserStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUserCounts = `-- name: AdminUserCounts :one
SELECT
  (SELECT COUNT(*) FROM materials m WHERE m.owner_user_id = CAST(? AS UNSIGNED)) AS materials,
  (SELECT COUNT(*) FROM materials m WHERE m.owner_user_id = CAST(? AS UNSIGNED) AND m.status IN ('failed', 'partial')) AS failed_materials,
  (SELECT CAST(COALESCE(SUM(m.page_count), 0) AS SIGNED) FROM materials m WHERE m.owner_user_id = CAST(? AS UNSIGNED)) AS pages,
  (SELECT COUNT(*) FROM questions q WHERE q.owner_user_id = CAST(? AS UNSIGNED) AND q.status = 'active') AS questions,
  (SELECT COUNT(*) FROM knowledge_points k WHERE k.owner_user_id = CAST(? AS UNSIGNED)) AS knowledge_points,
  (SELECT COUNT(*) FROM paper_sessions p WHERE p.owner_user_id = CAST(? AS UNSIGNED) AND p.status = 'graded') AS papers,
  (SELECT COUNT(*) FROM gradings g WHERE g.owner_user_id = CAST(? AS UNSIGNED) AND g.status = 'done' AND g.created_at >= CAST(? AS DATETIME)) AS week_gradings,
  (SELECT COUNT(*) FROM invites i WHERE i.inviter_id = CAST(? AS UNSIGNED)) AS invited,
  (SELECT CAST(COALESCE(SUM(i.inviter_days), 0) AS SIGNED) FROM invites i WHERE i.inviter_id = CAST(? AS UNSIGNED)) AS invite_days
`

type AdminUserCountsParams struct {
	UserID    int64
	WeekStart time.Time
}

type AdminUserCountsRow struct {
	Materials       int64
	FailedMaterials int64
	Pages           int64
	Questions       int64
	KnowledgePoints int64
	Papers          int64
	WeekGradings    int64
	Invited         int64
	InviteDays      int64
}

func (q *Queries) AdminUserCounts(ctx context.Context, arg AdminUserCountsParams) (AdminUserCountsRow, error) {
	row := q.db.QueryRowContext(ctx, adminUserCounts,
		arg.UserID,
		arg.UserID,
		arg.UserID,
		arg.UserID,
		arg.UserID,
		arg.UserID,
		arg.UserID,
		arg.WeekStart,
		arg.UserID,
		arg.UserID,
	)
	var i AdminUserCountsRow
	err := row.Scan(
		&i.Materials,
		&i.FailedMaterials,
		&i.Pages,
		&i.Questions,
		&i.KnowledgePoints,
		&i.Papers,
		&i.WeekGradings,
		&i.Invited,
		&i.InviteDays,
	)
	return i, err
}

const adminUserSubjects = `-- name: AdminUserSubjects :many
SELECT s.id, s.name, s.code, s.full_score, s.target_score,
  CAST(IFNULL((SELECT e.low FROM score_estimates e WHERE e.subject_id = s.id AND e.owner_user_id = s.owner_user_id ORDER BY e.id DESC LIMIT 1), -1) AS SIGNED) AS est_low,
  CAST(IFNULL((SELECT e.high FROM score_estimates e WHERE e.subject_id = s.id AND e.owner_user_id = s.owner_user_id ORDER BY e.id DESC LIMIT 1), -1) AS SIGNED) AS est_high
FROM subjects s WHERE s.owner_user_id = ? ORDER BY s.sort_order
`

type AdminUserSubjectsRow struct {
	ID          uint64
	Name        string
	Code        sql.NullString
	FullScore   uint16
	TargetScore sql.NullInt16
	EstLow      int64
	EstHigh     int64
}

// 专业课名称与代码（用户填的元数据）、满分、目标分与最新预估区间（数字）。
func (q *Queries) AdminUserSubjects(ctx context.Context, ownerUserID uint64) ([]AdminUserSubjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminUserSubjects, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserSubjectsRow{}
	for rows.Next() {
		var i AdminUserSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.FullScore,
			&i.TargetScore,
			&i.EstLow,
			&i.EstHigh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminVoidCode = `-- name: AdminVoidCode :execrows
UPDATE redeem_codes SET status = 'void' WHERE id = ? AND status <> 'void'
`

func (q *Queries) AdminVoidCode(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminVoidCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAdminSession = `-- name: DeleteAdminSession :exec
DELETE FROM admin_sessions WHERE token_hash = ?
`

func (q *Queries) DeleteAdminSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteAdminSession, tokenHash)
	return err
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :exec
DELETE FROM admin_sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAdminSessions, expiresAt)
	return err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, display_name, password_hash, phone, roles, status, last_login_at, created_at, updated_at, must_change_password FROM admin_users WHERE id = ?
`

func (q *Queries) GetAdminByID(ctx context.Context, id uint64) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Roles,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one

SELECT id, username, display_name, password_hash, phone, roles, status, last_login_at, created_at, updated_at, must_change_password FROM admin_users WHERE username = ?
`

// 管理后台（T28，PRD 10、dev-spec 第十节）。这里的查询只读计数、状态与元数据，不读用户资料、题目、作答的原文；
// 原文只能经 content_access_grants 授权、由 notify.RecordAccess 记日志后在 admincontent.sql 里读。
func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Roles,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT a.id, a.username, a.display_name, a.roles, a.must_change_password, s.expires_at FROM admin_sessions s JOIN admin_users a ON a.id = s.admin_id
WHERE s.token_hash = ? AND s.expires_at > ? AND a.status = 'active'
`

type GetAdminSessionParams struct {
	TokenHash string
	ExpiresAt time.Time
}

type GetAdminSessionRow struct {
	ID                 uint64
	Username           string
	DisplayName        string
	Roles              json.RawMessage
	MustChangePassword bool
	ExpiresAt          time.Time
}

func (q *Queries) GetAdminSession(ctx context.Context, arg GetAdminSessionParams) (GetAdminSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminSession, arg.TokenHash, arg.ExpiresAt)
	var i GetAdminSessionRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Roles,
		&i.MustChangePassword,
		&i.ExpiresAt,
	)
	return i, err
}

const getGrantBySource = `-- name: GetGrantBySource :one
SELECT id, user_id, source, source_id, scope, granted_at, expires_at, revoked_at FROM content_access_grants WHERE source = ? AND source_id = ? AND revoked_at IS NULL AND expires_at > ?
`

type GetGrantBySourceParams struct {
	Source    ContentAccessGrantsSource
	SourceID  uint64
	ExpiresAt time.Time
}

func (q *Queries) GetGrantBySource(ctx context.Context, arg GetGrantBySourceParams) (ContentAccessGrant, error) {
	row := q.db.QueryRowContext(ctx, getGrantBySource, arg.Source, arg.SourceID, arg.ExpiresAt)
	var i ContentAccessGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.SourceID,
		&i.Scope,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAdmin = `-- name: InsertAdmin :execlastid
INSERT INTO admin_users (username, display_name, password_hash, phone, roles, must_change_password) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAdminParams struct {
	Username           string
	DisplayName        string
	PasswordHash       string
	Phone              string
	Roles              json.RawMessage
	MustChangePassword bool
}

func (q *Queries) InsertAdmin(ctx context.Context, arg InsertAdminParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAdmin,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Phone,
		arg.Roles,
		arg.MustChangePassword,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertAdminAudit = `-- name: InsertAdminAudit :exec
INSERT INTO admin_audit_logs (admin_id, action, target_type, target_id, detail, ip, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAdminAuditParams struct {
	AdminID    uint64
	Action     string
	TargetType sql.NullString
	TargetID   sql.NullString
	Detail     dbtypes.NullJSON
	Ip         sql.NullString
	CreatedAt  time.Time
}

func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAdminAudit,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
		arg.Ip,
		arg.CreatedAt,
	)
	return err
}

const insertAdminSession = `-- name: InsertAdminSession :exec
INSERT INTO admin_sessions (token_hash, admin_id, expires_at, created_at) VALUES (?, ?, ?, ?)
`

type InsertAdminSessionParams struct {
	TokenHash string
	AdminID   uint64
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertAdminSession(ctx context.Context, arg InsertAdminSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertAdminSession,
		arg.TokenHash,
		arg.AdminID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listAdminAudit = `-- name: ListAdminAudit :many
SELECT l.id, l.admin_id, a.display_name, l.action, l.target_type, l.target_id, l.detail, l.created_at
FROM admin_audit_logs l LEFT JOIN admin_users a ON a.id = l.admin_id
WHERE (CAST(? AS CHAR) = '' OR (l.target_type = CAST(? AS CHAR) AND l.target_id = CAST(? AS CHAR)))
  AND (CAST(? AS UNSIGNED) = 0 OR l.id < CAST(? AS UNSIGNED))
ORDER BY l.id DESC LIMIT 50
`

type ListAdminAuditParams struct {
	TargetType interface{}
	TargetID   interface{}
	BeforeID   int64
}

type ListAdminAuditRow struct {
	ID          uint64
	AdminID     uint64
	DisplayName sql.NullString
	Action      string
	TargetType  sql.NullString
	TargetID    sql.NullString
	Detail      dbtypes.NullJSON
	CreatedAt   time.Time
}

func (q *Queries) ListAdminAudit(ctx context.Context, arg ListAdminAuditParams) ([]ListAdminAuditRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminAudit,
		arg.TargetType,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeID,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditRow{}
	for rows.Next() {
		var i ListAdminAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.DisplayName,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentAccessLogs = `-- name: ListContentAccessLogs :many
SELECT l.id, l.grant_id, l.admin_id, a.display_name, l.user_id, l.target_type, l.target_id, l.created_at
FROM content_access_logs l LEFT JOIN admin_users a ON a.id = l.admin_id
WHERE (CAST(? AS UNSIGNED) = 0 OR l.user_id = CAST(? AS UNSIGNED)) ORDER BY l.id DESC LIMIT 100
`

type ListContentAccessLogsParams struct {
	UserID int64
}

type ListContentAccessLogsRow struct {
	ID          uint64
	GrantID     uint64
	AdminID     uint64
	DisplayName sql.NullString
	UserID      uint64
	TargetType  string
	TargetID    uint64
	CreatedAt   time.Time
}

func (q *Queries) ListContentAccessLogs(ctx context.Context, arg ListContentAccessLogsParams) ([]ListContentAccessLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContentAccessLogs, arg.UserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentAccessLogsRow{}
	for rows.Next() {
		var i ListContentAccessLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.GrantID,
			&i.AdminID,
			&i.DisplayName,
			&i.UserID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStats = `-- name: ListStats :many
SELECT metric, dimension, bucket, value FROM stats_hourly WHERE bucket >= ? AND bucket <= ? ORDER BY bucket
`

type ListStatsParams struct {
	Bucket   time.Time
	Bucket_2 time.Time
}

type ListStatsRow struct {
	Metric    string
	Dimension string
	Bucket    time.Time
	Value     string
}

func (q *Queries) ListStats(ctx context.Context, arg ListStatsParams) ([]ListStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStats, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStatsRow{}
	for rows.Next() {
		var i ListStatsRow
		if err := rows.Scan(
			&i.Metric,
			&i.Dimension,
			&i.Bucket,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statDay = `-- name: StatDay :one
SELECT
  (SELECT COUNT(*) FROM users WHERE created_at >= CAST(? AS DATETIME) AND created_at < CAST(? AS DATETIME)) AS new_users,
  (SELECT COUNT(*) FROM users WHERE last_active_at >= CAST(? AS DATETIME) AND last_active_at < CAST(? AS DATETIME)) AS active_users,
  (SELECT COUNT(*) FROM attempts WHERE answered_at >= CAST(? AS DATETIME) AND answered_at < CAST(? AS DATETIME)) AS answers,
  (SELECT CAST(COALESCE(SUM(page_count), 0) AS SIGNED) FROM materials WHERE created_at >= CAST(? AS DATETIME) AND created_at < CAST(? AS DATETIME) AND status IN ('parsed', 'partial', 'failed')) AS parse_pages,
  (SELECT COUNT(*) FROM materials WHERE created_at >= CAST(? AS DATETIME) AND created_at < CAST(? AS DATETIME) AND status = 'parsed') AS parse_ok,
  (SELECT COUNT(*) FROM materials WHERE created_at >= CAST(? AS DATETIME) AND created_at < CAST(? AS DATETIME) AND status IN ('parsed', 'partial', 'failed')) AS parse_total,
  (SELECT COUNT(DISTINCT owner_user_id) FROM orders WHERE paid_at >= CAST(? AS DATETIME) AND paid_at < CAST(? AS DATETIME)) AS paying_users,
  (SELECT CAST(COALESCE(SUM(amount_cents), 0) AS SIGNED) FROM orders WHERE paid_at >= CAST(? AS DATETIME) AND paid_at < CAST(? AS DATETIME) AND status IN ('paid', 'refunding')) AS revenue_cents,
  (SELECT COUNT(*) FROM disputes WHERE created_at >= CAST(? AS DATETIME) AND created_at < CAST(? AS DATETIME)) AS disputes,
  (SELECT COUNT(*) FROM gradings WHERE created_at >= CAST(? AS DATETIME) AND created_at < CAST(? AS DATETIME) AND trigger_reason IN ('submit', 'pending_resubmit') AND status = 'done') AS gradings
`

type StatDayParams struct {
	FromT time.Time
	ToT   time.Time
}

type StatDayRow struct {
	NewUsers     int64
	ActiveUsers  int64
	Answers      int64
	ParsePages   int64
	ParseOk      int64
	ParseTotal   int64
	PayingUsers  int64
	RevenueCents int64
	Disputes     int64
	Gradings     int64
}

// 某天（北京时间，[from, to)）的新增、活跃、作答、解析、付费与收入。
func (q *Queries) StatDay(ctx context.Context, arg StatDayParams) (StatDayRow, error) {
	row := q.db.QueryRowContext(ctx, statDay,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
		arg.FromT,
		arg.ToT,
	)
	var i StatDayRow
	err := row.Scan(
		&i.NewUsers,
		&i.ActiveUsers,
		&i.Answers,
		&i.ParsePages,
		&i.ParseOk,
		&i.ParseTotal,
		&i.PayingUsers,
		&i.RevenueCents,
		&i.Disputes,
		&i.Gradings,
	)
	return i, err
}

const statFunnel = `-- name: StatFunnel :one
SELECT
  (SELECT COUNT(*) FROM users WHERE status <> 'deleting') AS registered,
  (SELECT COUNT(DISTINCT owner_user_id) FROM materials) AS imported,
  (SELECT COUNT(DISTINCT owner_user_id) FROM attempts) AS trained,
  (SELECT COUNT(*) FROM users u WHERE EXISTS (SELECT 1 FROM attempts a WHERE a.owner_user_id = u.id AND a.answered_at >= DATE_ADD(u.created_at, INTERVAL 7 DAY))) AS retained,
  (SELECT COUNT(DISTINCT owner_user_id) FROM orders WHERE status IN ('paid', 'refunding')) AS paid,
  (SELECT COUNT(DISTINCT owner_user_id) FROM memberships WHERE revoked_at IS NULL AND starts_at <= CAST(? AS DATETIME) AND ends_at > CAST(? AS DATETIME)) AS members
`

type StatFunnelParams struct {
	Now time.Time
}

type StatFunnelRow struct {
	Registered int64
	Imported   int64
	Trained    int64
	Retained   int64
	Paid       int64
	Members    int64
}

// 新用户漏斗（全部用户）：注册 → 导入第一份资料 → 完成首次训练 → 7 日后仍在练 → 付费。
func (q *Queries) StatFunnel(ctx context.Context, arg StatFunnelParams) (StatFunnelRow, error) {
	row := q.db.QueryRowContext(ctx, statFunnel, arg.Now, arg.Now)
	var i StatFunnelRow
	err := row.Scan(
		&i.Registered,
		&i.Imported,
		&i.Trained,
		&i.Retained,
		&i.Paid,
		&i.Members,
	)
	return i, err
}

const statHotSubjects = `-- name: StatHotSubjects :many
SELECT code, COUNT(DISTINCT owner_user_id) AS users FROM subjects WHERE code IS NOT NULL AND code <> '' GROUP BY code ORDER BY users DESC LIMIT 20
`

type StatHotSubjectsRow struct {
	Code  sql.NullString
	Users int64
}

// 热门专业课：按用户填的代码聚合（只有代码与人数）。
func (q *Queries) StatHotSubjects(ctx context.Context) ([]StatHotSubjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, statHotSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatHotSubjectsRow{}
	for rows.Next() {
		var i StatHotSubjectsRow
		if err := rows.Scan(&i.Code, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statImportModes = `-- name: StatImportModes :many
SELECT mode, COUNT(*) AS n FROM import_jobs WHERE created_at >= ? AND created_at < ? GROUP BY mode
`

type StatImportModesParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type StatImportModesRow struct {
	Mode ImportJobsMode
	N    int64
}

func (q *Queries) StatImportModes(ctx context.Context, arg StatImportModesParams) ([]StatImportModesRow, error) {
	rows, err := q.db.QueryContext(ctx, statImportModes, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatImportModesRow{}
	for rows.Next() {
		var i StatImportModesRow
		if err := rows.Scan(&i.Mode, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAdminLogin = `-- name: TouchAdminLogin :exec
UPDATE admin_users SET last_login_at = ? WHERE id = ?
`

type TouchAdminLoginParams struct {
	LastLoginAt sql.NullTime
	ID          uint64
}

func (q *Queries) TouchAdminLogin(ctx context.Context, arg TouchAdminLoginParams) error {
	_, err := q.db.ExecContext(ctx, touchAdminLogin, arg.LastLoginAt, arg.ID)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_users SET password_hash = ?, must_change_password = 0 WHERE id = ?
`

type UpdateAdminPasswordParams struct {
	PasswordHash string
	ID           uint64
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminPassword, arg.PasswordHash, arg.ID)
	return err
}

const upsertStat = `-- name: UpsertStat :exec

INSERT INTO stats_hourly (metric, dimension, bucket, value) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE value = VALUES(value)
`

type UpsertStatParams struct {
	Metric    string
	Dimension string
	Bucket    time.Time
	Value     string
}

// ---------- 统计汇总（Worker 每小时写 stats_hourly，7.1 只读它） ----------
func (q *Queries) UpsertStat(ctx context.Context, arg UpsertStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertStat,
		arg.Metric,
		arg.Dimension,
		arg.Bucket,
		arg.Value,
	)
	return err
}
