// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package dbq

import (
	"context"
	"database/sql"
)

const getAIRollout = `-- name: GetAIRollout :one
SELECT capability, stable_model, stable_prompt, candidate_model, candidate_prompt, candidate_percent, updated_by, updated_at FROM ai_rollouts WHERE capability = ?
`

func (q *Queries) GetAIRollout(ctx context.Context, capability string) (AiRollout, error) {
	row := q.db.QueryRowContext(ctx, getAIRollout, capability)
	var i AiRollout
	err := row.Scan(
		&i.Capability,
		&i.StableModel,
		&i.StablePrompt,
		&i.CandidateModel,
		&i.CandidatePrompt,
		&i.CandidatePercent,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAICall = `-- name: InsertAICall :exec

INSERT INTO ai_calls (capability, model, prompt_version, user_hash, input_tokens, output_tokens, cost_micro_yuan, latency_ms, success, error_kind, retried)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAICallParams struct {
	Capability    string
	Model         string
	PromptVersion string
	UserHash      sql.NullString
	InputTokens   uint32
	OutputTokens  uint32
	CostMicroYuan uint64
	LatencyMs     uint32
	Success       bool
	ErrorKind     sql.NullString
	Retried       bool
}

// AI 调用账本与灰度（T10）。不含用户内容，user_hash 是用户 ID 的哈希。
func (q *Queries) InsertAICall(ctx context.Context, arg InsertAICallParams) error {
	_, err := q.db.ExecContext(ctx, insertAICall,
		arg.Capability,
		arg.Model,
		arg.PromptVersion,
		arg.UserHash,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMicroYuan,
		arg.LatencyMs,
		arg.Success,
		arg.ErrorKind,
		arg.Retried,
	)
	return err
}
