// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bankwrite.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"

	"peetraining-server/internal/dbtypes"
)

const deletePaperQuestions = `-- name: DeletePaperQuestions :exec
DELETE pq FROM paper_questions pq JOIN papers p ON p.id = pq.paper_id WHERE pq.paper_id = ? AND p.owner_user_id = ?
`

type DeletePaperQuestionsParams struct {
	PaperID     uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeletePaperQuestions(ctx context.Context, arg DeletePaperQuestionsParams) error {
	_, err := q.db.ExecContext(ctx, deletePaperQuestions, arg.PaperID, arg.OwnerUserID)
	return err
}

const findKPByName = `-- name: FindKPByName :one
SELECT id FROM knowledge_points WHERE bank_id = ? AND owner_user_id = ? AND parent_id <=> ? AND level = ? AND name = ? LIMIT 1
`

type FindKPByNameParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
	ParentID    sql.NullInt64
	Level       KnowledgePointsLevel
	Name        string
}

// 按「父节点 + 层级 + 名称」找已有知识点，导入时同名节点复用，树不重复（parent_id 可空，用 <=> 比较）。
func (q *Queries) FindKPByName(ctx context.Context, arg FindKPByNameParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, findKPByName,
		arg.BankID,
		arg.OwnerUserID,
		arg.ParentID,
		arg.Level,
		arg.Name,
	)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const getBankKP = `-- name: GetBankKP :one
SELECT id, owner_user_id, bank_id, parent_id, level, name, original_text, source_material_id, source_page, origin, needs_review, ai_explanation, ai_explanation_at, exam_count, official_kp_id, sort_order, created_at, updated_at FROM knowledge_points WHERE id = ? AND bank_id = ? AND owner_user_id = ?
`

type GetBankKPParams struct {
	ID          uint64
	BankID      uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) GetBankKP(ctx context.Context, arg GetBankKPParams) (KnowledgePoint, error) {
	row := q.db.QueryRowContext(ctx, getBankKP, arg.ID, arg.BankID, arg.OwnerUserID)
	var i KnowledgePoint
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.ParentID,
		&i.Level,
		&i.Name,
		&i.OriginalText,
		&i.SourceMaterialID,
		&i.SourcePage,
		&i.Origin,
		&i.NeedsReview,
		&i.AiExplanation,
		&i.AiExplanationAt,
		&i.ExamCount,
		&i.OfficialKpID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRealExamPaper = `-- name: GetRealExamPaper :one
SELECT id, owner_user_id, bank_id, kind, title, exam_year, full_score, actual_score, duration_minutes, structure, missing_note, source_material_id, created_at FROM papers WHERE bank_id = ? AND owner_user_id = ? AND kind = 'real_exam' AND exam_year = ? LIMIT 1
`

type GetRealExamPaperParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
	ExamYear    sql.NullInt16
}

func (q *Queries) GetRealExamPaper(ctx context.Context, arg GetRealExamPaperParams) (Paper, error) {
	row := q.db.QueryRowContext(ctx, getRealExamPaper, arg.BankID, arg.OwnerUserID, arg.ExamYear)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Kind,
		&i.Title,
		&i.ExamYear,
		&i.FullScore,
		&i.ActualScore,
		&i.DurationMinutes,
		&i.Structure,
		&i.MissingNote,
		&i.SourceMaterialID,
		&i.CreatedAt,
	)
	return i, err
}

const insertKPSource = `-- name: InsertKPSource :exec
INSERT IGNORE INTO kp_sources (kp_id, material_id, page_no, owner_user_id) VALUES (?, ?, ?, ?)
`

type InsertKPSourceParams struct {
	KpID        uint64
	MaterialID  uint64
	PageNo      uint32
	OwnerUserID sql.NullInt64
}

func (q *Queries) InsertKPSource(ctx context.Context, arg InsertKPSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertKPSource,
		arg.KpID,
		arg.MaterialID,
		arg.PageNo,
		arg.OwnerUserID,
	)
	return err
}

const insertKnowledgePoint = `-- name: InsertKnowledgePoint :execlastid
INSERT INTO knowledge_points (owner_user_id, bank_id, parent_id, level, name, original_text, source_material_id, source_page, origin, needs_review, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertKnowledgePointParams struct {
	OwnerUserID      sql.NullInt64
	BankID           uint64
	ParentID         sql.NullInt64
	Level            KnowledgePointsLevel
	Name             string
	OriginalText     sql.NullString
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	Origin           KnowledgePointsOrigin
	NeedsReview      bool
	SortOrder        uint32
}

func (q *Queries) InsertKnowledgePoint(ctx context.Context, arg InsertKnowledgePointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertKnowledgePoint,
		arg.OwnerUserID,
		arg.BankID,
		arg.ParentID,
		arg.Level,
		arg.Name,
		arg.OriginalText,
		arg.SourceMaterialID,
		arg.SourcePage,
		arg.Origin,
		arg.NeedsReview,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertPaper = `-- name: InsertPaper :execlastid
INSERT INTO papers (owner_user_id, bank_id, kind, title, exam_year, full_score, actual_score, duration_minutes, structure, missing_note, source_material_id)
VALUES (?, ?, 'real_exam', ?, ?, ?, ?, 180, ?, ?, ?)
`

type InsertPaperParams struct {
	OwnerUserID      sql.NullInt64
	BankID           uint64
	Title            string
	ExamYear         sql.NullInt16
	FullScore        string
	ActualScore      string
	Structure        json.RawMessage
	MissingNote      sql.NullString
	SourceMaterialID sql.NullInt64
}

func (q *Queries) InsertPaper(ctx context.Context, arg InsertPaperParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertPaper,
		arg.OwnerUserID,
		arg.BankID,
		arg.Title,
		arg.ExamYear,
		arg.FullScore,
		arg.ActualScore,
		arg.Structure,
		arg.MissingNote,
		arg.SourceMaterialID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertPaperQuestion = `-- name: InsertPaperQuestion :exec
INSERT INTO paper_questions (paper_id, seq, question_id, section, score) VALUES (?, ?, ?, ?, ?)
`

type InsertPaperQuestionParams struct {
	PaperID    uint64
	Seq        uint16
	QuestionID uint64
	Section    string
	Score      string
}

func (q *Queries) InsertPaperQuestion(ctx context.Context, arg InsertPaperQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertPaperQuestion,
		arg.PaperID,
		arg.Seq,
		arg.QuestionID,
		arg.Section,
		arg.Score,
	)
	return err
}

const insertQuestion = `-- name: InsertQuestion :execlastid

INSERT INTO questions (owner_user_id, bank_id, qtype, stem, options, answer, answer_origin, analysis, score, difficulty,
  source, exam_year, question_no, is_recollection, source_material_id, source_page, content_hash, needs_review, review_reasons)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertQuestionParams struct {
	OwnerUserID      sql.NullInt64
	BankID           uint64
	Qtype            QuestionsQtype
	Stem             string
	Options          dbtypes.NullJSON
	Answer           sql.NullString
	AnswerOrigin     NullQuestionsAnswerOrigin
	Analysis         sql.NullString
	Score            sql.NullString
	Difficulty       NullQuestionsDifficulty
	Source           QuestionsSource
	ExamYear         sql.NullInt16
	QuestionNo       sql.NullString
	IsRecollection   bool
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	ContentHash      string
	NeedsReview      bool
	ReviewReasons    dbtypes.NullJSON
}

// 确认导入后写入题库（T10）。每条都带 owner_user_id。
func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertQuestion,
		arg.OwnerUserID,
		arg.BankID,
		arg.Qtype,
		arg.Stem,
		arg.Options,
		arg.Answer,
		arg.AnswerOrigin,
		arg.Analysis,
		arg.Score,
		arg.Difficulty,
		arg.Source,
		arg.ExamYear,
		arg.QuestionNo,
		arg.IsRecollection,
		arg.SourceMaterialID,
		arg.SourcePage,
		arg.ContentHash,
		arg.NeedsReview,
		arg.ReviewReasons,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertQuestionKP = `-- name: InsertQuestionKP :exec
INSERT IGNORE INTO question_kps (question_id, kp_id, is_primary, owner_user_id) VALUES (?, ?, ?, ?)
`

type InsertQuestionKPParams struct {
	QuestionID  uint64
	KpID        uint64
	IsPrimary   bool
	OwnerUserID sql.NullInt64
}

func (q *Queries) InsertQuestionKP(ctx context.Context, arg InsertQuestionKPParams) error {
	_, err := q.db.ExecContext(ctx, insertQuestionKP,
		arg.QuestionID,
		arg.KpID,
		arg.IsPrimary,
		arg.OwnerUserID,
	)
	return err
}

const insertRubricPoint = `-- name: InsertRubricPoint :exec
INSERT INTO rubric_points (owner_user_id, question_id, kp_id, seq, content, keywords, score, origin)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRubricPointParams struct {
	OwnerUserID sql.NullInt64
	QuestionID  sql.NullInt64
	KpID        sql.NullInt64
	Seq         uint16
	Content     string
	Keywords    dbtypes.NullJSON
	Score       sql.NullString
	Origin      RubricPointsOrigin
}

func (q *Queries) InsertRubricPoint(ctx context.Context, arg InsertRubricPointParams) error {
	_, err := q.db.ExecContext(ctx, insertRubricPoint,
		arg.OwnerUserID,
		arg.QuestionID,
		arg.KpID,
		arg.Seq,
		arg.Content,
		arg.Keywords,
		arg.Score,
		arg.Origin,
	)
	return err
}

const listExamQuestionsByYear = `-- name: ListExamQuestionsByYear :many
SELECT id, qtype, question_no, score, source_material_id FROM questions
WHERE bank_id = ? AND owner_user_id = ? AND source = 'exam' AND exam_year = ? AND status = 'active' AND is_recollection = 0
ORDER BY CAST(question_no AS UNSIGNED), id
`

type ListExamQuestionsByYearParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
	ExamYear    sql.NullInt16
}

type ListExamQuestionsByYearRow struct {
	ID               uint64
	Qtype            QuestionsQtype
	QuestionNo       sql.NullString
	Score            sql.NullString
	SourceMaterialID sql.NullInt64
}

// 组真题卷：某年份的真题（回忆版不计入，PRD 3.8），按题型、原题号排序。
func (q *Queries) ListExamQuestionsByYear(ctx context.Context, arg ListExamQuestionsByYearParams) ([]ListExamQuestionsByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, listExamQuestionsByYear, arg.BankID, arg.OwnerUserID, arg.ExamYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExamQuestionsByYearRow{}
	for rows.Next() {
		var i ListExamQuestionsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.Qtype,
			&i.QuestionNo,
			&i.Score,
			&i.SourceMaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsWithoutContent = `-- name: ListSubjectsWithoutContent :many
SELECT s.id FROM subjects s JOIN banks b ON b.subject_id = s.id
WHERE s.owner_user_id = ? AND NOT EXISTS (SELECT 1 FROM materials m WHERE m.bank_id = b.id)
ORDER BY s.id
`

// 还没导入任何资料的专业课（1.8 提示继续导入）。
func (q *Queries) ListSubjectsWithoutContent(ctx context.Context, ownerUserID uint64) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectsWithoutContent, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxKPSort = `-- name: MaxKPSort :one
SELECT CAST(COALESCE(MAX(sort_order), 0) AS SIGNED) FROM knowledge_points WHERE bank_id = ? AND owner_user_id = ?
`

type MaxKPSortParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) MaxKPSort(ctx context.Context, arg MaxKPSortParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxKPSort, arg.BankID, arg.OwnerUserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const recountKPExamCounts = `-- name: RecountKPExamCounts :exec
UPDATE knowledge_points k SET exam_count = (
  SELECT COUNT(DISTINCT q.id) FROM question_kps qk JOIN questions q ON q.id = qk.question_id
  WHERE qk.kp_id = k.id AND q.source = 'exam' AND q.is_recollection = 0 AND q.status = 'active')
WHERE k.bank_id = ? AND k.owner_user_id = ?
`

type RecountKPExamCountsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

// 知识点在真题中出现的次数（3.1、3.8；回忆版不计入）。
func (q *Queries) RecountKPExamCounts(ctx context.Context, arg RecountKPExamCountsParams) error {
	_, err := q.db.ExecContext(ctx, recountKPExamCounts, arg.BankID, arg.OwnerUserID)
	return err
}

const recountMaterial = `-- name: RecountMaterial :exec
UPDATE materials m SET
  question_count = (SELECT COUNT(*) FROM questions q WHERE q.source_material_id = ? AND q.status = 'active'),
  kp_count = (SELECT COUNT(DISTINCT s.kp_id) FROM kp_sources s WHERE s.material_id = ?)
WHERE m.id = ? AND m.owner_user_id = ?
`

type RecountMaterialParams struct {
	SourceMaterialID sql.NullInt64
	MaterialID       uint64
	ID               uint64
	OwnerUserID      uint64
}

// 参数依次：资料 ID（题目来源）、资料 ID（知识点来源）、资料 ID、所有者。
func (q *Queries) RecountMaterial(ctx context.Context, arg RecountMaterialParams) error {
	_, err := q.db.ExecContext(ctx, recountMaterial,
		arg.SourceMaterialID,
		arg.MaterialID,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updatePaperScores = `-- name: UpdatePaperScores :exec
UPDATE papers SET full_score = ?, actual_score = ?, structure = ?, missing_note = ? WHERE id = ? AND owner_user_id = ?
`

type UpdatePaperScoresParams struct {
	FullScore   string
	ActualScore string
	Structure   json.RawMessage
	MissingNote sql.NullString
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) UpdatePaperScores(ctx context.Context, arg UpdatePaperScoresParams) error {
	_, err := q.db.ExecContext(ctx, updatePaperScores,
		arg.FullScore,
		arg.ActualScore,
		arg.Structure,
		arg.MissingNote,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}
