// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank.sql

package dbq

import (
	"context"
	"database/sql"
	"time"

	"peetraining-server/internal/dbtypes"
)

const bankCounts = `-- name: BankCounts :one
SELECT
  (SELECT COUNT(*) FROM questions q WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.status = 'active') AS question_count,
  (SELECT COUNT(*) FROM knowledge_points k WHERE k.bank_id = ? AND k.owner_user_id = ? AND k.level = 'point') AS kp_count,
  (SELECT COUNT(*) FROM questions q WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.status = 'active' AND q.needs_review = 1) AS question_review_count,
  (SELECT COUNT(*) FROM knowledge_points k WHERE k.bank_id = ? AND k.owner_user_id = ? AND k.needs_review = 1) AS kp_review_count,
  (SELECT COUNT(*) FROM materials m WHERE m.bank_id = ? AND m.owner_user_id = ?) AS material_count,
  (SELECT COUNT(*) FROM papers p WHERE p.bank_id = ? AND p.owner_user_id = ?) AS paper_count
`

type BankCountsParams struct {
	BankID uint64
	Owner  sql.NullInt64
	UserID uint64
}

type BankCountsRow struct {
	QuestionCount       int64
	KpCount             int64
	QuestionReviewCount int64
	KpReviewCount       int64
	MaterialCount       int64
	PaperCount          int64
}

func (q *Queries) BankCounts(ctx context.Context, arg BankCountsParams) (BankCountsRow, error) {
	row := q.db.QueryRowContext(ctx, bankCounts,
		arg.BankID,
		arg.Owner,
		arg.BankID,
		arg.Owner,
		arg.BankID,
		arg.Owner,
		arg.BankID,
		arg.Owner,
		arg.BankID,
		arg.UserID,
		arg.BankID,
		arg.Owner,
	)
	var i BankCountsRow
	err := row.Scan(
		&i.QuestionCount,
		&i.KpCount,
		&i.QuestionReviewCount,
		&i.KpReviewCount,
		&i.MaterialCount,
		&i.PaperCount,
	)
	return i, err
}

const copyKPSources = `-- name: CopyKPSources :exec
INSERT IGNORE INTO kp_sources (kp_id, material_id, page_no, owner_user_id)
SELECT ?, src.material_id, src.page_no, src.owner_user_id FROM kp_sources src WHERE src.kp_id = ? AND src.owner_user_id = ?
`

type CopyKPSourcesParams struct {
	TargetID uint64
	SourceID uint64
	Owner    sql.NullInt64
}

func (q *Queries) CopyKPSources(ctx context.Context, arg CopyKPSourcesParams) error {
	_, err := q.db.ExecContext(ctx, copyKPSources, arg.TargetID, arg.SourceID, arg.Owner)
	return err
}

const deleteKP = `-- name: DeleteKP :execrows
DELETE FROM knowledge_points WHERE id = ? AND owner_user_id = ?
`

type DeleteKPParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteKP(ctx context.Context, arg DeleteKPParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteKP, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteKPRubric = `-- name: DeleteKPRubric :exec
DELETE FROM rubric_points WHERE kp_id = ? AND owner_user_id = ?
`

type DeleteKPRubricParams struct {
	KpID        sql.NullInt64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteKPRubric(ctx context.Context, arg DeleteKPRubricParams) error {
	_, err := q.db.ExecContext(ctx, deleteKPRubric, arg.KpID, arg.OwnerUserID)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :execrows
DELETE FROM questions WHERE id = ? AND owner_user_id = ?
`

type DeleteQuestionParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQuestion, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteQuestionKPs = `-- name: DeleteQuestionKPs :exec
DELETE FROM question_kps WHERE question_id = ? AND owner_user_id = ?
`

type DeleteQuestionKPsParams struct {
	QuestionID  uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteQuestionKPs(ctx context.Context, arg DeleteQuestionKPsParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionKPs, arg.QuestionID, arg.OwnerUserID)
	return err
}

const deleteQuestionRubric = `-- name: DeleteQuestionRubric :exec
DELETE FROM rubric_points WHERE question_id = ? AND owner_user_id = ?
`

type DeleteQuestionRubricParams struct {
	QuestionID  sql.NullInt64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteQuestionRubric(ctx context.Context, arg DeleteQuestionRubricParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionRubric, arg.QuestionID, arg.OwnerUserID)
	return err
}

const getKP = `-- name: GetKP :one
SELECT k.id, k.owner_user_id, k.bank_id, k.parent_id, k.level, k.name, k.original_text, k.source_material_id, k.source_page, k.origin, k.needs_review, k.ai_explanation, k.ai_explanation_at, k.exam_count, k.official_kp_id, k.sort_order, k.created_at, k.updated_at, b.subject_id FROM knowledge_points k JOIN banks b ON b.id = k.bank_id
WHERE k.id = ? AND k.owner_user_id = ?
`

type GetKPParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

type GetKPRow struct {
	ID               uint64
	OwnerUserID      sql.NullInt64
	BankID           uint64
	ParentID         sql.NullInt64
	Level            KnowledgePointsLevel
	Name             string
	OriginalText     sql.NullString
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	Origin           KnowledgePointsOrigin
	NeedsReview      bool
	AiExplanation    sql.NullString
	AiExplanationAt  sql.NullTime
	ExamCount        uint32
	OfficialKpID     sql.NullInt64
	SortOrder        uint32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SubjectID        sql.NullInt64
}

// 知识点与所在题库、专业课；归属按题库的所有者判断。
func (q *Queries) GetKP(ctx context.Context, arg GetKPParams) (GetKPRow, error) {
	row := q.db.QueryRowContext(ctx, getKP, arg.ID, arg.OwnerUserID)
	var i GetKPRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.ParentID,
		&i.Level,
		&i.Name,
		&i.OriginalText,
		&i.SourceMaterialID,
		&i.SourcePage,
		&i.Origin,
		&i.NeedsReview,
		&i.AiExplanation,
		&i.AiExplanationAt,
		&i.ExamCount,
		&i.OfficialKpID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubjectID,
	)
	return i, err
}

const getKPMastery = `-- name: GetKPMastery :one
SELECT owner_user_id, kp_id, m, state, viewed, answered, last_self_assess, last_self_assess_at, correct_dates, next_review_on, interval_step, recite_next_review_on, recite_interval_step, decay_applied_on, updated_at FROM kp_mastery WHERE owner_user_id = ? AND kp_id = ?
`

type GetKPMasteryParams struct {
	OwnerUserID uint64
	KpID        uint64
}

func (q *Queries) GetKPMastery(ctx context.Context, arg GetKPMasteryParams) (KpMastery, error) {
	row := q.db.QueryRowContext(ctx, getKPMastery, arg.OwnerUserID, arg.KpID)
	var i KpMastery
	err := row.Scan(
		&i.OwnerUserID,
		&i.KpID,
		&i.M,
		&i.State,
		&i.Viewed,
		&i.Answered,
		&i.LastSelfAssess,
		&i.LastSelfAssessAt,
		&i.CorrectDates,
		&i.NextReviewOn,
		&i.IntervalStep,
		&i.ReciteNextReviewOn,
		&i.ReciteIntervalStep,
		&i.DecayAppliedOn,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterialPage = `-- name: GetMaterialPage :one
SELECT p.material_id, p.page_no, p.owner_user_id, p.text, p.tables, p.low_confidence, m.file_name, m.page_count FROM material_pages p JOIN materials m ON m.id = p.material_id
WHERE p.material_id = ? AND p.page_no = ? AND p.owner_user_id = ? AND m.owner_user_id = ?
`

type GetMaterialPageParams struct {
	MaterialID    uint64
	PageNo        uint32
	OwnerUserID   uint64
	OwnerUserID_2 uint64
}

type GetMaterialPageRow struct {
	MaterialID    uint64
	PageNo        uint32
	OwnerUserID   uint64
	Text          string
	Tables        dbtypes.NullJSON
	LowConfidence dbtypes.NullJSON
	FileName      string
	PageCount     uint32
}

func (q *Queries) GetMaterialPage(ctx context.Context, arg GetMaterialPageParams) (GetMaterialPageRow, error) {
	row := q.db.QueryRowContext(ctx, getMaterialPage,
		arg.MaterialID,
		arg.PageNo,
		arg.OwnerUserID,
		arg.OwnerUserID_2,
	)
	var i GetMaterialPageRow
	err := row.Scan(
		&i.MaterialID,
		&i.PageNo,
		&i.OwnerUserID,
		&i.Text,
		&i.Tables,
		&i.LowConfidence,
		&i.FileName,
		&i.PageCount,
	)
	return i, err
}

const getQuestionFull = `-- name: GetQuestionFull :one
SELECT q.id, q.owner_user_id, q.bank_id, q.qtype, q.stem, q.options, q.answer, q.answer_origin, q.analysis, q.score, q.difficulty, q.source, q.exam_year, q.question_no, q.is_recollection, q.source_material_id, q.source_page, q.generated_from_kp_id, q.content_hash, q.rubric_version, q.status, q.needs_review, q.review_reasons, q.report_count, q.official_question_id, q.created_at, q.updated_at, q.required_words, b.subject_id FROM questions q JOIN banks b ON b.id = q.bank_id
WHERE q.id = ? AND q.owner_user_id = ?
`

type GetQuestionFullParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

type GetQuestionFullRow struct {
	ID                 uint64
	OwnerUserID        sql.NullInt64
	BankID             uint64
	Qtype              QuestionsQtype
	Stem               string
	Options            dbtypes.NullJSON
	Answer             sql.NullString
	AnswerOrigin       NullQuestionsAnswerOrigin
	Analysis           sql.NullString
	Score              sql.NullString
	Difficulty         NullQuestionsDifficulty
	Source             QuestionsSource
	ExamYear           sql.NullInt16
	QuestionNo         sql.NullString
	IsRecollection     bool
	SourceMaterialID   sql.NullInt64
	SourcePage         sql.NullInt32
	GeneratedFromKpID  sql.NullInt64
	ContentHash        string
	RubricVersion      uint32
	Status             QuestionsStatus
	NeedsReview        bool
	ReviewReasons      dbtypes.NullJSON
	ReportCount        uint32
	OfficialQuestionID sql.NullInt64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	RequiredWords      sql.NullInt16
	SubjectID          sql.NullInt64
}

func (q *Queries) GetQuestionFull(ctx context.Context, arg GetQuestionFullParams) (GetQuestionFullRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestionFull, arg.ID, arg.OwnerUserID)
	var i GetQuestionFullRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Qtype,
		&i.Stem,
		&i.Options,
		&i.Answer,
		&i.AnswerOrigin,
		&i.Analysis,
		&i.Score,
		&i.Difficulty,
		&i.Source,
		&i.ExamYear,
		&i.QuestionNo,
		&i.IsRecollection,
		&i.SourceMaterialID,
		&i.SourcePage,
		&i.GeneratedFromKpID,
		&i.ContentHash,
		&i.RubricVersion,
		&i.Status,
		&i.NeedsReview,
		&i.ReviewReasons,
		&i.ReportCount,
		&i.OfficialQuestionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredWords,
		&i.SubjectID,
	)
	return i, err
}

const getSubjectBank = `-- name: GetSubjectBank :one

SELECT s.id AS subject_id, s.name, s.full_score, s.is_essay, b.id AS bank_id FROM subjects s JOIN banks b ON b.subject_id = s.id
WHERE s.id = ? AND s.owner_user_id = ? AND b.owner_user_id = ?
`

type GetSubjectBankParams struct {
	ID            uint64
	OwnerUserID   uint64
	OwnerUserID_2 sql.NullInt64
}

type GetSubjectBankRow struct {
	SubjectID uint64
	Name      string
	FullScore uint16
	IsEssay   bool
	BankID    uint64
}

// 题库：知识点、题目、资料（T13）。每条查询都带 owner_user_id 归属条件。
func (q *Queries) GetSubjectBank(ctx context.Context, arg GetSubjectBankParams) (GetSubjectBankRow, error) {
	row := q.db.QueryRowContext(ctx, getSubjectBank, arg.ID, arg.OwnerUserID, arg.OwnerUserID_2)
	var i GetSubjectBankRow
	err := row.Scan(
		&i.SubjectID,
		&i.Name,
		&i.FullScore,
		&i.IsEssay,
		&i.BankID,
	)
	return i, err
}

const inWrongBook = `-- name: InWrongBook :one
SELECT EXISTS (SELECT 1 FROM wrong_book WHERE owner_user_id = ? AND question_id = ? AND status = 'active')
`

type InWrongBookParams struct {
	OwnerUserID uint64
	QuestionID  uint64
}

func (q *Queries) InWrongBook(ctx context.Context, arg InWrongBookParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, inWrongBook, arg.OwnerUserID, arg.QuestionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertKPMasteryCopy = `-- name: InsertKPMasteryCopy :exec
INSERT INTO kp_mastery (owner_user_id, kp_id, m, state, viewed, answered, last_self_assess, last_self_assess_at, correct_dates, next_review_on, interval_step)
SELECT owner_user_id, ?, m, state, viewed, answered, last_self_assess, last_self_assess_at, correct_dates, next_review_on, interval_step
FROM kp_mastery src WHERE src.owner_user_id = ? AND src.kp_id = ?
ON DUPLICATE KEY UPDATE
  m = GREATEST(kp_mastery.m, VALUES(m)),
  answered = GREATEST(kp_mastery.answered, VALUES(answered)),
  viewed = GREATEST(kp_mastery.viewed, VALUES(viewed))
`

type InsertKPMasteryCopyParams struct {
	TargetID uint64
	UserID   uint64
	SourceID uint64
}

// 合并掌握度：目标没有记录时沿用来源的；都有时保留作答过的、掌握分取较高者。
func (q *Queries) InsertKPMasteryCopy(ctx context.Context, arg InsertKPMasteryCopyParams) error {
	_, err := q.db.ExecContext(ctx, insertKPMasteryCopy, arg.TargetID, arg.UserID, arg.SourceID)
	return err
}

const listBankKPsFull = `-- name: ListBankKPsFull :many
SELECT k.id, k.parent_id, k.level, k.name, k.exam_count, k.needs_review, k.official_kp_id, k.sort_order,
  COALESCE(m.m, 0) AS m, COALESCE(m.state, 'unlearned') AS state
FROM knowledge_points k
LEFT JOIN kp_mastery m ON m.kp_id = k.id AND m.owner_user_id = ?
WHERE k.bank_id = ? AND k.owner_user_id = ?
ORDER BY k.sort_order, k.id
`

type ListBankKPsFullParams struct {
	UserID uint64
	BankID uint64
	Owner  sql.NullInt64
}

type ListBankKPsFullRow struct {
	ID           uint64
	ParentID     sql.NullInt64
	Level        KnowledgePointsLevel
	Name         string
	ExamCount    uint32
	NeedsReview  bool
	OfficialKpID sql.NullInt64
	SortOrder    uint32
	M            string
	State        KpMasteryState
}

func (q *Queries) ListBankKPsFull(ctx context.Context, arg ListBankKPsFullParams) ([]ListBankKPsFullRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankKPsFull, arg.UserID, arg.BankID, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankKPsFullRow{}
	for rows.Next() {
		var i ListBankKPsFullRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Name,
			&i.ExamCount,
			&i.NeedsReview,
			&i.OfficialKpID,
			&i.SortOrder,
			&i.M,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankQuestionsFull = `-- name: ListBankQuestionsFull :many
SELECT q.id, q.qtype, LEFT(q.stem, 120) AS stem, q.score, q.source, q.exam_year, q.needs_review, q.generated_from_kp_id, q.created_at,
  CAST(COALESCE((SELECT qk.kp_id FROM question_kps qk WHERE qk.question_id = q.id ORDER BY qk.is_primary DESC, qk.kp_id LIMIT 1), 0) AS UNSIGNED) AS primary_kp_id,
  (SELECT COUNT(*) FROM attempts a WHERE a.question_id = q.id AND a.owner_user_id = ?) AS attempt_count,
  (SELECT a.score FROM attempts a WHERE a.question_id = q.id AND a.owner_user_id = ? ORDER BY a.answered_at DESC, a.id DESC LIMIT 1) AS last_score,
  (SELECT MAX(a.answered_at) FROM attempts a WHERE a.question_id = q.id AND a.owner_user_id = ?) AS last_answered_at,
  EXISTS (SELECT 1 FROM wrong_book w WHERE w.question_id = q.id AND w.owner_user_id = ? AND w.status = 'active') AS in_wrong_book
FROM questions q
WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.status = 'active'
ORDER BY q.id
`

type ListBankQuestionsFullParams struct {
	UserID uint64
	BankID uint64
	Owner  sql.NullInt64
}

type ListBankQuestionsFullRow struct {
	ID                uint64
	Qtype             QuestionsQtype
	Stem              string
	Score             sql.NullString
	Source            QuestionsSource
	ExamYear          sql.NullInt16
	NeedsReview       bool
	GeneratedFromKpID sql.NullInt64
	CreatedAt         time.Time
	PrimaryKpID       int64
	AttemptCount      int64
	LastScore         sql.NullString
	LastAnsweredAt    interface{}
	InWrongBook       bool
}

// 题目列表（3.1b）：一次取出题库全部题目及作答概况，在服务端筛选、排序与分页（单个题库通常几百到几千题）。
func (q *Queries) ListBankQuestionsFull(ctx context.Context, arg ListBankQuestionsFullParams) ([]ListBankQuestionsFullRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankQuestionsFull,
		arg.UserID,
		arg.UserID,
		arg.UserID,
		arg.UserID,
		arg.BankID,
		arg.Owner,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankQuestionsFullRow{}
	for rows.Next() {
		var i ListBankQuestionsFullRow
		if err := rows.Scan(
			&i.ID,
			&i.Qtype,
			&i.Stem,
			&i.Score,
			&i.Source,
			&i.ExamYear,
			&i.NeedsReview,
			&i.GeneratedFromKpID,
			&i.CreatedAt,
			&i.PrimaryKpID,
			&i.AttemptCount,
			&i.LastScore,
			&i.LastAnsweredAt,
			&i.InWrongBook,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKPRubric = `-- name: ListKPRubric :many
SELECT id, owner_user_id, question_id, kp_id, seq, content, keywords, score, origin, created_at, updated_at FROM rubric_points WHERE kp_id = ? AND owner_user_id = ? ORDER BY seq
`

type ListKPRubricParams struct {
	KpID        sql.NullInt64
	OwnerUserID sql.NullInt64
}

func (q *Queries) ListKPRubric(ctx context.Context, arg ListKPRubricParams) ([]RubricPoint, error) {
	rows, err := q.db.QueryContext(ctx, listKPRubric, arg.KpID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RubricPoint{}
	for rows.Next() {
		var i RubricPoint
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.QuestionID,
			&i.KpID,
			&i.Seq,
			&i.Content,
			&i.Keywords,
			&i.Score,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKPSourcesOfKP = `-- name: ListKPSourcesOfKP :many
SELECT s.material_id, s.page_no, m.file_name FROM kp_sources s JOIN materials m ON m.id = s.material_id
WHERE s.kp_id = ? AND s.owner_user_id = ? ORDER BY s.material_id, s.page_no
`

type ListKPSourcesOfKPParams struct {
	KpID        uint64
	OwnerUserID sql.NullInt64
}

type ListKPSourcesOfKPRow struct {
	MaterialID uint64
	PageNo     uint32
	FileName   string
}

func (q *Queries) ListKPSourcesOfKP(ctx context.Context, arg ListKPSourcesOfKPParams) ([]ListKPSourcesOfKPRow, error) {
	rows, err := q.db.QueryContext(ctx, listKPSourcesOfKP, arg.KpID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKPSourcesOfKPRow{}
	for rows.Next() {
		var i ListKPSourcesOfKPRow
		if err := rows.Scan(&i.MaterialID, &i.PageNo, &i.FileName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKPsOnPage = `-- name: ListKPsOnPage :many
SELECT k.id, k.name FROM kp_sources s JOIN knowledge_points k ON k.id = s.kp_id
WHERE s.material_id = ? AND s.page_no = ? AND s.owner_user_id = ? ORDER BY k.id LIMIT 30
`

type ListKPsOnPageParams struct {
	MaterialID  uint64
	PageNo      uint32
	OwnerUserID sql.NullInt64
}

type ListKPsOnPageRow struct {
	ID   uint64
	Name string
}

func (q *Queries) ListKPsOnPage(ctx context.Context, arg ListKPsOnPageParams) ([]ListKPsOnPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listKPsOnPage, arg.MaterialID, arg.PageNo, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKPsOnPageRow{}
	for rows.Next() {
		var i ListKPsOnPageRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionAttempts = `-- name: ListQuestionAttempts :many
SELECT a.id, a.answered_at, a.score, a.full_score, a.is_correct,
  (SELECT g.point_results FROM gradings g WHERE g.attempt_id = a.id AND g.status = 'done' ORDER BY g.id DESC LIMIT 1) AS point_results,
  (SELECT g.loss FROM gradings g WHERE g.attempt_id = a.id AND g.status = 'done' ORDER BY g.id DESC LIMIT 1) AS loss
FROM attempts a WHERE a.question_id = ? AND a.owner_user_id = ?
ORDER BY a.answered_at DESC, a.id DESC LIMIT 50
`

type ListQuestionAttemptsParams struct {
	QuestionID  uint64
	OwnerUserID uint64
}

type ListQuestionAttemptsRow struct {
	ID           uint64
	AnsweredAt   time.Time
	Score        sql.NullString
	FullScore    sql.NullString
	IsCorrect    sql.NullBool
	PointResults dbtypes.NullJSON
	Loss         dbtypes.NullJSON
}

// 我的每次作答（3.3）与最近一次批改的逐点结果、失分归因。
func (q *Queries) ListQuestionAttempts(ctx context.Context, arg ListQuestionAttemptsParams) ([]ListQuestionAttemptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionAttempts, arg.QuestionID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionAttemptsRow{}
	for rows.Next() {
		var i ListQuestionAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.AnsweredAt,
			&i.Score,
			&i.FullScore,
			&i.IsCorrect,
			&i.PointResults,
			&i.Loss,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionKPs = `-- name: ListQuestionKPs :many
SELECT k.id, k.name, qk.is_primary FROM question_kps qk JOIN knowledge_points k ON k.id = qk.kp_id
WHERE qk.question_id = ? AND qk.owner_user_id = ? ORDER BY qk.is_primary DESC, k.id
`

type ListQuestionKPsParams struct {
	QuestionID  uint64
	OwnerUserID sql.NullInt64
}

type ListQuestionKPsRow struct {
	ID        uint64
	Name      string
	IsPrimary bool
}

func (q *Queries) ListQuestionKPs(ctx context.Context, arg ListQuestionKPsParams) ([]ListQuestionKPsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionKPs, arg.QuestionID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionKPsRow{}
	for rows.Next() {
		var i ListQuestionKPsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsPrimary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionRubric = `-- name: ListQuestionRubric :many
SELECT id, owner_user_id, question_id, kp_id, seq, content, keywords, score, origin, created_at, updated_at FROM rubric_points WHERE question_id = ? AND owner_user_id = ? ORDER BY seq
`

type ListQuestionRubricParams struct {
	QuestionID  sql.NullInt64
	OwnerUserID sql.NullInt64
}

func (q *Queries) ListQuestionRubric(ctx context.Context, arg ListQuestionRubricParams) ([]RubricPoint, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionRubric, arg.QuestionID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RubricPoint{}
	for rows.Next() {
		var i RubricPoint
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.QuestionID,
			&i.KpID,
			&i.Seq,
			&i.Content,
			&i.Keywords,
			&i.Score,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedQuestions = `-- name: ListRelatedQuestions :many
SELECT q.id, q.qtype, q.stem, q.source, q.exam_year FROM question_kps qk JOIN questions q ON q.id = qk.question_id
WHERE qk.kp_id = ? AND q.owner_user_id = ? AND q.status = 'active'
ORDER BY qk.is_primary DESC, q.id LIMIT 20
`

type ListRelatedQuestionsParams struct {
	KpID        uint64
	OwnerUserID sql.NullInt64
}

type ListRelatedQuestionsRow struct {
	ID       uint64
	Qtype    QuestionsQtype
	Stem     string
	Source   QuestionsSource
	ExamYear sql.NullInt16
}

func (q *Queries) ListRelatedQuestions(ctx context.Context, arg ListRelatedQuestionsParams) ([]ListRelatedQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelatedQuestions, arg.KpID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelatedQuestionsRow{}
	for rows.Next() {
		var i ListRelatedQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Qtype,
			&i.Stem,
			&i.Source,
			&i.ExamYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveKPChildren = `-- name: MoveKPChildren :exec
UPDATE knowledge_points SET parent_id = ? WHERE parent_id = ? AND owner_user_id = ?
`

type MoveKPChildrenParams struct {
	TargetID sql.NullInt64
	SourceID sql.NullInt64
	Owner    sql.NullInt64
}

func (q *Queries) MoveKPChildren(ctx context.Context, arg MoveKPChildrenParams) error {
	_, err := q.db.ExecContext(ctx, moveKPChildren, arg.TargetID, arg.SourceID, arg.Owner)
	return err
}

const moveKPRubric = `-- name: MoveKPRubric :exec
UPDATE rubric_points SET kp_id = ?, seq = seq + ? WHERE kp_id = ? AND owner_user_id = ?
`

type MoveKPRubricParams struct {
	TargetID sql.NullInt64
	Offset   uint16
	SourceID sql.NullInt64
	Owner    sql.NullInt64
}

func (q *Queries) MoveKPRubric(ctx context.Context, arg MoveKPRubricParams) error {
	_, err := q.db.ExecContext(ctx, moveKPRubric,
		arg.TargetID,
		arg.Offset,
		arg.SourceID,
		arg.Owner,
	)
	return err
}

const moveQuestionKPs = `-- name: MoveQuestionKPs :exec
INSERT IGNORE INTO question_kps (question_id, kp_id, is_primary, owner_user_id)
SELECT src.question_id, ?, src.is_primary, src.owner_user_id FROM question_kps src WHERE src.kp_id = ? AND src.owner_user_id = ?
`

type MoveQuestionKPsParams struct {
	TargetID uint64
	SourceID uint64
	Owner    sql.NullInt64
}

// 合并：把来源知识点的题目关联挂到目标知识点（已挂的跳过）。
func (q *Queries) MoveQuestionKPs(ctx context.Context, arg MoveQuestionKPsParams) error {
	_, err := q.db.ExecContext(ctx, moveQuestionKPs, arg.TargetID, arg.SourceID, arg.Owner)
	return err
}

const searchKPs = `-- name: SearchKPs :many
SELECT id, name, original_text, parent_id FROM knowledge_points
WHERE bank_id = ? AND owner_user_id = ? AND level = 'point'
  AND (name LIKE ? OR original_text LIKE ?)
ORDER BY id LIMIT 20
`

type SearchKPsParams struct {
	BankID      uint64
	Owner       sql.NullInt64
	NamePattern string
	TextPattern sql.NullString
}

type SearchKPsRow struct {
	ID           uint64
	Name         string
	OriginalText sql.NullString
	ParentID     sql.NullInt64
}

func (q *Queries) SearchKPs(ctx context.Context, arg SearchKPsParams) ([]SearchKPsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchKPs,
		arg.BankID,
		arg.Owner,
		arg.NamePattern,
		arg.TextPattern,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchKPsRow{}
	for rows.Next() {
		var i SearchKPsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OriginalText,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMaterialPages = `-- name: SearchMaterialPages :many
SELECT p.material_id, p.page_no, p.text, m.file_name FROM material_pages p JOIN materials m ON m.id = p.material_id
WHERE m.bank_id = ? AND p.owner_user_id = ? AND p.text LIKE ?
ORDER BY p.material_id, p.page_no LIMIT 20
`

type SearchMaterialPagesParams struct {
	BankID  uint64
	UserID  uint64
	Pattern string
}

type SearchMaterialPagesRow struct {
	MaterialID uint64
	PageNo     uint32
	Text       string
	FileName   string
}

func (q *Queries) SearchMaterialPages(ctx context.Context, arg SearchMaterialPagesParams) ([]SearchMaterialPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMaterialPages, arg.BankID, arg.UserID, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMaterialPagesRow{}
	for rows.Next() {
		var i SearchMaterialPagesRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.PageNo,
			&i.Text,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchQuestions = `-- name: SearchQuestions :many
SELECT id, qtype, stem FROM questions
WHERE bank_id = ? AND owner_user_id = ? AND status = 'active' AND stem LIKE ?
ORDER BY id LIMIT 20
`

type SearchQuestionsParams struct {
	BankID  uint64
	Owner   sql.NullInt64
	Pattern string
}

type SearchQuestionsRow struct {
	ID    uint64
	Qtype QuestionsQtype
	Stem  string
}

func (q *Queries) SearchQuestions(ctx context.Context, arg SearchQuestionsParams) ([]SearchQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchQuestions, arg.BankID, arg.Owner, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchQuestionsRow{}
	for rows.Next() {
		var i SearchQuestionsRow
		if err := rows.Scan(&i.ID, &i.Qtype, &i.Stem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKPExplanation = `-- name: SetKPExplanation :exec
UPDATE knowledge_points SET ai_explanation = ?, ai_explanation_at = ? WHERE id = ? AND owner_user_id = ?
`

type SetKPExplanationParams struct {
	AiExplanation   sql.NullString
	AiExplanationAt sql.NullTime
	ID              uint64
	OwnerUserID     sql.NullInt64
}

func (q *Queries) SetKPExplanation(ctx context.Context, arg SetKPExplanationParams) error {
	_, err := q.db.ExecContext(ctx, setKPExplanation,
		arg.AiExplanation,
		arg.AiExplanationAt,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updateKP = `-- name: UpdateKP :exec
UPDATE knowledge_points SET name = ?, original_text = ?, parent_id = ?, needs_review = ?, origin = ?
WHERE id = ? AND owner_user_id = ?
`

type UpdateKPParams struct {
	Name         string
	OriginalText sql.NullString
	ParentID     sql.NullInt64
	NeedsReview  bool
	Origin       KnowledgePointsOrigin
	ID           uint64
	OwnerUserID  sql.NullInt64
}

func (q *Queries) UpdateKP(ctx context.Context, arg UpdateKPParams) error {
	_, err := q.db.ExecContext(ctx, updateKP,
		arg.Name,
		arg.OriginalText,
		arg.ParentID,
		arg.NeedsReview,
		arg.Origin,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updateQuestion = `-- name: UpdateQuestion :exec
UPDATE questions SET qtype = ?, stem = ?, options = ?, answer = ?, answer_origin = ?, analysis = ?, score = ?, exam_year = ?, source = ?,
  content_hash = ?, rubric_version = ?, needs_review = ?, review_reasons = ?
WHERE id = ? AND owner_user_id = ?
`

type UpdateQuestionParams struct {
	Qtype         QuestionsQtype
	Stem          string
	Options       dbtypes.NullJSON
	Answer        sql.NullString
	AnswerOrigin  NullQuestionsAnswerOrigin
	Analysis      sql.NullString
	Score         sql.NullString
	ExamYear      sql.NullInt16
	Source        QuestionsSource
	ContentHash   string
	RubricVersion uint32
	NeedsReview   bool
	ReviewReasons dbtypes.NullJSON
	ID            uint64
	OwnerUserID   sql.NullInt64
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestion,
		arg.Qtype,
		arg.Stem,
		arg.Options,
		arg.Answer,
		arg.AnswerOrigin,
		arg.Analysis,
		arg.Score,
		arg.ExamYear,
		arg.Source,
		arg.ContentHash,
		arg.RubricVersion,
		arg.NeedsReview,
		arg.ReviewReasons,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const upsertKPSelfAssess = `-- name: UpsertKPSelfAssess :exec
INSERT INTO kp_mastery (owner_user_id, kp_id, m, state, viewed, last_self_assess, last_self_assess_at)
VALUES (?, ?, ?, ?, 1, ?, ?)
ON DUPLICATE KEY UPDATE
  m = IF(answered = 1, m, VALUES(m)),
  state = IF(answered = 1, state, VALUES(state)),
  viewed = 1,
  last_self_assess = VALUES(last_self_assess),
  last_self_assess_at = VALUES(last_self_assess_at)
`

type UpsertKPSelfAssessParams struct {
	OwnerUserID      uint64
	KpID             uint64
	M                string
	State            KpMasteryState
	LastSelfAssess   NullKpMasteryLastSelfAssess
	LastSelfAssessAt sql.NullTime
}

// 三档自评（3.4）：没有作答记录时设 M 与状态，有作答记录时只记录自评（D16）。
func (q *Queries) UpsertKPSelfAssess(ctx context.Context, arg UpsertKPSelfAssessParams) error {
	_, err := q.db.ExecContext(ctx, upsertKPSelfAssess,
		arg.OwnerUserID,
		arg.KpID,
		arg.M,
		arg.State,
		arg.LastSelfAssess,
		arg.LastSelfAssessAt,
	)
	return err
}
