// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package dbq

import (
	"context"
	"encoding/json"
)

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT flag_key, enabled_for_all FROM feature_flags
`

type ListFeatureFlagsRow struct {
	FlagKey       string
	EnabledForAll bool
}

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]ListFeatureFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeatureFlagsRow{}
	for rows.Next() {
		var i ListFeatureFlagsRow
		if err := rows.Scan(&i.FlagKey, &i.EnabledForAll); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleParams = `-- name: ListRuleParams :many

SELECT param_key, value FROM rule_params
`

type ListRuleParamsRow struct {
	ParamKey string
	Value    json.RawMessage
}

// 规则参数与功能开关（T06 读取，T07 / T29 管理）。
func (q *Queries) ListRuleParams(ctx context.Context) ([]ListRuleParamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuleParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuleParamsRow{}
	for rows.Next() {
		var i ListRuleParamsRow
		if err := rows.Scan(&i.ParamKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFeatureFlags = `-- name: ListUserFeatureFlags :many
SELECT flag_key FROM feature_flag_users WHERE user_id = ?
`

func (q *Queries) ListUserFeatureFlags(ctx context.Context, userID uint64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserFeatureFlags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var flag_key string
		if err := rows.Scan(&flag_key); err != nil {
			return nil, err
		}
		items = append(items, flag_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
