// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: essay.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const activateEssayRubric = `-- name: ActivateEssayRubric :execrows
UPDATE essay_rubrics SET is_active = 1 WHERE id = ? AND owner_user_id = ?
`

type ActivateEssayRubricParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) ActivateEssayRubric(ctx context.Context, arg ActivateEssayRubricParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateEssayRubric, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const disputeEssay = `-- name: DisputeEssay :exec
UPDATE essays SET disputed = 1, dispute_reason = ?, dispute_note = ?, score_before = score, status = 'grading', grading_round = grading_round + 1
WHERE id = ? AND owner_user_id = ?
`

type DisputeEssayParams struct {
	DisputeReason sql.NullString
	DisputeNote   sql.NullString
	ID            uint64
	OwnerUserID   uint64
}

func (q *Queries) DisputeEssay(ctx context.Context, arg DisputeEssayParams) error {
	_, err := q.db.ExecContext(ctx, disputeEssay,
		arg.DisputeReason,
		arg.DisputeNote,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const failEssayGrading = `-- name: FailEssayGrading :exec
UPDATE essays SET status = ?, fail_reason = ? WHERE id = ? AND owner_user_id = ?
`

type FailEssayGradingParams struct {
	Status      EssaysStatus
	FailReason  sql.NullString
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) FailEssayGrading(ctx context.Context, arg FailEssayGradingParams) error {
	_, err := q.db.ExecContext(ctx, failEssayGrading,
		arg.Status,
		arg.FailReason,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const finishEssayGrading = `-- name: FinishEssayGrading :exec
UPDATE essays SET status = 'graded', score = ?, full_score = ?, dimension_scores = ?, review = ?, counts_for_estimate = ?, model = ?,
  prompt_version = ?, graded_at = ?
WHERE id = ? AND owner_user_id = ?
`

type FinishEssayGradingParams struct {
	Score             sql.NullString
	FullScore         sql.NullString
	DimensionScores   dbtypes.NullJSON
	Review            dbtypes.NullJSON
	CountsForEstimate bool
	Model             sql.NullString
	PromptVersion     sql.NullString
	GradedAt          sql.NullTime
	ID                uint64
	OwnerUserID       uint64
}

func (q *Queries) FinishEssayGrading(ctx context.Context, arg FinishEssayGradingParams) error {
	_, err := q.db.ExecContext(ctx, finishEssayGrading,
		arg.Score,
		arg.FullScore,
		arg.DimensionScores,
		arg.Review,
		arg.CountsForEstimate,
		arg.Model,
		arg.PromptVersion,
		arg.GradedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const getEssay = `-- name: GetEssay :one
SELECT id, owner_user_id, subject_id, topic_source, topic_question_id, topic_text, required_words, draft_no, parent_essay_id, content, photo_keys, word_count, timed, duration_seconds, rubric_id, rubric_snapshot, status, score, full_score, dimension_scores, review, counts_for_estimate, model, prompt_version, idempotency_key, created_at, updated_at, graded_at, ai_topic_id, quota_period, grading_round, submitted_at, fail_reason, disputed, dispute_reason, dispute_note, score_before FROM essays WHERE id = ? AND owner_user_id = ?
`

type GetEssayParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetEssay(ctx context.Context, arg GetEssayParams) (Essay, error) {
	row := q.db.QueryRowContext(ctx, getEssay, arg.ID, arg.OwnerUserID)
	var i Essay
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.TopicSource,
		&i.TopicQuestionID,
		&i.TopicText,
		&i.RequiredWords,
		&i.DraftNo,
		&i.ParentEssayID,
		&i.Content,
		&i.PhotoKeys,
		&i.WordCount,
		&i.Timed,
		&i.DurationSeconds,
		&i.RubricID,
		&i.RubricSnapshot,
		&i.Status,
		&i.Score,
		&i.FullScore,
		&i.DimensionScores,
		&i.Review,
		&i.CountsForEstimate,
		&i.Model,
		&i.PromptVersion,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GradedAt,
		&i.AiTopicID,
		&i.QuotaPeriod,
		&i.GradingRound,
		&i.SubmittedAt,
		&i.FailReason,
		&i.Disputed,
		&i.DisputeReason,
		&i.DisputeNote,
		&i.ScoreBefore,
	)
	return i, err
}

const getEssayAITopic = `-- name: GetEssayAITopic :one
SELECT id, owner_user_id, subject_id, topic, required_words, note, model, prompt_version, created_at FROM essay_ai_topics WHERE id = ? AND owner_user_id = ?
`

type GetEssayAITopicParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetEssayAITopic(ctx context.Context, arg GetEssayAITopicParams) (EssayAiTopic, error) {
	row := q.db.QueryRowContext(ctx, getEssayAITopic, arg.ID, arg.OwnerUserID)
	var i EssayAiTopic
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.Topic,
		&i.RequiredWords,
		&i.Note,
		&i.Model,
		&i.PromptVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getEssayByKey = `-- name: GetEssayByKey :one
SELECT id, owner_user_id, subject_id, topic_source, topic_question_id, topic_text, required_words, draft_no, parent_essay_id, content, photo_keys, word_count, timed, duration_seconds, rubric_id, rubric_snapshot, status, score, full_score, dimension_scores, review, counts_for_estimate, model, prompt_version, idempotency_key, created_at, updated_at, graded_at, ai_topic_id, quota_period, grading_round, submitted_at, fail_reason, disputed, dispute_reason, dispute_note, score_before FROM essays WHERE owner_user_id = ? AND idempotency_key = ?
`

type GetEssayByKeyParams struct {
	OwnerUserID    uint64
	IdempotencyKey sql.NullString
}

func (q *Queries) GetEssayByKey(ctx context.Context, arg GetEssayByKeyParams) (Essay, error) {
	row := q.db.QueryRowContext(ctx, getEssayByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i Essay
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.TopicSource,
		&i.TopicQuestionID,
		&i.TopicText,
		&i.RequiredWords,
		&i.DraftNo,
		&i.ParentEssayID,
		&i.Content,
		&i.PhotoKeys,
		&i.WordCount,
		&i.Timed,
		&i.DurationSeconds,
		&i.RubricID,
		&i.RubricSnapshot,
		&i.Status,
		&i.Score,
		&i.FullScore,
		&i.DimensionScores,
		&i.Review,
		&i.CountsForEstimate,
		&i.Model,
		&i.PromptVersion,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GradedAt,
		&i.AiTopicID,
		&i.QuotaPeriod,
		&i.GradingRound,
		&i.SubmittedAt,
		&i.FailReason,
		&i.Disputed,
		&i.DisputeReason,
		&i.DisputeNote,
		&i.ScoreBefore,
	)
	return i, err
}

const getEssayForUpdate = `-- name: GetEssayForUpdate :one
SELECT id, owner_user_id, subject_id, topic_source, topic_question_id, topic_text, required_words, draft_no, parent_essay_id, content, photo_keys, word_count, timed, duration_seconds, rubric_id, rubric_snapshot, status, score, full_score, dimension_scores, review, counts_for_estimate, model, prompt_version, idempotency_key, created_at, updated_at, graded_at, ai_topic_id, quota_period, grading_round, submitted_at, fail_reason, disputed, dispute_reason, dispute_note, score_before FROM essays WHERE id = ? AND owner_user_id = ? FOR UPDATE
`

type GetEssayForUpdateParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetEssayForUpdate(ctx context.Context, arg GetEssayForUpdateParams) (Essay, error) {
	row := q.db.QueryRowContext(ctx, getEssayForUpdate, arg.ID, arg.OwnerUserID)
	var i Essay
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.TopicSource,
		&i.TopicQuestionID,
		&i.TopicText,
		&i.RequiredWords,
		&i.DraftNo,
		&i.ParentEssayID,
		&i.Content,
		&i.PhotoKeys,
		&i.WordCount,
		&i.Timed,
		&i.DurationSeconds,
		&i.RubricID,
		&i.RubricSnapshot,
		&i.Status,
		&i.Score,
		&i.FullScore,
		&i.DimensionScores,
		&i.Review,
		&i.CountsForEstimate,
		&i.Model,
		&i.PromptVersion,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GradedAt,
		&i.AiTopicID,
		&i.QuotaPeriod,
		&i.GradingRound,
		&i.SubmittedAt,
		&i.FailReason,
		&i.Disputed,
		&i.DisputeReason,
		&i.DisputeNote,
		&i.ScoreBefore,
	)
	return i, err
}

const getEssayTopicQuestion = `-- name: GetEssayTopicQuestion :one
SELECT q.id, q.stem, q.required_words, q.exam_year, b.subject_id
FROM questions q JOIN banks b ON b.id = q.bank_id
WHERE q.id = ? AND q.owner_user_id = ? AND q.qtype = 'essay' AND q.status = 'active'
`

type GetEssayTopicQuestionParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

type GetEssayTopicQuestionRow struct {
	ID            uint64
	Stem          string
	RequiredWords sql.NullInt16
	ExamYear      sql.NullInt16
	SubjectID     sql.NullInt64
}

// 真题作文题：必须是自己题库里的作文题。
func (q *Queries) GetEssayTopicQuestion(ctx context.Context, arg GetEssayTopicQuestionParams) (GetEssayTopicQuestionRow, error) {
	row := q.db.QueryRowContext(ctx, getEssayTopicQuestion, arg.ID, arg.OwnerUserID)
	var i GetEssayTopicQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Stem,
		&i.RequiredWords,
		&i.ExamYear,
		&i.SubjectID,
	)
	return i, err
}

const getGenericEssayRubric = `-- name: GetGenericEssayRubric :one
SELECT id, owner_user_id, subject_id, source, name, full_score, dimensions, source_material_id, source_page, is_active, origin, created_at, updated_at FROM essay_rubrics WHERE owner_user_id IS NULL AND source = 'generic' ORDER BY id LIMIT 1
`

func (q *Queries) GetGenericEssayRubric(ctx context.Context) (EssayRubric, error) {
	row := q.db.QueryRowContext(ctx, getGenericEssayRubric)
	var i EssayRubric
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.Source,
		&i.Name,
		&i.FullScore,
		&i.Dimensions,
		&i.SourceMaterialID,
		&i.SourcePage,
		&i.IsActive,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelEssay = `-- name: GetModelEssay :one
SELECT e.id, e.owner_user_id, e.bank_id, e.topic_question_id, e.title, e.content, e.structure, e.source_material_id, e.source_page, e.created_at, m.file_name, q.stem AS topic FROM model_essays e
LEFT JOIN materials m ON m.id = e.source_material_id LEFT JOIN questions q ON q.id = e.topic_question_id
WHERE e.id = ? AND e.owner_user_id = ?
`

type GetModelEssayParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

type GetModelEssayRow struct {
	ID               uint64
	OwnerUserID      sql.NullInt64
	BankID           uint64
	TopicQuestionID  sql.NullInt64
	Title            string
	Content          string
	Structure        dbtypes.NullJSON
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	CreatedAt        time.Time
	FileName         sql.NullString
	Topic            sql.NullString
}

func (q *Queries) GetModelEssay(ctx context.Context, arg GetModelEssayParams) (GetModelEssayRow, error) {
	row := q.db.QueryRowContext(ctx, getModelEssay, arg.ID, arg.OwnerUserID)
	var i GetModelEssayRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.TopicQuestionID,
		&i.Title,
		&i.Content,
		&i.Structure,
		&i.SourceMaterialID,
		&i.SourcePage,
		&i.CreatedAt,
		&i.FileName,
		&i.Topic,
	)
	return i, err
}

const insertEssay = `-- name: InsertEssay :execlastid

INSERT INTO essays (owner_user_id, subject_id, topic_source, topic_question_id, ai_topic_id, topic_text, required_words, draft_no, parent_essay_id,
  content, timed, idempotency_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, '', ?, ?)
`

type InsertEssayParams struct {
	OwnerUserID     uint64
	SubjectID       uint64
	TopicSource     EssaysTopicSource
	TopicQuestionID sql.NullInt64
	AiTopicID       sql.NullInt64
	TopicText       string
	RequiredWords   sql.NullInt16
	DraftNo         uint8
	ParentEssayID   sql.NullInt64
	Timed           bool
	IdempotencyKey  sql.NullString
}

// 作文（T23，PRD 模块 5、11.13）。每条都带 owner_user_id。
func (q *Queries) InsertEssay(ctx context.Context, arg InsertEssayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertEssay,
		arg.OwnerUserID,
		arg.SubjectID,
		arg.TopicSource,
		arg.TopicQuestionID,
		arg.AiTopicID,
		arg.TopicText,
		arg.RequiredWords,
		arg.DraftNo,
		arg.ParentEssayID,
		arg.Timed,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertEssayAITopic = `-- name: InsertEssayAITopic :execlastid
INSERT INTO essay_ai_topics (owner_user_id, subject_id, topic, required_words, note, model, prompt_version, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEssayAITopicParams struct {
	OwnerUserID   uint64
	SubjectID     uint64
	Topic         string
	RequiredWords sql.NullInt16
	Note          sql.NullString
	Model         sql.NullString
	PromptVersion sql.NullString
	CreatedAt     time.Time
}

func (q *Queries) InsertEssayAITopic(ctx context.Context, arg InsertEssayAITopicParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertEssayAITopic,
		arg.OwnerUserID,
		arg.SubjectID,
		arg.Topic,
		arg.RequiredWords,
		arg.Note,
		arg.Model,
		arg.PromptVersion,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listEssayAITopics = `-- name: ListEssayAITopics :many
SELECT id, owner_user_id, subject_id, topic, required_words, note, model, prompt_version, created_at FROM essay_ai_topics WHERE owner_user_id = ? AND subject_id = ? ORDER BY id DESC LIMIT 20
`

type ListEssayAITopicsParams struct {
	OwnerUserID uint64
	SubjectID   uint64
}

func (q *Queries) ListEssayAITopics(ctx context.Context, arg ListEssayAITopicsParams) ([]EssayAiTopic, error) {
	rows, err := q.db.QueryContext(ctx, listEssayAITopics, arg.OwnerUserID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EssayAiTopic{}
	for rows.Next() {
		var i EssayAiTopic
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.SubjectID,
			&i.Topic,
			&i.RequiredWords,
			&i.Note,
			&i.Model,
			&i.PromptVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEstimateEssays = `-- name: ListEstimateEssays :many
SELECT score, dimension_scores FROM essays
WHERE owner_user_id = ? AND subject_id = ? AND status = 'graded' AND counts_for_estimate = 1 AND score IS NOT NULL
ORDER BY graded_at DESC, id DESC LIMIT 10
`

type ListEstimateEssaysParams struct {
	OwnerUserID uint64
	SubjectID   uint64
}

type ListEstimateEssaysRow struct {
	Score           sql.NullString
	DimensionScores dbtypes.NullJSON
}

// 作文课预估分（PRD 11.13）：按用户评分细则批改、且以真题限时完成的作文，新的在前。
func (q *Queries) ListEstimateEssays(ctx context.Context, arg ListEstimateEssaysParams) ([]ListEstimateEssaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listEstimateEssays, arg.OwnerUserID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEstimateEssaysRow{}
	for rows.Next() {
		var i ListEstimateEssaysRow
		if err := rows.Scan(&i.Score, &i.DimensionScores); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectEssays = `-- name: ListSubjectEssays :many
SELECT id, topic_source, topic_question_id, ai_topic_id, topic_text, draft_no, parent_essay_id, word_count, timed, status, score, full_score,
  dimension_scores, counts_for_estimate, rubric_snapshot, created_at, graded_at
FROM essays WHERE owner_user_id = ? AND subject_id = ?
ORDER BY created_at DESC, id DESC
`

type ListSubjectEssaysParams struct {
	OwnerUserID uint64
	SubjectID   uint64
}

type ListSubjectEssaysRow struct {
	ID                uint64
	TopicSource       EssaysTopicSource
	TopicQuestionID   sql.NullInt64
	AiTopicID         sql.NullInt64
	TopicText         string
	DraftNo           uint8
	ParentEssayID     sql.NullInt64
	WordCount         uint32
	Timed             bool
	Status            EssaysStatus
	Score             sql.NullString
	FullScore         sql.NullString
	DimensionScores   dbtypes.NullJSON
	CountsForEstimate bool
	RubricSnapshot    dbtypes.NullJSON
	CreatedAt         time.Time
	GradedAt          sql.NullTime
}

// 作文本与作文训练首页：一门课的全部作文，新的在前。
func (q *Queries) ListSubjectEssays(ctx context.Context, arg ListSubjectEssaysParams) ([]ListSubjectEssaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectEssays, arg.OwnerUserID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectEssaysRow{}
	for rows.Next() {
		var i ListSubjectEssaysRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicSource,
			&i.TopicQuestionID,
			&i.AiTopicID,
			&i.TopicText,
			&i.DraftNo,
			&i.ParentEssayID,
			&i.WordCount,
			&i.Timed,
			&i.Status,
			&i.Score,
			&i.FullScore,
			&i.DimensionScores,
			&i.CountsForEstimate,
			&i.RubricSnapshot,
			&i.CreatedAt,
			&i.GradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicModelEssays = `-- name: ListTopicModelEssays :many
SELECT id, title, structure FROM model_essays WHERE owner_user_id = ? AND topic_question_id = ? ORDER BY id
`

type ListTopicModelEssaysParams struct {
	OwnerUserID     sql.NullInt64
	TopicQuestionID sql.NullInt64
}

type ListTopicModelEssaysRow struct {
	ID        uint64
	Title     string
	Structure dbtypes.NullJSON
}

// 范文对比（5.6）：用户导入的同题范文。
func (q *Queries) ListTopicModelEssays(ctx context.Context, arg ListTopicModelEssaysParams) ([]ListTopicModelEssaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopicModelEssays, arg.OwnerUserID, arg.TopicQuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicModelEssaysRow{}
	for rows.Next() {
		var i ListTopicModelEssaysRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Structure); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEssayRubrics = `-- name: ListUserEssayRubrics :many
SELECT r.id, r.owner_user_id, r.subject_id, r.source, r.name, r.full_score, r.dimensions, r.source_material_id, r.source_page, r.is_active, r.origin, r.created_at, r.updated_at, m.file_name FROM essay_rubrics r LEFT JOIN materials m ON m.id = r.source_material_id
WHERE r.owner_user_id = ? AND r.subject_id = ? ORDER BY r.id DESC
`

type ListUserEssayRubricsParams struct {
	OwnerUserID sql.NullInt64
	SubjectID   sql.NullInt64
}

type ListUserEssayRubricsRow struct {
	ID               uint64
	OwnerUserID      sql.NullInt64
	SubjectID        sql.NullInt64
	Source           EssayRubricsSource
	Name             string
	FullScore        string
	Dimensions       json.RawMessage
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	IsActive         bool
	Origin           EssayRubricsOrigin
	CreatedAt        time.Time
	UpdatedAt        time.Time
	FileName         sql.NullString
}

// 5.9「你的资料」：从用户资料识别出的评分标准，新的在前。
func (q *Queries) ListUserEssayRubrics(ctx context.Context, arg ListUserEssayRubricsParams) ([]ListUserEssayRubricsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserEssayRubrics, arg.OwnerUserID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserEssayRubricsRow{}
	for rows.Next() {
		var i ListUserEssayRubricsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.SubjectID,
			&i.Source,
			&i.Name,
			&i.FullScore,
			&i.Dimensions,
			&i.SourceMaterialID,
			&i.SourcePage,
			&i.IsActive,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEssayDraft = `-- name: SaveEssayDraft :execrows
UPDATE essays SET content = ?, word_count = ?, duration_seconds = ?, timed = ?, photo_keys = ?
WHERE id = ? AND owner_user_id = ? AND status IN ('draft', 'failed')
`

type SaveEssayDraftParams struct {
	Content         sql.NullString
	WordCount       uint32
	DurationSeconds uint32
	Timed           bool
	PhotoKeys       dbtypes.NullJSON
	ID              uint64
	OwnerUserID     uint64
}

// 草稿（客户端每 5 秒存一次）；提交后不能再改。
func (q *Queries) SaveEssayDraft(ctx context.Context, arg SaveEssayDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveEssayDraft,
		arg.Content,
		arg.WordCount,
		arg.DurationSeconds,
		arg.Timed,
		arg.PhotoKeys,
		arg.ID,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const submitEssay = `-- name: SubmitEssay :exec
UPDATE essays SET status = 'grading', rubric_id = ?, rubric_snapshot = ?, quota_period = ?, submitted_at = ?, grading_round = grading_round + 1,
  fail_reason = NULL
WHERE id = ? AND owner_user_id = ?
`

type SubmitEssayParams struct {
	RubricID       sql.NullInt64
	RubricSnapshot dbtypes.NullJSON
	QuotaPeriod    sql.NullString
	SubmittedAt    sql.NullTime
	ID             uint64
	OwnerUserID    uint64
}

func (q *Queries) SubmitEssay(ctx context.Context, arg SubmitEssayParams) error {
	_, err := q.db.ExecContext(ctx, submitEssay,
		arg.RubricID,
		arg.RubricSnapshot,
		arg.QuotaPeriod,
		arg.SubmittedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updateEssayRubric = `-- name: UpdateEssayRubric :execrows
UPDATE essay_rubrics SET name = ?, full_score = ?, dimensions = ?, origin = 'user_confirmed' WHERE id = ? AND owner_user_id = ?
`

type UpdateEssayRubricParams struct {
	Name        string
	FullScore   string
	Dimensions  json.RawMessage
	ID          uint64
	OwnerUserID sql.NullInt64
}

// 用户编辑评分标准：只影响之后的批改，已批改的作文存了标准快照，分数不变。
func (q *Queries) UpdateEssayRubric(ctx context.Context, arg UpdateEssayRubricParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEssayRubric,
		arg.Name,
		arg.FullScore,
		arg.Dimensions,
		arg.ID,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
