// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grading.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const completeGrading = `-- name: CompleteGrading :exec
UPDATE gradings SET status = 'done', trigger_reason = 'pending_resubmit', rubric_version = ?, rubric_snapshot = ?, score = ?, full_score = ?,
  point_results = ?, loss = ?, suggestions = ?, model = ?, prompt_version = ?, quota_charged = 1, finished_at = ?
WHERE id = ? AND owner_user_id = ? AND status = 'queued_quota'
`

type CompleteGradingParams struct {
	RubricVersion  sql.NullInt32
	RubricSnapshot dbtypes.NullJSON
	Score          sql.NullString
	FullScore      sql.NullString
	PointResults   dbtypes.NullJSON
	Loss           dbtypes.NullJSON
	Suggestions    dbtypes.NullJSON
	Model          sql.NullString
	PromptVersion  sql.NullString
	FinishedAt     sql.NullTime
	ID             uint64
	OwnerUserID    uint64
}

// 待批改提交后写入结果。
func (q *Queries) CompleteGrading(ctx context.Context, arg CompleteGradingParams) error {
	_, err := q.db.ExecContext(ctx, completeGrading,
		arg.RubricVersion,
		arg.RubricSnapshot,
		arg.Score,
		arg.FullScore,
		arg.PointResults,
		arg.Loss,
		arg.Suggestions,
		arg.Model,
		arg.PromptVersion,
		arg.FinishedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const correctWrongBookRate = `-- name: CorrectWrongBookRate :exec
UPDATE wrong_book SET last_score_rate = ? WHERE owner_user_id = ? AND question_id = ? AND status = 'active'
`

type CorrectWrongBookRateParams struct {
	LastScoreRate sql.NullString
	OwnerUserID   uint64
	QuestionID    uint64
}

func (q *Queries) CorrectWrongBookRate(ctx context.Context, arg CorrectWrongBookRateParams) error {
	_, err := q.db.ExecContext(ctx, correctWrongBookRate, arg.LastScoreRate, arg.OwnerUserID, arg.QuestionID)
	return err
}

const countDisputes = `-- name: CountDisputes :one
SELECT COUNT(*) FROM disputes WHERE grading_id = ? AND owner_user_id = ?
`

type CountDisputesParams struct {
	GradingID   uint64
	OwnerUserID uint64
}

func (q *Queries) CountDisputes(ctx context.Context, arg CountDisputesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDisputes, arg.GradingID, arg.OwnerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disputedGradings = `-- name: DisputedGradings :many
SELECT d.grading_id, d.regrade_id FROM disputes d WHERE d.owner_user_id = ? AND (d.grading_id = ? OR d.regrade_id = ?)
`

type DisputedGradingsParams struct {
	OwnerUserID uint64
	GradingID   uint64
	RegradeID   sql.NullInt64
}

type DisputedGradingsRow struct {
	GradingID uint64
	RegradeID sql.NullInt64
}

// 已复核过的批改（含被复核重批出来的新批改），每次批改只能复核一次。
func (q *Queries) DisputedGradings(ctx context.Context, arg DisputedGradingsParams) ([]DisputedGradingsRow, error) {
	rows, err := q.db.QueryContext(ctx, disputedGradings, arg.OwnerUserID, arg.GradingID, arg.RegradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DisputedGradingsRow{}
	for rows.Next() {
		var i DisputedGradingsRow
		if err := rows.Scan(&i.GradingID, &i.RegradeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dropPartialWrongBook = `-- name: DropPartialWrongBook :exec
UPDATE wrong_book SET status = 'removed', removed_at = ?
WHERE owner_user_id = ? AND question_id = ? AND status = 'active' AND added_reason = 'partial' AND wrong_count <= 1
`

type DropPartialWrongBookParams struct {
	RemovedAt   sql.NullTime
	OwnerUserID uint64
	QuestionID  uint64
}

// 重批后拿满分：这次批改收录的「没拿满分」错题撤回。
func (q *Queries) DropPartialWrongBook(ctx context.Context, arg DropPartialWrongBookParams) error {
	_, err := q.db.ExecContext(ctx, dropPartialWrongBook, arg.RemovedAt, arg.OwnerUserID, arg.QuestionID)
	return err
}

const getGrading = `-- name: GetGrading :one
SELECT g.id, g.owner_user_id, g.attempt_id, g.kind, g.trigger_reason, g.parent_grading_id, g.status, g.rubric_version, g.rubric_snapshot, g.score, g.full_score, g.point_results, g.loss, g.suggestions, g.model, g.prompt_version, g.quota_charged, g.fail_reason, g.idempotency_key, g.created_at, g.finished_at, a.question_id, a.answer_text, a.timed, a.answered_at, a.practice_session_id
FROM gradings g JOIN attempts a ON a.id = g.attempt_id
WHERE g.id = ? AND g.owner_user_id = ?
`

type GetGradingParams struct {
	ID          uint64
	OwnerUserID uint64
}

type GetGradingRow struct {
	ID                uint64
	OwnerUserID       uint64
	AttemptID         uint64
	Kind              GradingsKind
	TriggerReason     GradingsTriggerReason
	ParentGradingID   sql.NullInt64
	Status            GradingsStatus
	RubricVersion     sql.NullInt32
	RubricSnapshot    dbtypes.NullJSON
	Score             sql.NullString
	FullScore         sql.NullString
	PointResults      dbtypes.NullJSON
	Loss              dbtypes.NullJSON
	Suggestions       dbtypes.NullJSON
	Model             sql.NullString
	PromptVersion     sql.NullString
	QuotaCharged      bool
	FailReason        sql.NullString
	IdempotencyKey    sql.NullString
	CreatedAt         time.Time
	FinishedAt        sql.NullTime
	QuestionID        uint64
	AnswerText        sql.NullString
	Timed             bool
	AnsweredAt        time.Time
	PracticeSessionID sql.NullInt64
}

func (q *Queries) GetGrading(ctx context.Context, arg GetGradingParams) (GetGradingRow, error) {
	row := q.db.QueryRowContext(ctx, getGrading, arg.ID, arg.OwnerUserID)
	var i GetGradingRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AttemptID,
		&i.Kind,
		&i.TriggerReason,
		&i.ParentGradingID,
		&i.Status,
		&i.RubricVersion,
		&i.RubricSnapshot,
		&i.Score,
		&i.FullScore,
		&i.PointResults,
		&i.Loss,
		&i.Suggestions,
		&i.Model,
		&i.PromptVersion,
		&i.QuotaCharged,
		&i.FailReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.QuestionID,
		&i.AnswerText,
		&i.Timed,
		&i.AnsweredAt,
		&i.PracticeSessionID,
	)
	return i, err
}

const getGradingByKey = `-- name: GetGradingByKey :one

SELECT id, owner_user_id, attempt_id, kind, trigger_reason, parent_grading_id, status, rubric_version, rubric_snapshot, score, full_score, point_results, loss, suggestions, model, prompt_version, quota_charged, fail_reason, idempotency_key, created_at, finished_at FROM gradings WHERE owner_user_id = ? AND idempotency_key = ?
`

type GetGradingByKeyParams struct {
	OwnerUserID    uint64
	IdempotencyKey sql.NullString
}

// 主观题批改、待批改、异议（T18）。每条查询都带归属条件。
func (q *Queries) GetGradingByKey(ctx context.Context, arg GetGradingByKeyParams) (Grading, error) {
	row := q.db.QueryRowContext(ctx, getGradingByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i Grading
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AttemptID,
		&i.Kind,
		&i.TriggerReason,
		&i.ParentGradingID,
		&i.Status,
		&i.RubricVersion,
		&i.RubricSnapshot,
		&i.Score,
		&i.FullScore,
		&i.PointResults,
		&i.Loss,
		&i.Suggestions,
		&i.Model,
		&i.PromptVersion,
		&i.QuotaCharged,
		&i.FailReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertContentAccessGrant = `-- name: InsertContentAccessGrant :exec
INSERT INTO content_access_grants (user_id, source, source_id, scope, expires_at) VALUES (?, 'dispute', ?, ?, ?)
`

type InsertContentAccessGrantParams struct {
	UserID    uint64
	SourceID  uint64
	Scope     json.RawMessage
	ExpiresAt time.Time
}

func (q *Queries) InsertContentAccessGrant(ctx context.Context, arg InsertContentAccessGrantParams) error {
	_, err := q.db.ExecContext(ctx, insertContentAccessGrant,
		arg.UserID,
		arg.SourceID,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}

const insertDispute = `-- name: InsertDispute :execlastid
INSERT INTO disputes (owner_user_id, grading_id, reason, note, allow_access, regrade_id, score_before, score_after, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'rechecked')
`

type InsertDisputeParams struct {
	OwnerUserID uint64
	GradingID   uint64
	Reason      DisputesReason
	Note        sql.NullString
	AllowAccess bool
	RegradeID   sql.NullInt64
	ScoreBefore sql.NullString
	ScoreAfter  sql.NullString
}

func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDispute,
		arg.OwnerUserID,
		arg.GradingID,
		arg.Reason,
		arg.Note,
		arg.AllowAccess,
		arg.RegradeID,
		arg.ScoreBefore,
		arg.ScoreAfter,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertGrading = `-- name: InsertGrading :execlastid
INSERT INTO gradings (owner_user_id, attempt_id, kind, trigger_reason, parent_grading_id, status, rubric_version, rubric_snapshot,
  score, full_score, point_results, loss, suggestions, model, prompt_version, quota_charged, idempotency_key, finished_at)
VALUES (?, ?, 'subjective', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertGradingParams struct {
	OwnerUserID     uint64
	AttemptID       uint64
	TriggerReason   GradingsTriggerReason
	ParentGradingID sql.NullInt64
	Status          GradingsStatus
	RubricVersion   sql.NullInt32
	RubricSnapshot  dbtypes.NullJSON
	Score           sql.NullString
	FullScore       sql.NullString
	PointResults    dbtypes.NullJSON
	Loss            dbtypes.NullJSON
	Suggestions     dbtypes.NullJSON
	Model           sql.NullString
	PromptVersion   sql.NullString
	QuotaCharged    bool
	IdempotencyKey  sql.NullString
	FinishedAt      sql.NullTime
}

func (q *Queries) InsertGrading(ctx context.Context, arg InsertGradingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertGrading,
		arg.OwnerUserID,
		arg.AttemptID,
		arg.TriggerReason,
		arg.ParentGradingID,
		arg.Status,
		arg.RubricVersion,
		arg.RubricSnapshot,
		arg.Score,
		arg.FullScore,
		arg.PointResults,
		arg.Loss,
		arg.Suggestions,
		arg.Model,
		arg.PromptVersion,
		arg.QuotaCharged,
		arg.IdempotencyKey,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const latestDoneGrading = `-- name: LatestDoneGrading :one
SELECT id, owner_user_id, attempt_id, kind, trigger_reason, parent_grading_id, status, rubric_version, rubric_snapshot, score, full_score, point_results, loss, suggestions, model, prompt_version, quota_charged, fail_reason, idempotency_key, created_at, finished_at FROM gradings WHERE attempt_id = ? AND owner_user_id = ? AND status = 'done' ORDER BY id DESC LIMIT 1
`

type LatestDoneGradingParams struct {
	AttemptID   uint64
	OwnerUserID uint64
}

func (q *Queries) LatestDoneGrading(ctx context.Context, arg LatestDoneGradingParams) (Grading, error) {
	row := q.db.QueryRowContext(ctx, latestDoneGrading, arg.AttemptID, arg.OwnerUserID)
	var i Grading
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.AttemptID,
		&i.Kind,
		&i.TriggerReason,
		&i.ParentGradingID,
		&i.Status,
		&i.RubricVersion,
		&i.RubricSnapshot,
		&i.Score,
		&i.FullScore,
		&i.PointResults,
		&i.Loss,
		&i.Suggestions,
		&i.Model,
		&i.PromptVersion,
		&i.QuotaCharged,
		&i.FailReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listQueuedGradings = `-- name: ListQueuedGradings :many
SELECT g.id, g.attempt_id, g.created_at, a.question_id, q.qtype, q.stem
FROM gradings g JOIN attempts a ON a.id = g.attempt_id JOIN questions q ON q.id = a.question_id
WHERE g.owner_user_id = ? AND g.status = 'queued_quota'
ORDER BY g.id
`

type ListQueuedGradingsRow struct {
	ID         uint64
	AttemptID  uint64
	CreatedAt  time.Time
	QuestionID uint64
	Qtype      QuestionsQtype
	Stem       string
}

func (q *Queries) ListQueuedGradings(ctx context.Context, ownerUserID uint64) ([]ListQueuedGradingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedGradings, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueuedGradingsRow{}
	for rows.Next() {
		var i ListQueuedGradingsRow
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.CreatedAt,
			&i.QuestionID,
			&i.Qtype,
			&i.Stem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAttemptScore = `-- name: SetAttemptScore :exec
UPDATE attempts SET score = ?, full_score = ? WHERE id = ? AND owner_user_id = ?
`

type SetAttemptScoreParams struct {
	Score       sql.NullString
	FullScore   sql.NullString
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) SetAttemptScore(ctx context.Context, arg SetAttemptScoreParams) error {
	_, err := q.db.ExecContext(ctx, setAttemptScore,
		arg.Score,
		arg.FullScore,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const setAttemptTimed = `-- name: SetAttemptTimed :exec
UPDATE attempts SET timed = 1 WHERE id = ? AND owner_user_id = ?
`

type SetAttemptTimedParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) SetAttemptTimed(ctx context.Context, arg SetAttemptTimedParams) error {
	_, err := q.db.ExecContext(ctx, setAttemptTimed, arg.ID, arg.OwnerUserID)
	return err
}
