// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: importer.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const addImportJobMaterial = `-- name: AddImportJobMaterial :exec
INSERT INTO import_job_materials (job_id, material_id, owner_user_id) VALUES (?, ?, ?)
`

type AddImportJobMaterialParams struct {
	JobID       uint64
	MaterialID  uint64
	OwnerUserID uint64
}

func (q *Queries) AddImportJobMaterial(ctx context.Context, arg AddImportJobMaterialParams) error {
	_, err := q.db.ExecContext(ctx, addImportJobMaterial, arg.JobID, arg.MaterialID, arg.OwnerUserID)
	return err
}

const addImportJobPages = `-- name: AddImportJobPages :exec
UPDATE import_jobs SET reserved_pages = reserved_pages + ?, billed_pages = billed_pages + ?
WHERE id = ? AND owner_user_id = ?
`

type AddImportJobPagesParams struct {
	Reserved    uint32
	Billed      uint32
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) AddImportJobPages(ctx context.Context, arg AddImportJobPagesParams) error {
	_, err := q.db.ExecContext(ctx, addImportJobPages,
		arg.Reserved,
		arg.Billed,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const countActiveImportJobs = `-- name: CountActiveImportJobs :one
SELECT COUNT(*) FROM import_jobs WHERE owner_user_id = ? AND status IN ('queued', 'running')
`

func (q *Queries) CountActiveImportJobs(ctx context.Context, ownerUserID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveImportJobs, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImportItems = `-- name: CountImportItems :one
SELECT
  CAST(COALESCE(SUM(item_type = 'question'), 0) AS SIGNED) AS questions,
  CAST(COALESCE(SUM(item_type = 'knowledge_point'), 0) AS SIGNED) AS knowledge_points,
  CAST(COALESCE(SUM(needs_review = 1), 0) AS SIGNED) AS needs_review,
  CAST(COALESCE(SUM(item_type = 'question' AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.qtype')) IN ('term', 'short_answer', 'discussion', 'essay')), 0) AS SIGNED) AS subjective,
  CAST(COALESCE(SUM(item_type = 'question' AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.qtype')) NOT IN ('term', 'short_answer', 'discussion', 'essay')), 0) AS SIGNED) AS objective,
  CAST(COALESCE(SUM(status = 'confirmed' AND created_entity_id IS NOT NULL), 0) AS SIGNED) AS confirmed,
  CAST(COALESCE(SUM(item_type IN ('essay_topic', 'essay_rubric', 'writing_method', 'essay_material', 'model_essay')), 0) AS SIGNED) AS essay_items
FROM import_items WHERE job_id = ? AND owner_user_id = ? AND status <> 'deleted'
`

type CountImportItemsParams struct {
	JobID       uint64
	OwnerUserID uint64
}

type CountImportItemsRow struct {
	Questions       int64
	KnowledgePoints int64
	NeedsReview     int64
	Subjective      int64
	Objective       int64
	Confirmed       int64
	EssayItems      int64
}

func (q *Queries) CountImportItems(ctx context.Context, arg CountImportItemsParams) (CountImportItemsRow, error) {
	row := q.db.QueryRowContext(ctx, countImportItems, arg.JobID, arg.OwnerUserID)
	var i CountImportItemsRow
	err := row.Scan(
		&i.Questions,
		&i.KnowledgePoints,
		&i.NeedsReview,
		&i.Subjective,
		&i.Objective,
		&i.Confirmed,
		&i.EssayItems,
	)
	return i, err
}

const createImportJob = `-- name: CreateImportJob :execlastid

INSERT INTO import_jobs (owner_user_id, bank_id, mode, status, reserved_pages) VALUES (?, ?, ?, 'queued', 0)
`

type CreateImportJobParams struct {
	OwnerUserID uint64
	BankID      uint64
	Mode        ImportJobsMode
}

// 导入流水线（T10）。每条查询都带 owner_user_id 归属条件。
func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createImportJob, arg.OwnerUserID, arg.BankID, arg.Mode)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteImportAnswersOfMaterial = `-- name: DeleteImportAnswersOfMaterial :exec
DELETE FROM import_answers WHERE job_id = ? AND material_id = ? AND owner_user_id = ?
`

type DeleteImportAnswersOfMaterialParams struct {
	JobID       uint64
	MaterialID  uint64
	OwnerUserID uint64
}

func (q *Queries) DeleteImportAnswersOfMaterial(ctx context.Context, arg DeleteImportAnswersOfMaterialParams) error {
	_, err := q.db.ExecContext(ctx, deleteImportAnswersOfMaterial, arg.JobID, arg.MaterialID, arg.OwnerUserID)
	return err
}

const deleteImportItemsOfMaterial = `-- name: DeleteImportItemsOfMaterial :exec
DELETE FROM import_items WHERE job_id = ? AND material_id = ? AND owner_user_id = ? AND created_entity_id IS NULL
`

type DeleteImportItemsOfMaterialParams struct {
	JobID       uint64
	MaterialID  sql.NullInt64
	OwnerUserID uint64
}

// 从任务里移除文件（1.6b）时，它还没确认的条目一起删掉。
func (q *Queries) DeleteImportItemsOfMaterial(ctx context.Context, arg DeleteImportItemsOfMaterialParams) error {
	_, err := q.db.ExecContext(ctx, deleteImportItemsOfMaterial, arg.JobID, arg.MaterialID, arg.OwnerUserID)
	return err
}

const deleteImportJobMaterial = `-- name: DeleteImportJobMaterial :execrows
DELETE FROM import_job_materials WHERE job_id = ? AND material_id = ? AND owner_user_id = ?
`

type DeleteImportJobMaterialParams struct {
	JobID       uint64
	MaterialID  uint64
	OwnerUserID uint64
}

func (q *Queries) DeleteImportJobMaterial(ctx context.Context, arg DeleteImportJobMaterialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteImportJobMaterial, arg.JobID, arg.MaterialID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingItemsOfMaterial = `-- name: DeletePendingItemsOfMaterial :exec
DELETE FROM import_items WHERE job_id = ? AND material_id = ? AND owner_user_id = ? AND status = 'pending' AND created_entity_id IS NULL
`

type DeletePendingItemsOfMaterialParams struct {
	JobID       uint64
	MaterialID  sql.NullInt64
	OwnerUserID uint64
}

// 重跑结构化前删掉这份资料用户还没动过的条目；改过、确认过的保留。
func (q *Queries) DeletePendingItemsOfMaterial(ctx context.Context, arg DeletePendingItemsOfMaterialParams) error {
	_, err := q.db.ExecContext(ctx, deletePendingItemsOfMaterial, arg.JobID, arg.MaterialID, arg.OwnerUserID)
	return err
}

const getImportItem = `-- name: GetImportItem :one
SELECT i.id, i.owner_user_id, i.job_id, i.material_id, i.item_type, i.seq, i.payload, i.confidence, i.status, i.needs_review, i.review_reasons, i.duplicate_of_question_id, i.dedupe_key, i.created_entity_id, i.created_at, i.updated_at, j.bank_id FROM import_items i JOIN import_jobs j ON j.id = i.job_id
WHERE i.id = ? AND i.owner_user_id = ?
`

type GetImportItemParams struct {
	ID          uint64
	OwnerUserID uint64
}

type GetImportItemRow struct {
	ID                    uint64
	OwnerUserID           uint64
	JobID                 uint64
	MaterialID            sql.NullInt64
	ItemType              ImportItemsItemType
	Seq                   uint32
	Payload               json.RawMessage
	Confidence            sql.NullString
	Status                ImportItemsStatus
	NeedsReview           bool
	ReviewReasons         dbtypes.NullJSON
	DuplicateOfQuestionID sql.NullInt64
	DedupeKey             sql.NullString
	CreatedEntityID       sql.NullInt64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	BankID                uint64
}

func (q *Queries) GetImportItem(ctx context.Context, arg GetImportItemParams) (GetImportItemRow, error) {
	row := q.db.QueryRowContext(ctx, getImportItem, arg.ID, arg.OwnerUserID)
	var i GetImportItemRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.JobID,
		&i.MaterialID,
		&i.ItemType,
		&i.Seq,
		&i.Payload,
		&i.Confidence,
		&i.Status,
		&i.NeedsReview,
		&i.ReviewReasons,
		&i.DuplicateOfQuestionID,
		&i.DedupeKey,
		&i.CreatedEntityID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankID,
	)
	return i, err
}

const getImportJob = `-- name: GetImportJob :one
SELECT j.id, j.owner_user_id, j.bank_id, j.mode, j.status, j.reserved_pages, j.billed_pages, j.prompt_versions, j.fail_reason, j.started_at, j.finished_at, j.confirmed_at, j.created_at, j.updated_at, b.subject_id, s.name AS subject_name, s.full_score AS subject_full_score FROM import_jobs j
JOIN banks b ON b.id = j.bank_id JOIN subjects s ON s.id = b.subject_id
WHERE j.id = ? AND j.owner_user_id = ?
`

type GetImportJobParams struct {
	ID          uint64
	OwnerUserID uint64
}

type GetImportJobRow struct {
	ID               uint64
	OwnerUserID      uint64
	BankID           uint64
	Mode             ImportJobsMode
	Status           ImportJobsStatus
	ReservedPages    uint32
	BilledPages      uint32
	PromptVersions   dbtypes.NullJSON
	FailReason       sql.NullString
	StartedAt        sql.NullTime
	FinishedAt       sql.NullTime
	ConfirmedAt      sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SubjectID        sql.NullInt64
	SubjectName      string
	SubjectFullScore uint16
}

func (q *Queries) GetImportJob(ctx context.Context, arg GetImportJobParams) (GetImportJobRow, error) {
	row := q.db.QueryRowContext(ctx, getImportJob, arg.ID, arg.OwnerUserID)
	var i GetImportJobRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Mode,
		&i.Status,
		&i.ReservedPages,
		&i.BilledPages,
		&i.PromptVersions,
		&i.FailReason,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubjectID,
		&i.SubjectName,
		&i.SubjectFullScore,
	)
	return i, err
}

const getImportJobMaterial = `-- name: GetImportJobMaterial :one
SELECT job_id, material_id, owner_user_id, step, status, attempts, fail_reason, failed_pages, eta_seconds, updated_at, reserved_pages, quota_period, settled FROM import_job_materials WHERE job_id = ? AND material_id = ? AND owner_user_id = ?
`

type GetImportJobMaterialParams struct {
	JobID       uint64
	MaterialID  uint64
	OwnerUserID uint64
}

func (q *Queries) GetImportJobMaterial(ctx context.Context, arg GetImportJobMaterialParams) (ImportJobMaterial, error) {
	row := q.db.QueryRowContext(ctx, getImportJobMaterial, arg.JobID, arg.MaterialID, arg.OwnerUserID)
	var i ImportJobMaterial
	err := row.Scan(
		&i.JobID,
		&i.MaterialID,
		&i.OwnerUserID,
		&i.Step,
		&i.Status,
		&i.Attempts,
		&i.FailReason,
		&i.FailedPages,
		&i.EtaSeconds,
		&i.UpdatedAt,
		&i.ReservedPages,
		&i.QuotaPeriod,
		&i.Settled,
	)
	return i, err
}

const listBankKPs = `-- name: ListBankKPs :many
SELECT id, parent_id, level, name FROM knowledge_points WHERE bank_id = ? AND owner_user_id = ? ORDER BY sort_order, id
`

type ListBankKPsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListBankKPsRow struct {
	ID       uint64
	ParentID sql.NullInt64
	Level    KnowledgePointsLevel
	Name     string
}

func (q *Queries) ListBankKPs(ctx context.Context, arg ListBankKPsParams) ([]ListBankKPsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankKPs, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankKPsRow{}
	for rows.Next() {
		var i ListBankKPsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankQuestionsForDedupe = `-- name: ListBankQuestionsForDedupe :many
SELECT id, qtype, stem, content_hash FROM questions WHERE bank_id = ? AND owner_user_id = ? AND status = 'active'
`

type ListBankQuestionsForDedupeParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListBankQuestionsForDedupeRow struct {
	ID          uint64
	Qtype       QuestionsQtype
	Stem        string
	ContentHash string
}

func (q *Queries) ListBankQuestionsForDedupe(ctx context.Context, arg ListBankQuestionsForDedupeParams) ([]ListBankQuestionsForDedupeRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankQuestionsForDedupe, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankQuestionsForDedupeRow{}
	for rows.Next() {
		var i ListBankQuestionsForDedupeRow
		if err := rows.Scan(
			&i.ID,
			&i.Qtype,
			&i.Stem,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportAnswers = `-- name: ListImportAnswers :many
SELECT id, owner_user_id, job_id, material_id, exam_year, question_no, answer, page, dedupe_key, created_at FROM import_answers WHERE job_id = ? AND owner_user_id = ? ORDER BY id
`

type ListImportAnswersParams struct {
	JobID       uint64
	OwnerUserID uint64
}

func (q *Queries) ListImportAnswers(ctx context.Context, arg ListImportAnswersParams) ([]ImportAnswer, error) {
	rows, err := q.db.QueryContext(ctx, listImportAnswers, arg.JobID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportAnswer{}
	for rows.Next() {
		var i ImportAnswer
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.JobID,
			&i.MaterialID,
			&i.ExamYear,
			&i.QuestionNo,
			&i.Answer,
			&i.Page,
			&i.DedupeKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportItemsPage = `-- name: ListImportItemsPage :many
SELECT id, owner_user_id, job_id, material_id, item_type, seq, payload, confidence, status, needs_review, review_reasons, duplicate_of_question_id, dedupe_key, created_entity_id, created_at, updated_at FROM import_items
WHERE job_id = ? AND owner_user_id = ? AND status <> 'deleted' AND id > ?
  AND (? = 'all'
    OR (? = 'needs_review' AND needs_review = 1)
    OR (? = 'subjective' AND item_type = 'question' AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.qtype')) IN ('term', 'short_answer', 'discussion', 'essay'))
    OR (? = 'objective' AND item_type = 'question' AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.qtype')) NOT IN ('term', 'short_answer', 'discussion', 'essay')))
ORDER BY id LIMIT ?
`

type ListImportItemsPageParams struct {
	JobID       uint64
	OwnerUserID uint64
	AfterID     uint64
	Filter      interface{}
	Limit       int32
}

func (q *Queries) ListImportItemsPage(ctx context.Context, arg ListImportItemsPageParams) ([]ImportItem, error) {
	rows, err := q.db.QueryContext(ctx, listImportItemsPage,
		arg.JobID,
		arg.OwnerUserID,
		arg.AfterID,
		arg.Filter,
		arg.Filter,
		arg.Filter,
		arg.Filter,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportItem{}
	for rows.Next() {
		var i ImportItem
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.JobID,
			&i.MaterialID,
			&i.ItemType,
			&i.Seq,
			&i.Payload,
			&i.Confidence,
			&i.Status,
			&i.NeedsReview,
			&i.ReviewReasons,
			&i.DuplicateOfQuestionID,
			&i.DedupeKey,
			&i.CreatedEntityID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobMaterials = `-- name: ListImportJobMaterials :many
SELECT jm.job_id, jm.material_id, jm.owner_user_id, jm.step, jm.status, jm.attempts, jm.fail_reason, jm.failed_pages, jm.eta_seconds, jm.updated_at, jm.reserved_pages, jm.quota_period, jm.settled, m.file_name, m.format, m.billed_pages, m.page_count, m.category,
  (SELECT COUNT(*) FROM import_items i WHERE i.job_id = jm.job_id AND i.material_id = jm.material_id AND i.status <> 'deleted') AS recognized_count
FROM import_job_materials jm JOIN materials m ON m.id = jm.material_id
WHERE jm.job_id = ? AND jm.owner_user_id = ?
ORDER BY m.id
`

type ListImportJobMaterialsParams struct {
	JobID       uint64
	OwnerUserID uint64
}

type ListImportJobMaterialsRow struct {
	JobID           uint64
	MaterialID      uint64
	OwnerUserID     uint64
	Step            ImportJobMaterialsStep
	Status          ImportJobMaterialsStatus
	Attempts        uint8
	FailReason      sql.NullString
	FailedPages     dbtypes.NullJSON
	EtaSeconds      sql.NullInt32
	UpdatedAt       time.Time
	ReservedPages   uint32
	QuotaPeriod     sql.NullString
	Settled         bool
	FileName        string
	Format          MaterialsFormat
	BilledPages     uint32
	PageCount       uint32
	Category        NullMaterialsCategory
	RecognizedCount int64
}

func (q *Queries) ListImportJobMaterials(ctx context.Context, arg ListImportJobMaterialsParams) ([]ListImportJobMaterialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listImportJobMaterials, arg.JobID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportJobMaterialsRow{}
	for rows.Next() {
		var i ListImportJobMaterialsRow
		if err := rows.Scan(
			&i.JobID,
			&i.MaterialID,
			&i.OwnerUserID,
			&i.Step,
			&i.Status,
			&i.Attempts,
			&i.FailReason,
			&i.FailedPages,
			&i.EtaSeconds,
			&i.UpdatedAt,
			&i.ReservedPages,
			&i.QuotaPeriod,
			&i.Settled,
			&i.FileName,
			&i.Format,
			&i.BilledPages,
			&i.PageCount,
			&i.Category,
			&i.RecognizedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobs = `-- name: ListImportJobs :many
SELECT j.id FROM import_jobs j
WHERE j.owner_user_id = ?
  AND (? = 0 OR j.status IN ('queued', 'running', 'reviewing'))
ORDER BY j.created_at DESC, j.id DESC LIMIT 50
`

type ListImportJobsParams struct {
	OwnerUserID uint64
	ActiveOnly  interface{}
}

func (q *Queries) ListImportJobs(ctx context.Context, arg ListImportJobsParams) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listImportJobs, arg.OwnerUserID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobItems = `-- name: ListJobItems :many
SELECT id, owner_user_id, job_id, material_id, item_type, seq, payload, confidence, status, needs_review, review_reasons, duplicate_of_question_id, dedupe_key, created_entity_id, created_at, updated_at FROM import_items WHERE job_id = ? AND owner_user_id = ? AND status <> 'deleted' ORDER BY seq, id
`

type ListJobItemsParams struct {
	JobID       uint64
	OwnerUserID uint64
}

func (q *Queries) ListJobItems(ctx context.Context, arg ListJobItemsParams) ([]ImportItem, error) {
	rows, err := q.db.QueryContext(ctx, listJobItems, arg.JobID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportItem{}
	for rows.Next() {
		var i ImportItem
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.JobID,
			&i.MaterialID,
			&i.ItemType,
			&i.Seq,
			&i.Payload,
			&i.Confidence,
			&i.Status,
			&i.NeedsReview,
			&i.ReviewReasons,
			&i.DuplicateOfQuestionID,
			&i.DedupeKey,
			&i.CreatedEntityID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImportItemCreated = `-- name: SetImportItemCreated :exec
UPDATE import_items SET status = 'confirmed', created_entity_id = ? WHERE id = ? AND owner_user_id = ?
`

type SetImportItemCreatedParams struct {
	CreatedEntityID sql.NullInt64
	ID              uint64
	OwnerUserID     uint64
}

func (q *Queries) SetImportItemCreated(ctx context.Context, arg SetImportItemCreatedParams) error {
	_, err := q.db.ExecContext(ctx, setImportItemCreated, arg.CreatedEntityID, arg.ID, arg.OwnerUserID)
	return err
}

const setImportJobMaterialQuota = `-- name: SetImportJobMaterialQuota :exec
UPDATE import_job_materials SET reserved_pages = ?, quota_period = ?, settled = ? WHERE job_id = ? AND material_id = ? AND owner_user_id = ?
`

type SetImportJobMaterialQuotaParams struct {
	ReservedPages uint32
	QuotaPeriod   sql.NullString
	Settled       bool
	JobID         uint64
	MaterialID    uint64
	OwnerUserID   uint64
}

func (q *Queries) SetImportJobMaterialQuota(ctx context.Context, arg SetImportJobMaterialQuotaParams) error {
	_, err := q.db.ExecContext(ctx, setImportJobMaterialQuota,
		arg.ReservedPages,
		arg.QuotaPeriod,
		arg.Settled,
		arg.JobID,
		arg.MaterialID,
		arg.OwnerUserID,
	)
	return err
}

const setImportJobPromptVersions = `-- name: SetImportJobPromptVersions :exec
UPDATE import_jobs SET prompt_versions = ? WHERE id = ? AND owner_user_id = ?
`

type SetImportJobPromptVersionsParams struct {
	PromptVersions dbtypes.NullJSON
	ID             uint64
	OwnerUserID    uint64
}

func (q *Queries) SetImportJobPromptVersions(ctx context.Context, arg SetImportJobPromptVersionsParams) error {
	_, err := q.db.ExecContext(ctx, setImportJobPromptVersions, arg.PromptVersions, arg.ID, arg.OwnerUserID)
	return err
}

const updateImportItem = `-- name: UpdateImportItem :exec
UPDATE import_items SET payload = ?, status = ?, needs_review = ?, review_reasons = ?, duplicate_of_question_id = ?
WHERE id = ? AND owner_user_id = ?
`

type UpdateImportItemParams struct {
	Payload               json.RawMessage
	Status                ImportItemsStatus
	NeedsReview           bool
	ReviewReasons         dbtypes.NullJSON
	DuplicateOfQuestionID sql.NullInt64
	ID                    uint64
	OwnerUserID           uint64
}

func (q *Queries) UpdateImportItem(ctx context.Context, arg UpdateImportItemParams) error {
	_, err := q.db.ExecContext(ctx, updateImportItem,
		arg.Payload,
		arg.Status,
		arg.NeedsReview,
		arg.ReviewReasons,
		arg.DuplicateOfQuestionID,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updateImportJobMaterial = `-- name: UpdateImportJobMaterial :exec
UPDATE import_job_materials SET step = ?, status = ?, fail_reason = ?, attempts = ?
WHERE job_id = ? AND material_id = ? AND owner_user_id = ?
`

type UpdateImportJobMaterialParams struct {
	Step        ImportJobMaterialsStep
	Status      ImportJobMaterialsStatus
	FailReason  sql.NullString
	Attempts    uint8
	JobID       uint64
	MaterialID  uint64
	OwnerUserID uint64
}

func (q *Queries) UpdateImportJobMaterial(ctx context.Context, arg UpdateImportJobMaterialParams) error {
	_, err := q.db.ExecContext(ctx, updateImportJobMaterial,
		arg.Step,
		arg.Status,
		arg.FailReason,
		arg.Attempts,
		arg.JobID,
		arg.MaterialID,
		arg.OwnerUserID,
	)
	return err
}

const updateImportJobStatus = `-- name: UpdateImportJobStatus :exec
UPDATE import_jobs SET status = ?, fail_reason = ?,
  started_at = COALESCE(started_at, ?),
  finished_at = COALESCE(?, finished_at),
  confirmed_at = COALESCE(?, confirmed_at)
WHERE id = ? AND owner_user_id = ?
`

type UpdateImportJobStatusParams struct {
	Status      ImportJobsStatus
	FailReason  sql.NullString
	StartedAt   sql.NullTime
	FinishedAt  sql.NullTime
	ConfirmedAt sql.NullTime
	ID          uint64
	OwnerUserID uint64
}

// 时间由调用方给（数据库时间一律 UTC）；不改的时间传 NULL。
func (q *Queries) UpdateImportJobStatus(ctx context.Context, arg UpdateImportJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateImportJobStatus,
		arg.Status,
		arg.FailReason,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ConfirmedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const upsertImportAnswer = `-- name: UpsertImportAnswer :exec
INSERT INTO import_answers (owner_user_id, job_id, material_id, exam_year, question_no, answer, page, dedupe_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE answer = VALUES(answer), page = VALUES(page)
`

type UpsertImportAnswerParams struct {
	OwnerUserID uint64
	JobID       uint64
	MaterialID  uint64
	ExamYear    sql.NullInt16
	QuestionNo  string
	Answer      string
	Page        uint32
	DedupeKey   string
}

func (q *Queries) UpsertImportAnswer(ctx context.Context, arg UpsertImportAnswerParams) error {
	_, err := q.db.ExecContext(ctx, upsertImportAnswer,
		arg.OwnerUserID,
		arg.JobID,
		arg.MaterialID,
		arg.ExamYear,
		arg.QuestionNo,
		arg.Answer,
		arg.Page,
		arg.DedupeKey,
	)
	return err
}

const upsertImportItem = `-- name: UpsertImportItem :exec
INSERT INTO import_items (owner_user_id, job_id, material_id, item_type, seq, payload, confidence, needs_review, review_reasons, dedupe_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  payload = IF(status = 'pending', VALUES(payload), payload),
  confidence = IF(status = 'pending', VALUES(confidence), confidence),
  needs_review = IF(status = 'pending', VALUES(needs_review), needs_review),
  review_reasons = IF(status = 'pending', VALUES(review_reasons), review_reasons)
`

type UpsertImportItemParams struct {
	OwnerUserID   uint64
	JobID         uint64
	MaterialID    sql.NullInt64
	ItemType      ImportItemsItemType
	Seq           uint32
	Payload       json.RawMessage
	Confidence    sql.NullString
	NeedsReview   bool
	ReviewReasons dbtypes.NullJSON
	DedupeKey     sql.NullString
}

// 重跑同一步时按 dedupe_key 覆盖：用户还没动过（pending）的条目更新内容，已改过或已确认的保留用户的版本。
func (q *Queries) UpsertImportItem(ctx context.Context, arg UpsertImportItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertImportItem,
		arg.OwnerUserID,
		arg.JobID,
		arg.MaterialID,
		arg.ItemType,
		arg.Seq,
		arg.Payload,
		arg.Confidence,
		arg.NeedsReview,
		arg.ReviewReasons,
		arg.DedupeKey,
	)
	return err
}
