// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insight.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const deleteKPRelation = `-- name: DeleteKPRelation :execrows
DELETE FROM kp_relations WHERE id = ? AND owner_user_id = ?
`

type DeleteKPRelationParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteKPRelation(ctx context.Context, arg DeleteKPRelationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteKPRelation, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const essayMaterialExists = `-- name: EssayMaterialExists :one
SELECT EXISTS (SELECT 1 FROM essay_materials WHERE id = ? AND owner_user_id = ?)
`

type EssayMaterialExistsParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) EssayMaterialExists(ctx context.Context, arg EssayMaterialExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, essayMaterialExists, arg.ID, arg.OwnerUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActiveEssayRubric = `-- name: GetActiveEssayRubric :one
SELECT r.id, r.owner_user_id, r.subject_id, r.source, r.name, r.full_score, r.dimensions, r.source_material_id, r.source_page, r.is_active, r.origin, r.created_at, r.updated_at, m.file_name FROM essay_rubrics r LEFT JOIN materials m ON m.id = r.source_material_id
WHERE (r.owner_user_id = ? AND r.subject_id = ? AND r.is_active = 1) OR (r.owner_user_id IS NULL AND r.source = 'generic')
ORDER BY r.owner_user_id IS NULL, r.id DESC LIMIT 1
`

type GetActiveEssayRubricParams struct {
	UserID    sql.NullInt64
	SubjectID sql.NullInt64
}

type GetActiveEssayRubricRow struct {
	ID               uint64
	OwnerUserID      sql.NullInt64
	SubjectID        sql.NullInt64
	Source           EssayRubricsSource
	Name             string
	FullScore        string
	Dimensions       json.RawMessage
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	IsActive         bool
	Origin           EssayRubricsOrigin
	CreatedAt        time.Time
	UpdatedAt        time.Time
	FileName         sql.NullString
}

// 当前评分标准：用户资料里识别出的优先，没有时用通用五维度（PRD 11.13）。
func (q *Queries) GetActiveEssayRubric(ctx context.Context, arg GetActiveEssayRubricParams) (GetActiveEssayRubricRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveEssayRubric, arg.UserID, arg.SubjectID)
	var i GetActiveEssayRubricRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.Source,
		&i.Name,
		&i.FullScore,
		&i.Dimensions,
		&i.SourceMaterialID,
		&i.SourcePage,
		&i.IsActive,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileName,
	)
	return i, err
}

const getBankInsight = `-- name: GetBankInsight :one
SELECT exam_style, exam_style_key, relations_generated_at FROM banks WHERE id = ? AND owner_user_id = ?
`

type GetBankInsightParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

type GetBankInsightRow struct {
	ExamStyle            dbtypes.NullJSON
	ExamStyleKey         sql.NullString
	RelationsGeneratedAt sql.NullTime
}

func (q *Queries) GetBankInsight(ctx context.Context, arg GetBankInsightParams) (GetBankInsightRow, error) {
	row := q.db.QueryRowContext(ctx, getBankInsight, arg.ID, arg.OwnerUserID)
	var i GetBankInsightRow
	err := row.Scan(&i.ExamStyle, &i.ExamStyleKey, &i.RelationsGeneratedAt)
	return i, err
}

const getKPRelation = `-- name: GetKPRelation :one
SELECT id, owner_user_id, bank_id, kp_a_id, kp_b_id, relation_type, origin, created_at FROM kp_relations WHERE id = ? AND owner_user_id = ?
`

type GetKPRelationParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) GetKPRelation(ctx context.Context, arg GetKPRelationParams) (KpRelation, error) {
	row := q.db.QueryRowContext(ctx, getKPRelation, arg.ID, arg.OwnerUserID)
	var i KpRelation
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.KpAID,
		&i.KpBID,
		&i.RelationType,
		&i.Origin,
		&i.CreatedAt,
	)
	return i, err
}

const insertKPRelation = `-- name: InsertKPRelation :execlastid
INSERT INTO kp_relations (owner_user_id, bank_id, kp_a_id, kp_b_id, relation_type, origin) VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE relation_type = VALUES(relation_type), origin = VALUES(origin), id = LAST_INSERT_ID(id)
`

type InsertKPRelationParams struct {
	OwnerUserID  sql.NullInt64
	BankID       uint64
	KpAID        uint64
	KpBID        uint64
	RelationType KpRelationsRelationType
	Origin       KpRelationsOrigin
}

// kp_a_id < kp_b_id，同一对只存一条。
func (q *Queries) InsertKPRelation(ctx context.Context, arg InsertKPRelationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertKPRelation,
		arg.OwnerUserID,
		arg.BankID,
		arg.KpAID,
		arg.KpBID,
		arg.RelationType,
		arg.Origin,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listBankExamQuestions = `-- name: ListBankExamQuestions :many

SELECT id, qtype, score, exam_year, is_recollection, source_material_id, LEFT(stem, 200) AS stem
FROM questions WHERE bank_id = ? AND owner_user_id = ? AND source = 'exam' AND status = 'active'
ORDER BY exam_year, id
`

type ListBankExamQuestionsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListBankExamQuestionsRow struct {
	ID               uint64
	Qtype            QuestionsQtype
	Score            sql.NullString
	ExamYear         sql.NullInt16
	IsRecollection   bool
	SourceMaterialID sql.NullInt64
	Stem             string
}

// 考情分析、知识图谱、作文知识库（T14）。每条查询都带 owner_user_id。
func (q *Queries) ListBankExamQuestions(ctx context.Context, arg ListBankExamQuestionsParams) ([]ListBankExamQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankExamQuestions, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankExamQuestionsRow{}
	for rows.Next() {
		var i ListBankExamQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Qtype,
			&i.Score,
			&i.ExamYear,
			&i.IsRecollection,
			&i.SourceMaterialID,
			&i.Stem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankQuestionKPLinks = `-- name: ListBankQuestionKPLinks :many
SELECT qk.question_id, qk.kp_id FROM question_kps qk JOIN questions q ON q.id = qk.question_id
WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.status = 'active'
`

type ListBankQuestionKPLinksParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListBankQuestionKPLinksRow struct {
	QuestionID uint64
	KpID       uint64
}

func (q *Queries) ListBankQuestionKPLinks(ctx context.Context, arg ListBankQuestionKPLinksParams) ([]ListBankQuestionKPLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankQuestionKPLinks, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankQuestionKPLinksRow{}
	for rows.Next() {
		var i ListBankQuestionKPLinksRow
		if err := rows.Scan(&i.QuestionID, &i.KpID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEssayMaterialsKB = `-- name: ListEssayMaterialsKB :many
SELECT e.id, e.owner_user_id, e.bank_id, e.theme, e.content, e.source_material_id, e.source_page, e.origin, e.favorite, e.exam_count, e.created_at, m.file_name FROM essay_materials e LEFT JOIN materials m ON m.id = e.source_material_id
WHERE e.bank_id = ? AND e.owner_user_id = ? ORDER BY e.favorite DESC, e.theme, e.id
`

type ListEssayMaterialsKBParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListEssayMaterialsKBRow struct {
	ID               uint64
	OwnerUserID      sql.NullInt64
	BankID           uint64
	Theme            string
	Content          string
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	Origin           EssayMaterialsOrigin
	Favorite         bool
	ExamCount        uint32
	CreatedAt        time.Time
	FileName         sql.NullString
}

func (q *Queries) ListEssayMaterialsKB(ctx context.Context, arg ListEssayMaterialsKBParams) ([]ListEssayMaterialsKBRow, error) {
	rows, err := q.db.QueryContext(ctx, listEssayMaterialsKB, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEssayMaterialsKBRow{}
	for rows.Next() {
		var i ListEssayMaterialsKBRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BankID,
			&i.Theme,
			&i.Content,
			&i.SourceMaterialID,
			&i.SourcePage,
			&i.Origin,
			&i.Favorite,
			&i.ExamCount,
			&i.CreatedAt,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEssayTopicsKB = `-- name: ListEssayTopicsKB :many
SELECT q.id, q.stem, q.exam_year, q.required_words,
  (SELECT COUNT(*) FROM model_essays e WHERE e.topic_question_id = q.id) AS model_essay_count
FROM questions q WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.qtype = 'essay' AND q.status = 'active'
ORDER BY q.exam_year DESC, q.id
`

type ListEssayTopicsKBParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListEssayTopicsKBRow struct {
	ID              uint64
	Stem            string
	ExamYear        sql.NullInt16
	RequiredWords   sql.NullInt16
	ModelEssayCount int64
}

func (q *Queries) ListEssayTopicsKB(ctx context.Context, arg ListEssayTopicsKBParams) ([]ListEssayTopicsKBRow, error) {
	rows, err := q.db.QueryContext(ctx, listEssayTopicsKB, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEssayTopicsKBRow{}
	for rows.Next() {
		var i ListEssayTopicsKBRow
		if err := rows.Scan(
			&i.ID,
			&i.Stem,
			&i.ExamYear,
			&i.RequiredWords,
			&i.ModelEssayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKPRelations = `-- name: ListKPRelations :many
SELECT id, owner_user_id, bank_id, kp_a_id, kp_b_id, relation_type, origin, created_at FROM kp_relations WHERE bank_id = ? AND owner_user_id = ? ORDER BY id
`

type ListKPRelationsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) ListKPRelations(ctx context.Context, arg ListKPRelationsParams) ([]KpRelation, error) {
	rows, err := q.db.QueryContext(ctx, listKPRelations, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KpRelation{}
	for rows.Next() {
		var i KpRelation
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BankID,
			&i.KpAID,
			&i.KpBID,
			&i.RelationType,
			&i.Origin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelEssaysKB = `-- name: ListModelEssaysKB :many
SELECT e.id, e.title, e.topic_question_id, e.structure, e.source_material_id, e.source_page, m.file_name, q.stem AS topic
FROM model_essays e LEFT JOIN materials m ON m.id = e.source_material_id LEFT JOIN questions q ON q.id = e.topic_question_id
WHERE e.bank_id = ? AND e.owner_user_id = ? ORDER BY e.id
`

type ListModelEssaysKBParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListModelEssaysKBRow struct {
	ID               uint64
	Title            string
	TopicQuestionID  sql.NullInt64
	Structure        dbtypes.NullJSON
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	FileName         sql.NullString
	Topic            sql.NullString
}

func (q *Queries) ListModelEssaysKB(ctx context.Context, arg ListModelEssaysKBParams) ([]ListModelEssaysKBRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelEssaysKB, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelEssaysKBRow{}
	for rows.Next() {
		var i ListModelEssaysKBRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TopicQuestionID,
			&i.Structure,
			&i.SourceMaterialID,
			&i.SourcePage,
			&i.FileName,
			&i.Topic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWritingMethods = `-- name: ListWritingMethods :many
SELECT w.id, w.owner_user_id, w.bank_id, w.title, w.content, w.dimension, w.source_material_id, w.source_page, w.origin, w.mastery_state, w.created_at, m.file_name FROM writing_methods w LEFT JOIN materials m ON m.id = w.source_material_id
WHERE w.bank_id = ? AND w.owner_user_id = ? ORDER BY w.id
`

type ListWritingMethodsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListWritingMethodsRow struct {
	ID               uint64
	OwnerUserID      sql.NullInt64
	BankID           uint64
	Title            string
	Content          string
	Dimension        sql.NullString
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
	Origin           WritingMethodsOrigin
	MasteryState     WritingMethodsMasteryState
	CreatedAt        time.Time
	FileName         sql.NullString
}

func (q *Queries) ListWritingMethods(ctx context.Context, arg ListWritingMethodsParams) ([]ListWritingMethodsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWritingMethods, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWritingMethodsRow{}
	for rows.Next() {
		var i ListWritingMethodsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BankID,
			&i.Title,
			&i.Content,
			&i.Dimension,
			&i.SourceMaterialID,
			&i.SourcePage,
			&i.Origin,
			&i.MasteryState,
			&i.CreatedAt,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRelationsGenerated = `-- name: MarkRelationsGenerated :exec
UPDATE banks SET relations_generated_at = ? WHERE id = ? AND owner_user_id = ?
`

type MarkRelationsGeneratedParams struct {
	RelationsGeneratedAt sql.NullTime
	ID                   uint64
	OwnerUserID          sql.NullInt64
}

func (q *Queries) MarkRelationsGenerated(ctx context.Context, arg MarkRelationsGeneratedParams) error {
	_, err := q.db.ExecContext(ctx, markRelationsGenerated, arg.RelationsGeneratedAt, arg.ID, arg.OwnerUserID)
	return err
}

const setBankExamStyle = `-- name: SetBankExamStyle :exec
UPDATE banks SET exam_style = ?, exam_style_key = ? WHERE id = ? AND owner_user_id = ?
`

type SetBankExamStyleParams struct {
	ExamStyle    dbtypes.NullJSON
	ExamStyleKey sql.NullString
	ID           uint64
	OwnerUserID  sql.NullInt64
}

func (q *Queries) SetBankExamStyle(ctx context.Context, arg SetBankExamStyleParams) error {
	_, err := q.db.ExecContext(ctx, setBankExamStyle,
		arg.ExamStyle,
		arg.ExamStyleKey,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const setEssayMaterialFavorite = `-- name: SetEssayMaterialFavorite :execrows
UPDATE essay_materials SET favorite = ? WHERE id = ? AND owner_user_id = ?
`

type SetEssayMaterialFavoriteParams struct {
	Favorite    bool
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) SetEssayMaterialFavorite(ctx context.Context, arg SetEssayMaterialFavoriteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setEssayMaterialFavorite, arg.Favorite, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
