// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const activateInvite = `-- name: ActivateInvite :execrows
UPDATE invites SET activated_at = ?, inviter_days = ? WHERE id = ? AND activated_at IS NULL
`

type ActivateInviteParams struct {
	ActivatedAt sql.NullTime
	InviterDays uint16
	ID          uint64
}

func (q *Queries) ActivateInvite(ctx context.Context, arg ActivateInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateInvite, arg.ActivatedAt, arg.InviterDays, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countMyInvites = `-- name: CountMyInvites :one
SELECT COUNT(*) FROM invites WHERE inviter_id = ?
`

func (q *Queries) CountMyInvites(ctx context.Context, inviterID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMyInvites, inviterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPendingInviteForUpdate = `-- name: GetPendingInviteForUpdate :one
SELECT id, inviter_id, invitee_id, registered_at, activated_at, inviter_days FROM invites WHERE invitee_id = ? AND activated_at IS NULL FOR UPDATE
`

// 被邀请人第一次导入资料时激活；锁住这一行，并发确认导入只发一次奖励。
func (q *Queries) GetPendingInviteForUpdate(ctx context.Context, inviteeID uint64) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getPendingInviteForUpdate, inviteeID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.InviterID,
		&i.InviteeID,
		&i.RegisteredAt,
		&i.ActivatedAt,
		&i.InviterDays,
	)
	return i, err
}

const getUserByInviteCode = `-- name: GetUserByInviteCode :one

SELECT id, status FROM users WHERE invite_code = ?
`

type GetUserByInviteCodeRow struct {
	ID     uint64
	Status UsersStatus
}

// 邀请研友（T26，PRD 6.8、13.4）。
func (q *Queries) GetUserByInviteCode(ctx context.Context, inviteCode string) (GetUserByInviteCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByInviteCode, inviteCode)
	var i GetUserByInviteCodeRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT IGNORE INTO invites (inviter_id, invitee_id, registered_at) VALUES (?, ?, ?)
`

type InsertInviteParams struct {
	InviterID    uint64
	InviteeID    uint64
	RegisteredAt time.Time
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite, arg.InviterID, arg.InviteeID, arg.RegisteredAt)
	return err
}

const listMyInvites = `-- name: ListMyInvites :many
SELECT id, registered_at, activated_at, inviter_days FROM invites WHERE inviter_id = ? ORDER BY id DESC LIMIT 100
`

type ListMyInvitesRow struct {
	ID           uint64
	RegisteredAt time.Time
	ActivatedAt  sql.NullTime
	InviterDays  uint16
}

func (q *Queries) ListMyInvites(ctx context.Context, inviterID uint64) ([]ListMyInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyInvites, inviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyInvitesRow{}
	for rows.Next() {
		var i ListMyInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.RegisteredAt,
			&i.ActivatedAt,
			&i.InviterDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserRow = `-- name: LockUserRow :one
SELECT id FROM users WHERE id = ? FOR UPDATE
`

// 锁住邀请人，两个好友同时激活时累计天数不会超过上限。
func (q *Queries) LockUserRow(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockUserRow, id)
	var id_2 uint64
	err := row.Scan(&id_2)
	return id_2, err
}

const sumInviterDays = `-- name: SumInviterDays :one
SELECT CAST(COALESCE(SUM(inviter_days), 0) AS SIGNED) AS days FROM invites WHERE inviter_id = ?
`

func (q *Queries) SumInviterDays(ctx context.Context, inviterID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumInviterDays, inviterID)
	var days int64
	err := row.Scan(&days)
	return days, err
}
