// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: materials.sql

package dbq

import (
	"context"
	"database/sql"
	"time"

	"peetraining-server/internal/dbtypes"
)

const countKPsFromMaterial = `-- name: CountKPsFromMaterial :one
SELECT COUNT(DISTINCT kp_id) FROM kp_sources WHERE material_id = ?
`

func (q *Queries) CountKPsFromMaterial(ctx context.Context, materialID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKPsFromMaterial, materialID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMaterialImpact = `-- name: CountMaterialImpact :one
SELECT
  (SELECT COUNT(*) FROM questions q WHERE q.source_material_id = ?) AS question_count,
  (SELECT COUNT(*) FROM attempts a JOIN questions q ON q.id = a.question_id
     WHERE q.source_material_id = ?) AS attempt_count,
  (SELECT COUNT(*) FROM wrong_book w JOIN questions q ON q.id = w.question_id
     WHERE q.source_material_id = ? AND w.status = 'active') AS wrong_count,
  (SELECT COUNT(DISTINCT ps.id) FROM paper_sessions ps JOIN papers p ON p.id = ps.paper_id
     WHERE p.source_material_id = ?) AS paper_session_count
`

type CountMaterialImpactParams struct {
	MaterialID sql.NullInt64
}

type CountMaterialImpactRow struct {
	QuestionCount     int64
	AttemptCount      int64
	WrongCount        int64
	PaperSessionCount int64
}

// 删除资料前说明连带影响（3.1d）。调用前已用 GetMaterial 核对资料属于当前用户，下面按资料 ID 统计。
func (q *Queries) CountMaterialImpact(ctx context.Context, arg CountMaterialImpactParams) (CountMaterialImpactRow, error) {
	row := q.db.QueryRowContext(ctx, countMaterialImpact,
		arg.MaterialID,
		arg.MaterialID,
		arg.MaterialID,
		arg.MaterialID,
	)
	var i CountMaterialImpactRow
	err := row.Scan(
		&i.QuestionCount,
		&i.AttemptCount,
		&i.WrongCount,
		&i.PaperSessionCount,
	)
	return i, err
}

const createMaterial = `-- name: CreateMaterial :execlastid
INSERT INTO materials (owner_user_id, bank_id, category, file_name, format, size_bytes, page_count, billed_pages, sha256, status, right_confirmed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMaterialParams struct {
	OwnerUserID      uint64
	BankID           uint64
	Category         NullMaterialsCategory
	FileName         string
	Format           MaterialsFormat
	SizeBytes        uint64
	PageCount        uint32
	BilledPages      uint32
	Sha256           string
	Status           MaterialsStatus
	RightConfirmedAt time.Time
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMaterial,
		arg.OwnerUserID,
		arg.BankID,
		arg.Category,
		arg.FileName,
		arg.Format,
		arg.SizeBytes,
		arg.PageCount,
		arg.BilledPages,
		arg.Sha256,
		arg.Status,
		arg.RightConfirmedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteKnowledgePoint = `-- name: DeleteKnowledgePoint :exec
DELETE FROM knowledge_points WHERE id = ? AND bank_id = ?
`

type DeleteKnowledgePointParams struct {
	ID     uint64
	BankID uint64
}

func (q *Queries) DeleteKnowledgePoint(ctx context.Context, arg DeleteKnowledgePointParams) error {
	_, err := q.db.ExecContext(ctx, deleteKnowledgePoint, arg.ID, arg.BankID)
	return err
}

const deleteMaterial = `-- name: DeleteMaterial :execrows
DELETE FROM materials WHERE id = ? AND owner_user_id = ?
`

type DeleteMaterialParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) DeleteMaterial(ctx context.Context, arg DeleteMaterialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMaterial, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteQuestionsFromMaterial = `-- name: DeleteQuestionsFromMaterial :exec
DELETE FROM questions WHERE source_material_id = ? AND bank_id = ?
`

type DeleteQuestionsFromMaterialParams struct {
	SourceMaterialID sql.NullInt64
	BankID           uint64
}

func (q *Queries) DeleteQuestionsFromMaterial(ctx context.Context, arg DeleteQuestionsFromMaterialParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionsFromMaterial, arg.SourceMaterialID, arg.BankID)
	return err
}

const detachPapersFromMaterial = `-- name: DetachPapersFromMaterial :exec
DELETE FROM papers WHERE source_material_id = ? AND bank_id = ?
`

type DetachPapersFromMaterialParams struct {
	SourceMaterialID sql.NullInt64
	BankID           uint64
}

// 用它做过的整卷成绩保留：试卷本身删除，paper_sessions.paper_id 置空（外键 SET NULL）。
func (q *Queries) DetachPapersFromMaterial(ctx context.Context, arg DetachPapersFromMaterialParams) error {
	_, err := q.db.ExecContext(ctx, detachPapersFromMaterial, arg.SourceMaterialID, arg.BankID)
	return err
}

const getBankForSubject = `-- name: GetBankForSubject :one

SELECT b.id, b.source, b.owner_user_id, b.subject_id, b.title, b.school_major_tag, b.subject_code, b.created_at, b.updated_at FROM banks b JOIN subjects s ON s.id = b.subject_id
WHERE s.id = ? AND s.owner_user_id = ? AND b.owner_user_id = ?
`

type GetBankForSubjectParams struct {
	ID            uint64
	OwnerUserID   uint64
	OwnerUserID_2 sql.NullInt64
}

// 资料（T08）。每条查询都带 owner_user_id 归属条件。
func (q *Queries) GetBankForSubject(ctx context.Context, arg GetBankForSubjectParams) (Bank, error) {
	row := q.db.QueryRowContext(ctx, getBankForSubject, arg.ID, arg.OwnerUserID, arg.OwnerUserID_2)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.Title,
		&i.SchoolMajorTag,
		&i.SubjectCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterial = `-- name: GetMaterial :one
SELECT m.id, m.owner_user_id, m.bank_id, m.category, m.sub_type, m.file_name, m.format, m.object_key, m.size_bytes, m.page_count, m.billed_pages, m.sha256, m.status, m.fail_reason, m.question_count, m.kp_count, m.right_confirmed_at, m.created_at, m.updated_at, b.subject_id FROM materials m JOIN banks b ON b.id = m.bank_id
WHERE m.id = ? AND m.owner_user_id = ?
`

type GetMaterialParams struct {
	ID          uint64
	OwnerUserID uint64
}

type GetMaterialRow struct {
	ID               uint64
	OwnerUserID      uint64
	BankID           uint64
	Category         NullMaterialsCategory
	SubType          sql.NullString
	FileName         string
	Format           MaterialsFormat
	ObjectKey        sql.NullString
	SizeBytes        uint64
	PageCount        uint32
	BilledPages      uint32
	Sha256           string
	Status           MaterialsStatus
	FailReason       sql.NullString
	QuestionCount    uint32
	KpCount          uint32
	RightConfirmedAt time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SubjectID        sql.NullInt64
}

func (q *Queries) GetMaterial(ctx context.Context, arg GetMaterialParams) (GetMaterialRow, error) {
	row := q.db.QueryRowContext(ctx, getMaterial, arg.ID, arg.OwnerUserID)
	var i GetMaterialRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Category,
		&i.SubType,
		&i.FileName,
		&i.Format,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.PageCount,
		&i.BilledPages,
		&i.Sha256,
		&i.Status,
		&i.FailReason,
		&i.QuestionCount,
		&i.KpCount,
		&i.RightConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubjectID,
	)
	return i, err
}

const getMaterialBySha = `-- name: GetMaterialBySha :one
SELECT id, owner_user_id, bank_id, category, sub_type, file_name, format, object_key, size_bytes, page_count, billed_pages, sha256, status, fail_reason, question_count, kp_count, right_confirmed_at, created_at, updated_at FROM materials WHERE owner_user_id = ? AND sha256 = ?
`

type GetMaterialByShaParams struct {
	OwnerUserID uint64
	Sha256      string
}

func (q *Queries) GetMaterialBySha(ctx context.Context, arg GetMaterialByShaParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, getMaterialBySha, arg.OwnerUserID, arg.Sha256)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Category,
		&i.SubType,
		&i.FileName,
		&i.Format,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.PageCount,
		&i.BilledPages,
		&i.Sha256,
		&i.Status,
		&i.FailReason,
		&i.QuestionCount,
		&i.KpCount,
		&i.RightConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKPsOnlyFromMaterial = `-- name: ListKPsOnlyFromMaterial :many
SELECT k.id FROM knowledge_points k
WHERE k.bank_id = ?
  AND EXISTS (SELECT 1 FROM kp_sources s WHERE s.kp_id = k.id AND s.material_id = ?)
  AND NOT EXISTS (SELECT 1 FROM kp_sources s WHERE s.kp_id = k.id AND s.material_id <> ?)
`

type ListKPsOnlyFromMaterialParams struct {
	BankID     uint64
	MaterialID uint64
}

// 只来自这份资料的知识点：它有来源记录，且全部来源都是这份资料。
// 调用前已核对资料属于当前用户；再限定在资料所在的题库内。
func (q *Queries) ListKPsOnlyFromMaterial(ctx context.Context, arg ListKPsOnlyFromMaterialParams) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listKPsOnlyFromMaterial, arg.BankID, arg.MaterialID, arg.MaterialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialPages = `-- name: ListMaterialPages :many
SELECT material_id, page_no, owner_user_id, text, tables, low_confidence FROM material_pages WHERE material_id = ? AND owner_user_id = ? ORDER BY page_no
`

type ListMaterialPagesParams struct {
	MaterialID  uint64
	OwnerUserID uint64
}

func (q *Queries) ListMaterialPages(ctx context.Context, arg ListMaterialPagesParams) ([]MaterialPage, error) {
	rows, err := q.db.QueryContext(ctx, listMaterialPages, arg.MaterialID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialPage{}
	for rows.Next() {
		var i MaterialPage
		if err := rows.Scan(
			&i.MaterialID,
			&i.PageNo,
			&i.OwnerUserID,
			&i.Text,
			&i.Tables,
			&i.LowConfidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsByBank = `-- name: ListMaterialsByBank :many
SELECT m.id, m.owner_user_id, m.bank_id, m.category, m.sub_type, m.file_name, m.format, m.object_key, m.size_bytes, m.page_count, m.billed_pages, m.sha256, m.status, m.fail_reason, m.question_count, m.kp_count, m.right_confirmed_at, m.created_at, m.updated_at,
  (SELECT COUNT(DISTINCT p.id) FROM papers p WHERE p.source_material_id = m.id) AS paper_count,
  (SELECT COUNT(*) FROM questions q WHERE q.source_material_id = m.id AND q.needs_review = 1 AND q.status = 'active') AS needs_review_count
FROM materials m
WHERE m.bank_id = ? AND m.owner_user_id = ?
ORDER BY m.created_at DESC, m.id DESC
`

type ListMaterialsByBankParams struct {
	BankID      uint64
	OwnerUserID uint64
}

type ListMaterialsByBankRow struct {
	ID               uint64
	OwnerUserID      uint64
	BankID           uint64
	Category         NullMaterialsCategory
	SubType          sql.NullString
	FileName         string
	Format           MaterialsFormat
	ObjectKey        sql.NullString
	SizeBytes        uint64
	PageCount        uint32
	BilledPages      uint32
	Sha256           string
	Status           MaterialsStatus
	FailReason       sql.NullString
	QuestionCount    uint32
	KpCount          uint32
	RightConfirmedAt time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	PaperCount       int64
	NeedsReviewCount int64
}

func (q *Queries) ListMaterialsByBank(ctx context.Context, arg ListMaterialsByBankParams) ([]ListMaterialsByBankRow, error) {
	rows, err := q.db.QueryContext(ctx, listMaterialsByBank, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialsByBankRow{}
	for rows.Next() {
		var i ListMaterialsByBankRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BankID,
			&i.Category,
			&i.SubType,
			&i.FileName,
			&i.Format,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.PageCount,
			&i.BilledPages,
			&i.Sha256,
			&i.Status,
			&i.FailReason,
			&i.QuestionCount,
			&i.KpCount,
			&i.RightConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaperCount,
			&i.NeedsReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointKPSources = `-- name: RepointKPSources :exec
UPDATE knowledge_points k
JOIN (
  SELECT s.kp_id, MIN(s.material_id) AS alt_material_id FROM kp_sources s
  WHERE s.material_id <> ? GROUP BY s.kp_id
) alt ON alt.kp_id = k.id
SET k.source_material_id = alt.alt_material_id,
    k.source_page = (SELECT MIN(s2.page_no) FROM kp_sources s2 WHERE s2.kp_id = k.id AND s2.material_id = alt.alt_material_id)
WHERE k.bank_id = ? AND k.source_material_id = ?
`

type RepointKPSourcesParams struct {
	MaterialID       uint64
	BankID           uint64
	SourceMaterialID sql.NullInt64
}

// 保留下来的知识点（其他资料也有）把「出处」改指到另一份资料，避免指向已删除的资料。
// 三个参数依次是：要删除的资料 ID、题库 ID、要删除的资料 ID。
func (q *Queries) RepointKPSources(ctx context.Context, arg RepointKPSourcesParams) error {
	_, err := q.db.ExecContext(ctx, repointKPSources, arg.MaterialID, arg.BankID, arg.SourceMaterialID)
	return err
}

const setMaterialObjectKey = `-- name: SetMaterialObjectKey :exec
UPDATE materials SET object_key = ? WHERE id = ? AND owner_user_id = ?
`

type SetMaterialObjectKeyParams struct {
	ObjectKey   sql.NullString
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) SetMaterialObjectKey(ctx context.Context, arg SetMaterialObjectKeyParams) error {
	_, err := q.db.ExecContext(ctx, setMaterialObjectKey, arg.ObjectKey, arg.ID, arg.OwnerUserID)
	return err
}

const updateMaterialCategory = `-- name: UpdateMaterialCategory :exec
UPDATE materials SET category = ?, sub_type = ? WHERE id = ? AND owner_user_id = ?
`

type UpdateMaterialCategoryParams struct {
	Category    NullMaterialsCategory
	SubType     sql.NullString
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) UpdateMaterialCategory(ctx context.Context, arg UpdateMaterialCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateMaterialCategory,
		arg.Category,
		arg.SubType,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updateMaterialPages = `-- name: UpdateMaterialPages :exec
UPDATE materials SET page_count = ?, billed_pages = ? WHERE id = ? AND owner_user_id = ?
`

type UpdateMaterialPagesParams struct {
	PageCount   uint32
	BilledPages uint32
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) UpdateMaterialPages(ctx context.Context, arg UpdateMaterialPagesParams) error {
	_, err := q.db.ExecContext(ctx, updateMaterialPages,
		arg.PageCount,
		arg.BilledPages,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updateMaterialStatus = `-- name: UpdateMaterialStatus :exec
UPDATE materials SET status = ?, fail_reason = ? WHERE id = ? AND owner_user_id = ?
`

type UpdateMaterialStatusParams struct {
	Status      MaterialsStatus
	FailReason  sql.NullString
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) UpdateMaterialStatus(ctx context.Context, arg UpdateMaterialStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMaterialStatus,
		arg.Status,
		arg.FailReason,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const upsertMaterialPage = `-- name: UpsertMaterialPage :exec
INSERT INTO material_pages (material_id, page_no, owner_user_id, text, tables, low_confidence)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE text = VALUES(text), tables = VALUES(tables), low_confidence = VALUES(low_confidence)
`

type UpsertMaterialPageParams struct {
	MaterialID    uint64
	PageNo        uint32
	OwnerUserID   uint64
	Text          string
	Tables        dbtypes.NullJSON
	LowConfidence dbtypes.NullJSON
}

func (q *Queries) UpsertMaterialPage(ctx context.Context, arg UpsertMaterialPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMaterialPage,
		arg.MaterialID,
		arg.PageNo,
		arg.OwnerUserID,
		arg.Text,
		arg.Tables,
		arg.LowConfidence,
	)
	return err
}
