// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const countUnreadMessages = `-- name: CountUnreadMessages :one
SELECT COUNT(*) FROM messages WHERE owner_user_id = ? AND read_at IS NULL AND created_at >= ?
`

type CountUnreadMessagesParams struct {
	OwnerUserID uint64
	CreatedAt   time.Time
}

func (q *Queries) CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadMessages, arg.OwnerUserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldMessages = `-- name: DeleteOldMessages :execrows
DELETE FROM messages WHERE created_at < ? LIMIT 5000
`

// 系统清理任务：保留 30 天。
func (q *Queries) DeleteOldMessages(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldMessages, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveGrant = `-- name: GetActiveGrant :one
SELECT id, user_id, source, source_id, scope, granted_at, expires_at, revoked_at FROM content_access_grants WHERE id = ? AND revoked_at IS NULL AND expires_at > ?
`

type GetActiveGrantParams struct {
	ID        uint64
	ExpiresAt time.Time
}

// 后台授权查看（PRD 10.1）：只有有效期内、未撤销的授权能读。
func (q *Queries) GetActiveGrant(ctx context.Context, arg GetActiveGrantParams) (ContentAccessGrant, error) {
	row := q.db.QueryRowContext(ctx, getActiveGrant, arg.ID, arg.ExpiresAt)
	var i ContentAccessGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.SourceID,
		&i.Scope,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getFeedbackOwner = `-- name: GetFeedbackOwner :one
SELECT owner_user_id FROM feedbacks WHERE id = ?
`

func (q *Queries) GetFeedbackOwner(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getFeedbackOwner, id)
	var owner_user_id uint64
	err := row.Scan(&owner_user_id)
	return owner_user_id, err
}

const getMessageOwned = `-- name: GetMessageOwned :one
SELECT id FROM messages WHERE id = ? AND owner_user_id = ?
`

type GetMessageOwnedParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetMessageOwned(ctx context.Context, arg GetMessageOwnedParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getMessageOwned, arg.ID, arg.OwnerUserID)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const insertContentAccessLog = `-- name: InsertContentAccessLog :exec
INSERT INTO content_access_logs (grant_id, admin_id, user_id, target_type, target_id, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertContentAccessLogParams struct {
	GrantID    uint64
	AdminID    uint64
	UserID     uint64
	TargetType string
	TargetID   uint64
	CreatedAt  time.Time
}

func (q *Queries) InsertContentAccessLog(ctx context.Context, arg InsertContentAccessLogParams) error {
	_, err := q.db.ExecContext(ctx, insertContentAccessLog,
		arg.GrantID,
		arg.AdminID,
		arg.UserID,
		arg.TargetType,
		arg.TargetID,
		arg.CreatedAt,
	)
	return err
}

const listDueAnnouncements = `-- name: ListDueAnnouncements :many
SELECT id, title, body, audience FROM announcements WHERE sent_at IS NULL AND (scheduled_at IS NULL OR scheduled_at <= ?) ORDER BY id LIMIT 20
`

type ListDueAnnouncementsRow struct {
	ID       uint64
	Title    string
	Body     string
	Audience json.RawMessage
}

func (q *Queries) ListDueAnnouncements(ctx context.Context, scheduledAt sql.NullTime) ([]ListDueAnnouncementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueAnnouncements, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueAnnouncementsRow{}
	for rows.Next() {
		var i ListDueAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Audience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many

SELECT id, mtype, title, body, link, read_at, created_at FROM messages
WHERE owner_user_id = ? AND created_at >= ? AND (? = 0 OR id < ?)
ORDER BY id DESC LIMIT ?
`

type ListMessagesParams struct {
	Owner    uint64
	Since    time.Time
	BeforeID uint64
	Limit    int32
}

type ListMessagesRow struct {
	ID        uint64
	Mtype     MessagesMtype
	Title     string
	Body      string
	Link      dbtypes.NullJSON
	ReadAt    sql.NullTime
	CreatedAt time.Time
}

// 消息中心（T27，PRD 2.3）：保留 30 天；用户查询都带归属条件。批量发送（公告、协议更新、复习到期）用 INSERT ... SELECT，
// dedupe_key 保证同一事件对同一用户只发一条，任务重复执行也不会重复发。
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages,
		arg.Owner,
		arg.Since,
		arg.BeforeID,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Mtype,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAgreements = `-- name: ListRecentAgreements :many
SELECT id, kind, version, title, change_summary FROM agreements WHERE published_at IS NOT NULL AND published_at <= ? AND published_at >= ?
`

type ListRecentAgreementsParams struct {
	PublishedAt   sql.NullTime
	PublishedAt_2 sql.NullTime
}

type ListRecentAgreementsRow struct {
	ID            uint64
	Kind          AgreementsKind
	Version       string
	Title         string
	ChangeSummary sql.NullString
}

// 30 天内发布的协议新版本：给还没同意的用户发「协议更新」（新注册的用户登录时已同意当前版本）。
func (q *Queries) ListRecentAgreements(ctx context.Context, arg ListRecentAgreementsParams) ([]ListRecentAgreementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAgreements, arg.PublishedAt, arg.PublishedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAgreementsRow{}
	for rows.Next() {
		var i ListRecentAgreementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Title,
			&i.ChangeSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllMessagesRead = `-- name: MarkAllMessagesRead :execrows
UPDATE messages SET read_at = ? WHERE owner_user_id = ? AND read_at IS NULL
`

type MarkAllMessagesReadParams struct {
	ReadAt      sql.NullTime
	OwnerUserID uint64
}

func (q *Queries) MarkAllMessagesRead(ctx context.Context, arg MarkAllMessagesReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllMessagesRead, arg.ReadAt, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAnnouncementSent = `-- name: MarkAnnouncementSent :exec
UPDATE announcements SET sent_at = ?, sent_count = ? WHERE id = ? AND sent_at IS NULL
`

type MarkAnnouncementSentParams struct {
	SentAt    sql.NullTime
	SentCount uint32
	ID        uint64
}

func (q *Queries) MarkAnnouncementSent(ctx context.Context, arg MarkAnnouncementSentParams) error {
	_, err := q.db.ExecContext(ctx, markAnnouncementSent, arg.SentAt, arg.SentCount, arg.ID)
	return err
}

const markMessageRead = `-- name: MarkMessageRead :execrows
UPDATE messages SET read_at = ? WHERE id = ? AND owner_user_id = ? AND read_at IS NULL
`

type MarkMessageReadParams struct {
	ReadAt      sql.NullTime
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageRead, arg.ReadAt, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const replyFeedback = `-- name: ReplyFeedback :execrows
UPDATE feedbacks SET reply = ?, replied_by = ?, replied_at = ?, status = 'replied' WHERE id = ?
`

type ReplyFeedbackParams struct {
	Reply     sql.NullString
	RepliedBy sql.NullInt64
	RepliedAt sql.NullTime
	ID        uint64
}

// 客服回复（7.7）：回复写回反馈并发到消息中心。
func (q *Queries) ReplyFeedback(ctx context.Context, arg ReplyFeedbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replyFeedback,
		arg.Reply,
		arg.RepliedBy,
		arg.RepliedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sendAgreementUpdate = `-- name: SendAgreementUpdate :execrows
INSERT IGNORE INTO messages (owner_user_id, mtype, title, body, link, dedupe_key)
SELECT u.id, 'agreement_update', ?, ?, ?, ? FROM users u
WHERE u.status = 'active'
  AND NOT EXISTS (SELECT 1 FROM agreement_acceptances a WHERE a.user_id = u.id AND a.agreement_id = ?)
`

type SendAgreementUpdateParams struct {
	Title       string
	Body        string
	Link        dbtypes.NullJSON
	DedupeKey   sql.NullString
	AgreementID uint64
}

func (q *Queries) SendAgreementUpdate(ctx context.Context, arg SendAgreementUpdateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sendAgreementUpdate,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.DedupeKey,
		arg.AgreementID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sendAnnouncementToAll = `-- name: SendAnnouncementToAll :execrows
INSERT IGNORE INTO messages (owner_user_id, mtype, title, body, dedupe_key)
SELECT u.id, 'announcement', ?, ?, ? FROM users u WHERE u.status = 'active'
`

type SendAnnouncementToAllParams struct {
	Title     string
	Body      string
	DedupeKey sql.NullString
}

func (q *Queries) SendAnnouncementToAll(ctx context.Context, arg SendAnnouncementToAllParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sendAnnouncementToAll, arg.Title, arg.Body, arg.DedupeKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sendAnnouncementToUsers = `-- name: SendAnnouncementToUsers :execrows
INSERT IGNORE INTO messages (owner_user_id, mtype, title, body, dedupe_key)
SELECT u.id, 'announcement', ?, ?, ? FROM users u
WHERE u.status = 'active' AND JSON_CONTAINS(?, CAST(u.id AS JSON))
`

type SendAnnouncementToUsersParams struct {
	Title     string
	Body      string
	DedupeKey sql.NullString
	UserIds   string
}

func (q *Queries) SendAnnouncementToUsers(ctx context.Context, arg SendAnnouncementToUsersParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sendAnnouncementToUsers,
		arg.Title,
		arg.Body,
		arg.DedupeKey,
		arg.UserIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sendReviewDue = `-- name: SendReviewDue :execrows
INSERT IGNORE INTO messages (owner_user_id, mtype, title, body, link, dedupe_key)
SELECT p.user_id, 'review_due', '今天有内容到期复习',
  CONCAT('到期知识点 ', (SELECT COUNT(*) FROM kp_mastery k WHERE k.owner_user_id = p.user_id AND k.next_review_on <= ?),
         ' 个、到期错题 ', (SELECT COUNT(*) FROM wrong_book w WHERE w.owner_user_id = p.user_id AND w.status = 'active' AND w.next_review_on <= ?),
         ' 道，已排进今日训练'),
  ?, ?
FROM study_profiles p JOIN users u ON u.id = p.user_id
WHERE u.status = 'active' AND p.notify_review_due = 1
  AND (EXISTS (SELECT 1 FROM kp_mastery k WHERE k.owner_user_id = p.user_id AND k.next_review_on <= ?)
    OR EXISTS (SELECT 1 FROM wrong_book w WHERE w.owner_user_id = p.user_id AND w.status = 'active' AND w.next_review_on <= ?))
`

type SendReviewDueParams struct {
	Day       sql.NullTime
	Link      dbtypes.NullJSON
	DedupeKey sql.NullString
}

// 复习到期（北京时间当天）：打开了「复习到期提醒」、有到期知识点或错题的用户，每天一条。
func (q *Queries) SendReviewDue(ctx context.Context, arg SendReviewDueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sendReviewDue,
		arg.Day,
		arg.Day,
		arg.Link,
		arg.DedupeKey,
		arg.Day,
		arg.Day,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
