// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mine.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const clearExportObject = `-- name: ClearExportObject :exec
UPDATE export_jobs SET object_key = NULL WHERE id = ? AND owner_user_id = ?
`

type ClearExportObjectParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) ClearExportObject(ctx context.Context, arg ClearExportObjectParams) error {
	_, err := q.db.ExecContext(ctx, clearExportObject, arg.ID, arg.OwnerUserID)
	return err
}

const exportKnowledgePoints = `-- name: ExportKnowledgePoints :many
SELECT k.id, k.parent_id, k.level, k.name, k.original_text FROM knowledge_points k
WHERE k.bank_id = ? AND k.owner_user_id = ?
ORDER BY k.sort_order, k.id
`

type ExportKnowledgePointsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ExportKnowledgePointsRow struct {
	ID           uint64
	ParentID     sql.NullInt64
	Level        KnowledgePointsLevel
	Name         string
	OriginalText sql.NullString
}

func (q *Queries) ExportKnowledgePoints(ctx context.Context, arg ExportKnowledgePointsParams) ([]ExportKnowledgePointsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportKnowledgePoints, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportKnowledgePointsRow{}
	for rows.Next() {
		var i ExportKnowledgePointsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Name,
			&i.OriginalText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportQuestions = `-- name: ExportQuestions :many
SELECT q.id, q.qtype, q.stem, q.options, q.answer, q.score, q.source, q.exam_year
FROM questions q
WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.status = 'active'
ORDER BY FIELD(q.qtype, 'single_choice', 'multi_choice', 'true_false', 'fill_blank', 'term', 'short_answer', 'discussion', 'essay', 'calculation', 'other'),
  q.exam_year DESC, q.id
`

type ExportQuestionsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ExportQuestionsRow struct {
	ID       uint64
	Qtype    QuestionsQtype
	Stem     string
	Options  dbtypes.NullJSON
	Answer   sql.NullString
	Score    sql.NullString
	Source   QuestionsSource
	ExamYear sql.NullInt16
}

// 导出的题目与参考答案：按题型、年份排；AI 变式题单独标。
func (q *Queries) ExportQuestions(ctx context.Context, arg ExportQuestionsParams) ([]ExportQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportQuestions, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportQuestionsRow{}
	for rows.Next() {
		var i ExportQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Qtype,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Score,
			&i.Source,
			&i.ExamYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportRubricPoints = `-- name: ExportRubricPoints :many
SELECT r.question_id, r.kp_id, r.seq, r.content, r.score FROM rubric_points r
JOIN questions q ON q.id = r.question_id
WHERE q.bank_id = ? AND r.owner_user_id = ?
ORDER BY r.question_id, r.seq
`

type ExportRubricPointsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ExportRubricPointsRow struct {
	QuestionID sql.NullInt64
	KpID       sql.NullInt64
	Seq        uint16
	Content    string
	Score      sql.NullString
}

func (q *Queries) ExportRubricPoints(ctx context.Context, arg ExportRubricPointsParams) ([]ExportRubricPointsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportRubricPoints, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportRubricPointsRow{}
	for rows.Next() {
		var i ExportRubricPointsRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.KpID,
			&i.Seq,
			&i.Content,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportWrongBook = `-- name: ExportWrongBook :many
SELECT w.question_id, w.last_loss_type, w.wrong_count, q.qtype, q.stem, q.answer,
  (SELECT a.answer_text FROM attempts a WHERE a.question_id = w.question_id AND a.owner_user_id = w.owner_user_id ORDER BY a.answered_at DESC, a.id DESC LIMIT 1) AS my_answer
FROM wrong_book w JOIN questions q ON q.id = w.question_id
WHERE w.owner_user_id = ? AND q.bank_id = ? AND w.status = 'active'
ORDER BY w.added_at DESC
`

type ExportWrongBookParams struct {
	OwnerUserID uint64
	BankID      uint64
}

type ExportWrongBookRow struct {
	QuestionID   uint64
	LastLossType NullWrongBookLastLossType
	WrongCount   uint32
	Qtype        QuestionsQtype
	Stem         string
	Answer       sql.NullString
	MyAnswer     sql.NullString
}

// 错题和我的作答：最近一次作答原文与失分原因。
func (q *Queries) ExportWrongBook(ctx context.Context, arg ExportWrongBookParams) ([]ExportWrongBookRow, error) {
	rows, err := q.db.QueryContext(ctx, exportWrongBook, arg.OwnerUserID, arg.BankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportWrongBookRow{}
	for rows.Next() {
		var i ExportWrongBookRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.LastLossType,
			&i.WrongCount,
			&i.Qtype,
			&i.Stem,
			&i.Answer,
			&i.MyAnswer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failExportJob = `-- name: FailExportJob :exec
UPDATE export_jobs SET status = 'failed', finished_at = ? WHERE id = ? AND owner_user_id = ?
`

type FailExportJobParams struct {
	FinishedAt  sql.NullTime
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) FailExportJob(ctx context.Context, arg FailExportJobParams) error {
	_, err := q.db.ExecContext(ctx, failExportJob, arg.FinishedAt, arg.ID, arg.OwnerUserID)
	return err
}

const finishExportJob = `-- name: FinishExportJob :exec
UPDATE export_jobs SET status = 'done', object_key = ?, page_estimate = ?, expires_at = ?, finished_at = ? WHERE id = ? AND owner_user_id = ?
`

type FinishExportJobParams struct {
	ObjectKey    sql.NullString
	PageEstimate sql.NullInt32
	ExpiresAt    sql.NullTime
	FinishedAt   sql.NullTime
	ID           uint64
	OwnerUserID  uint64
}

func (q *Queries) FinishExportJob(ctx context.Context, arg FinishExportJobParams) error {
	_, err := q.db.ExecContext(ctx, finishExportJob,
		arg.ObjectKey,
		arg.PageEstimate,
		arg.ExpiresAt,
		arg.FinishedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const getExportJob = `-- name: GetExportJob :one
SELECT id, owner_user_id, subject_id, options, format, status, object_key, page_estimate, expires_at, created_at, finished_at FROM export_jobs WHERE id = ? AND owner_user_id = ?
`

type GetExportJobParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetExportJob(ctx context.Context, arg GetExportJobParams) (ExportJob, error) {
	row := q.db.QueryRowContext(ctx, getExportJob, arg.ID, arg.OwnerUserID)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.Options,
		&i.Format,
		&i.Status,
		&i.ObjectKey,
		&i.PageEstimate,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRedeemCodeForUpdate = `-- name: GetRedeemCodeForUpdate :one
SELECT c.id, c.status, c.batch_id, b.tier, b.days, b.code_expires_at, b.status AS batch_status
FROM redeem_codes c JOIN redeem_batches b ON b.id = c.batch_id
WHERE c.code_hash = ? FOR UPDATE
`

type GetRedeemCodeForUpdateRow struct {
	ID            uint64
	Status        RedeemCodesStatus
	BatchID       uint64
	Tier          RedeemBatchesTier
	Days          sql.NullInt16
	CodeExpiresAt time.Time
	BatchStatus   RedeemBatchesStatus
}

func (q *Queries) GetRedeemCodeForUpdate(ctx context.Context, codeHash string) (GetRedeemCodeForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getRedeemCodeForUpdate, codeHash)
	var i GetRedeemCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.BatchID,
		&i.Tier,
		&i.Days,
		&i.CodeExpiresAt,
		&i.BatchStatus,
	)
	return i, err
}

const getSurveyResponse = `-- name: GetSurveyResponse :one
SELECT owner_user_id, exam_year, scores, retest_result, admission, share_consent, membership_id, created_at, updated_at FROM survey_responses WHERE owner_user_id = ?
`

func (q *Queries) GetSurveyResponse(ctx context.Context, ownerUserID uint64) (SurveyResponse, error) {
	row := q.db.QueryRowContext(ctx, getSurveyResponse, ownerUserID)
	var i SurveyResponse
	err := row.Scan(
		&i.OwnerUserID,
		&i.ExamYear,
		&i.Scores,
		&i.RetestResult,
		&i.Admission,
		&i.ShareConsent,
		&i.MembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertExportJob = `-- name: InsertExportJob :execlastid
INSERT INTO export_jobs (owner_user_id, subject_id, options, format, page_estimate, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertExportJobParams struct {
	OwnerUserID  uint64
	SubjectID    uint64
	Options      json.RawMessage
	Format       ExportJobsFormat
	PageEstimate sql.NullInt32
	CreatedAt    time.Time
}

func (q *Queries) InsertExportJob(ctx context.Context, arg InsertExportJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertExportJob,
		arg.OwnerUserID,
		arg.SubjectID,
		arg.Options,
		arg.Format,
		arg.PageEstimate,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertFeedback = `-- name: InsertFeedback :execlastid
INSERT INTO feedbacks (owner_user_id, ftype, content, screenshot_keys, allow_access, related_material_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertFeedbackParams struct {
	OwnerUserID       uint64
	Ftype             FeedbacksFtype
	Content           string
	ScreenshotKeys    dbtypes.NullJSON
	AllowAccess       bool
	RelatedMaterialID sql.NullInt64
	CreatedAt         time.Time
}

func (q *Queries) InsertFeedback(ctx context.Context, arg InsertFeedbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertFeedback,
		arg.OwnerUserID,
		arg.Ftype,
		arg.Content,
		arg.ScreenshotKeys,
		arg.AllowAccess,
		arg.RelatedMaterialID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertFeedbackGrant = `-- name: InsertFeedbackGrant :exec
INSERT INTO content_access_grants (user_id, source, source_id, scope, granted_at, expires_at) VALUES (?, 'feedback', ?, ?, ?, ?)
`

type InsertFeedbackGrantParams struct {
	UserID    uint64
	SourceID  uint64
	Scope     json.RawMessage
	GrantedAt time.Time
	ExpiresAt time.Time
}

// 勾选「允许客服查看相关资料」：72 小时内有效，每次查看都通知用户（PRD 6.13、10.1）。
func (q *Queries) InsertFeedbackGrant(ctx context.Context, arg InsertFeedbackGrantParams) error {
	_, err := q.db.ExecContext(ctx, insertFeedbackGrant,
		arg.UserID,
		arg.SourceID,
		arg.Scope,
		arg.GrantedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertMembership = `-- name: InsertMembership :execlastid

INSERT INTO memberships (owner_user_id, tier, source, source_ref, starts_at, ends_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertMembershipParams struct {
	OwnerUserID uint64
	Tier        MembershipsTier
	Source      MembershipsSource
	SourceRef   sql.NullInt64
	StartsAt    time.Time
	EndsAt      time.Time
}

// 我的（T24）：会员时段、兑换码、考后回访、意见反馈、导出题库。每条用户内容查询都带归属条件。
func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertMembership,
		arg.OwnerUserID,
		arg.Tier,
		arg.Source,
		arg.SourceRef,
		arg.StartsAt,
		arg.EndsAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertSurveyResponse = `-- name: InsertSurveyResponse :exec
INSERT INTO survey_responses (owner_user_id, exam_year, scores, retest_result, admission, share_consent, membership_id) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSurveyResponseParams struct {
	OwnerUserID  uint64
	ExamYear     uint16
	Scores       json.RawMessage
	RetestResult SurveyResponsesRetestResult
	Admission    NullSurveyResponsesAdmission
	ShareConsent bool
	MembershipID sql.NullInt64
}

func (q *Queries) InsertSurveyResponse(ctx context.Context, arg InsertSurveyResponseParams) error {
	_, err := q.db.ExecContext(ctx, insertSurveyResponse,
		arg.OwnerUserID,
		arg.ExamYear,
		arg.Scores,
		arg.RetestResult,
		arg.Admission,
		arg.ShareConsent,
		arg.MembershipID,
	)
	return err
}

const listExamEndsFrom = `-- name: ListExamEndsFrom :many
SELECT exam_year, label, first_exam_start, first_exam_end, subject_exam_date, updated_at FROM exam_dates WHERE first_exam_end >= ? ORDER BY exam_year LIMIT 2
`

// 冲刺卡至当年初试结束、考季卡至次年初试结束（PRD 13.2）。
func (q *Queries) ListExamEndsFrom(ctx context.Context, firstExamEnd time.Time) ([]ExamDate, error) {
	rows, err := q.db.QueryContext(ctx, listExamEndsFrom, firstExamEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamDate{}
	for rows.Next() {
		var i ExamDate
		if err := rows.Scan(
			&i.ExamYear,
			&i.Label,
			&i.FirstExamStart,
			&i.FirstExamEnd,
			&i.SubjectExamDate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredExports = `-- name: ListExpiredExports :many
SELECT id, owner_user_id, object_key FROM export_jobs WHERE status = 'done' AND object_key IS NOT NULL AND expires_at < ? LIMIT 200
`

type ListExpiredExportsRow struct {
	ID          uint64
	OwnerUserID uint64
	ObjectKey   sql.NullString
}

// 24 小时后删除 OSS 对象（定时任务）。
func (q *Queries) ListExpiredExports(ctx context.Context, expiresAt sql.NullTime) ([]ListExpiredExportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredExports, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredExportsRow{}
	for rows.Next() {
		var i ListExpiredExportsRow
		if err := rows.Scan(&i.ID, &i.OwnerUserID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbacks = `-- name: ListFeedbacks :many
SELECT id, ftype, content, screenshot_keys, allow_access, status, reply, replied_at, created_at FROM feedbacks
WHERE owner_user_id = ? ORDER BY id DESC LIMIT 50
`

type ListFeedbacksRow struct {
	ID             uint64
	Ftype          FeedbacksFtype
	Content        string
	ScreenshotKeys dbtypes.NullJSON
	AllowAccess    bool
	Status         FeedbacksStatus
	Reply          sql.NullString
	RepliedAt      sql.NullTime
	CreatedAt      time.Time
}

func (q *Queries) ListFeedbacks(ctx context.Context, ownerUserID uint64) ([]ListFeedbacksRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedbacks, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbacksRow{}
	for rows.Next() {
		var i ListFeedbacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Ftype,
			&i.Content,
			&i.ScreenshotKeys,
			&i.AllowAccess,
			&i.Status,
			&i.Reply,
			&i.RepliedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const meOverview = `-- name: MeOverview :one
SELECT
  (SELECT COUNT(*) FROM materials m WHERE m.owner_user_id = ?) AS materials,
  (SELECT COUNT(*) FROM questions q WHERE q.owner_user_id = ? AND q.status = 'active') AS questions,
  (SELECT COUNT(*) FROM wrong_book w WHERE w.owner_user_id = ? AND w.status = 'active') AS wrong,
  (SELECT COUNT(*) FROM essays e WHERE e.owner_user_id = ? AND e.status = 'graded') AS essays
`

type MeOverviewParams struct {
	UserID uint64
	Owner  sql.NullInt64
}

type MeOverviewRow struct {
	Materials int64
	Questions int64
	Wrong     int64
	Essays    int64
}

// 6.1 我的：资料份数、题数、错题本待重做、作文篇数。
func (q *Queries) MeOverview(ctx context.Context, arg MeOverviewParams) (MeOverviewRow, error) {
	row := q.db.QueryRowContext(ctx, meOverview,
		arg.UserID,
		arg.Owner,
		arg.UserID,
		arg.UserID,
	)
	var i MeOverviewRow
	err := row.Scan(
		&i.Materials,
		&i.Questions,
		&i.Wrong,
		&i.Essays,
	)
	return i, err
}

const ownsMaterial = `-- name: OwnsMaterial :one
SELECT EXISTS (SELECT 1 FROM materials WHERE id = ? AND owner_user_id = ?)
`

type OwnsMaterialParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) OwnsMaterial(ctx context.Context, arg OwnsMaterialParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, ownsMaterial, arg.ID, arg.OwnerUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setExportJobRunning = `-- name: SetExportJobRunning :exec
UPDATE export_jobs SET status = 'running' WHERE id = ? AND owner_user_id = ? AND status IN ('queued', 'running')
`

type SetExportJobRunningParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) SetExportJobRunning(ctx context.Context, arg SetExportJobRunningParams) error {
	_, err := q.db.ExecContext(ctx, setExportJobRunning, arg.ID, arg.OwnerUserID)
	return err
}

const updateSurveyResponse = `-- name: UpdateSurveyResponse :exec
UPDATE survey_responses SET retest_result = ?, admission = ?, share_consent = ? WHERE owner_user_id = ?
`

type UpdateSurveyResponseParams struct {
	RetestResult SurveyResponsesRetestResult
	Admission    NullSurveyResponsesAdmission
	ShareConsent bool
	OwnerUserID  uint64
}

// 录取结果可以稍后补（6.14）；不重复送会员。
func (q *Queries) UpdateSurveyResponse(ctx context.Context, arg UpdateSurveyResponseParams) error {
	_, err := q.db.ExecContext(ctx, updateSurveyResponse,
		arg.RetestResult,
		arg.Admission,
		arg.ShareConsent,
		arg.OwnerUserID,
	)
	return err
}

const useRedeemCode = `-- name: UseRedeemCode :execrows
UPDATE redeem_codes SET status = 'used', used_by = ?, used_at = ?, membership_id = ? WHERE id = ? AND status = 'unused'
`

type UseRedeemCodeParams struct {
	UsedBy       sql.NullInt64
	UsedAt       sql.NullTime
	MembershipID sql.NullInt64
	ID           uint64
}

func (q *Queries) UseRedeemCode(ctx context.Context, arg UseRedeemCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useRedeemCode,
		arg.UsedBy,
		arg.UsedAt,
		arg.MembershipID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
