// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor.sql

package dbq

import (
	"context"
	"time"
)

const aICallHealth = `-- name: AICallHealth :one
SELECT COUNT(*) AS calls, CAST(COALESCE(SUM(success = 0), 0) AS SIGNED) AS failed FROM ai_calls WHERE created_at >= ?
`

type AICallHealthRow struct {
	Calls  int64
	Failed int64
}

// 告警：一段时间内的模型调用次数与失败次数（ai_calls 只有计数，不存输入输出）。
func (q *Queries) AICallHealth(ctx context.Context, createdAt time.Time) (AICallHealthRow, error) {
	row := q.db.QueryRowContext(ctx, aICallHealth, createdAt)
	var i AICallHealthRow
	err := row.Scan(&i.Calls, &i.Failed)
	return i, err
}
