// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: norm.sql

package dbq

import (
	"context"
	"database/sql"

	"peetraining-server/internal/dbtypes"
)

const anyQuestionOfQType = `-- name: AnyQuestionOfQType :one
SELECT q.id FROM questions q
WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.qtype = ? AND q.status = 'active'
ORDER BY (SELECT COUNT(*) FROM attempts a WHERE a.question_id = q.id), q.id
LIMIT 1
`

type AnyQuestionOfQTypeParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
	Qtype       QuestionsQtype
}

// 「按结构写一道」用的题：同题型里最近没做过的。
func (q *Queries) AnyQuestionOfQType(ctx context.Context, arg AnyQuestionOfQTypeParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, anyQuestionOfQType, arg.BankID, arg.OwnerUserID, arg.Qtype)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const insertNormGrading = `-- name: InsertNormGrading :execlastid
INSERT INTO gradings (owner_user_id, attempt_id, kind, trigger_reason, status, point_results, suggestions, model, prompt_version, quota_charged, idempotency_key, finished_at)
VALUES (?, ?, 'norm', 'submit', 'done', ?, ?, ?, ?, 1, ?, ?)
`

type InsertNormGradingParams struct {
	OwnerUserID    uint64
	AttemptID      uint64
	PointResults   dbtypes.NullJSON
	Suggestions    dbtypes.NullJSON
	Model          sql.NullString
	PromptVersion  sql.NullString
	IdempotencyKey sql.NullString
	FinishedAt     sql.NullTime
}

func (q *Queries) InsertNormGrading(ctx context.Context, arg InsertNormGradingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertNormGrading,
		arg.OwnerUserID,
		arg.AttemptID,
		arg.PointResults,
		arg.Suggestions,
		arg.Model,
		arg.PromptVersion,
		arg.IdempotencyKey,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const latestGradingOfQType = `-- name: LatestGradingOfQType :one
SELECT g.id, g.point_results, g.score, g.full_score, a.answer_text, q.id AS question_id, q.stem
FROM gradings g
JOIN attempts a ON a.id = g.attempt_id
JOIN questions q ON q.id = a.question_id
WHERE g.owner_user_id = ? AND g.kind = 'subjective' AND g.status = 'done' AND q.bank_id = ? AND q.qtype = ?
ORDER BY g.id DESC LIMIT 1
`

type LatestGradingOfQTypeParams struct {
	OwnerUserID uint64
	BankID      uint64
	Qtype       QuestionsQtype
}

type LatestGradingOfQTypeRow struct {
	ID           uint64
	PointResults dbtypes.NullJSON
	Score        sql.NullString
	FullScore    sql.NullString
	AnswerText   sql.NullString
	QuestionID   uint64
	Stem         string
}

// 你上次的写法：最近一次批改完的同题型作答。
func (q *Queries) LatestGradingOfQType(ctx context.Context, arg LatestGradingOfQTypeParams) (LatestGradingOfQTypeRow, error) {
	row := q.db.QueryRowContext(ctx, latestGradingOfQType, arg.OwnerUserID, arg.BankID, arg.Qtype)
	var i LatestGradingOfQTypeRow
	err := row.Scan(
		&i.ID,
		&i.PointResults,
		&i.Score,
		&i.FullScore,
		&i.AnswerText,
		&i.QuestionID,
		&i.Stem,
	)
	return i, err
}

const normExampleQuestion = `-- name: NormExampleQuestion :one
SELECT q.id, q.stem, q.answer, q.source_material_id, q.source_page
FROM questions q
WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.qtype = ? AND q.status = 'active'
  AND EXISTS (SELECT 1 FROM rubric_points r WHERE r.question_id = q.id)
ORDER BY (SELECT COUNT(*) FROM rubric_points r WHERE r.question_id = q.id AND r.origin = 'user_confirmed') DESC,
  q.source_material_id IS NULL, q.id
LIMIT 1
`

type NormExampleQuestionParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
	Qtype       QuestionsQtype
}

type NormExampleQuestionRow struct {
	ID               uint64
	Stem             string
	Answer           sql.NullString
	SourceMaterialID sql.NullInt64
	SourcePage       sql.NullInt32
}

// 高分写法：同题型里有采分点的题，用户确认过的采分点、有资料出处的优先。
func (q *Queries) NormExampleQuestion(ctx context.Context, arg NormExampleQuestionParams) (NormExampleQuestionRow, error) {
	row := q.db.QueryRowContext(ctx, normExampleQuestion, arg.BankID, arg.OwnerUserID, arg.Qtype)
	var i NormExampleQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Stem,
		&i.Answer,
		&i.SourceMaterialID,
		&i.SourcePage,
	)
	return i, err
}

const setAttemptPhotos = `-- name: SetAttemptPhotos :exec

UPDATE attempts SET photo_keys = ? WHERE id = ? AND owner_user_id = ?
`

type SetAttemptPhotosParams struct {
	PhotoKeys   dbtypes.NullJSON
	ID          uint64
	OwnerUserID uint64
}

// 拍手写稿与答题规范（T19）。每条查询都带归属条件。
func (q *Queries) SetAttemptPhotos(ctx context.Context, arg SetAttemptPhotosParams) error {
	_, err := q.db.ExecContext(ctx, setAttemptPhotos, arg.PhotoKeys, arg.ID, arg.OwnerUserID)
	return err
}
