// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: official.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const countEditorReviews = `-- name: CountEditorReviews :one
SELECT COUNT(*) FROM review_tasks t JOIN official_drafts d ON d.id = t.draft_id WHERE d.editor_id = ?
`

// 编辑已提交过几次（新编辑前 3 次全量审核）。
func (q *Queries) CountEditorReviews(ctx context.Context, editorID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEditorReviews, editorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideReviewTask = `-- name: DecideReviewTask :execrows
UPDATE review_tasks SET reviewer_id = ?, decision = ?, reason = ?, edited_payload = ?, decided_at = ? WHERE id = ? AND decision = 'pending'
`

type DecideReviewTaskParams struct {
	ReviewerID    sql.NullInt64
	Decision      ReviewTasksDecision
	Reason        sql.NullString
	EditedPayload dbtypes.NullJSON
	DecidedAt     sql.NullTime
	ID            uint64
}

func (q *Queries) DecideReviewTask(ctx context.Context, arg DecideReviewTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideReviewTask,
		arg.ReviewerID,
		arg.Decision,
		arg.Reason,
		arg.EditedPayload,
		arg.DecidedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDemandMark = `-- name: DeleteDemandMark :exec
DELETE FROM official_demand_marks WHERE subject_code = ?
`

func (q *Queries) DeleteDemandMark(ctx context.Context, subjectCode string) error {
	_, err := q.db.ExecContext(ctx, deleteDemandMark, subjectCode)
	return err
}

const deleteOfficialDraft = `-- name: DeleteOfficialDraft :execrows
DELETE FROM official_drafts WHERE id = ? AND editor_id = ? AND status IN ('draft', 'rejected')
`

type DeleteOfficialDraftParams struct {
	ID       uint64
	EditorID uint64
}

func (q *Queries) DeleteOfficialDraft(ctx context.Context, arg DeleteOfficialDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOfficialDraft, arg.ID, arg.EditorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOfficialKP = `-- name: DeleteOfficialKP :exec
DELETE FROM knowledge_points WHERE id = ? AND bank_id = ? AND owner_user_id IS NULL
`

type DeleteOfficialKPParams struct {
	ID     uint64
	BankID uint64
}

func (q *Queries) DeleteOfficialKP(ctx context.Context, arg DeleteOfficialKPParams) error {
	_, err := q.db.ExecContext(ctx, deleteOfficialKP, arg.ID, arg.BankID)
	return err
}

const deleteOfficialKPRubric = `-- name: DeleteOfficialKPRubric :exec
DELETE FROM rubric_points WHERE kp_id = ? AND owner_user_id IS NULL
`

func (q *Queries) DeleteOfficialKPRubric(ctx context.Context, kpID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteOfficialKPRubric, kpID)
	return err
}

const deleteOfficialQuestionKPs = `-- name: DeleteOfficialQuestionKPs :exec
DELETE FROM question_kps WHERE question_id = ? AND owner_user_id IS NULL
`

func (q *Queries) DeleteOfficialQuestionKPs(ctx context.Context, questionID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteOfficialQuestionKPs, questionID)
	return err
}

const deleteOfficialQuestionRubric = `-- name: DeleteOfficialQuestionRubric :exec
DELETE FROM rubric_points WHERE question_id = ? AND owner_user_id IS NULL
`

func (q *Queries) DeleteOfficialQuestionRubric(ctx context.Context, questionID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteOfficialQuestionRubric, questionID)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM bank_subscriptions WHERE owner_user_id = ? AND bank_id = ?
`

type DeleteSubscriptionParams struct {
	OwnerUserID uint64
	BankID      uint64
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubscription, arg.OwnerUserID, arg.BankID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserKP = `-- name: DeleteUserKP :exec
DELETE FROM knowledge_points WHERE id = ? AND owner_user_id = ?
`

type DeleteUserKPParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteUserKP(ctx context.Context, arg DeleteUserKPParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserKP, arg.ID, arg.OwnerUserID)
	return err
}

const deleteUserKPRubric = `-- name: DeleteUserKPRubric :exec
DELETE FROM rubric_points WHERE kp_id = ? AND owner_user_id = ?
`

type DeleteUserKPRubricParams struct {
	KpID        sql.NullInt64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteUserKPRubric(ctx context.Context, arg DeleteUserKPRubricParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserKPRubric, arg.KpID, arg.OwnerUserID)
	return err
}

const deleteUserQuestion = `-- name: DeleteUserQuestion :exec
DELETE FROM questions WHERE id = ? AND owner_user_id = ?
`

type DeleteUserQuestionParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteUserQuestion(ctx context.Context, arg DeleteUserQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserQuestion, arg.ID, arg.OwnerUserID)
	return err
}

const deleteUserQuestionKPs = `-- name: DeleteUserQuestionKPs :exec
DELETE FROM question_kps WHERE question_id = ? AND owner_user_id = ?
`

type DeleteUserQuestionKPsParams struct {
	QuestionID  uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteUserQuestionKPs(ctx context.Context, arg DeleteUserQuestionKPsParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserQuestionKPs, arg.QuestionID, arg.OwnerUserID)
	return err
}

const deleteUserQuestionRubric = `-- name: DeleteUserQuestionRubric :exec
DELETE FROM rubric_points WHERE question_id = ? AND owner_user_id = ?
`

type DeleteUserQuestionRubricParams struct {
	QuestionID  sql.NullInt64
	OwnerUserID sql.NullInt64
}

func (q *Queries) DeleteUserQuestionRubric(ctx context.Context, arg DeleteUserQuestionRubricParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserQuestionRubric, arg.QuestionID, arg.OwnerUserID)
	return err
}

const getOfficialDraft = `-- name: GetOfficialDraft :one
SELECT id, project_id, editor_id, entity_type, entity_id, change_type, payload, status, created_at, updated_at, submitted_at, reject_reason FROM official_drafts WHERE id = ?
`

func (q *Queries) GetOfficialDraft(ctx context.Context, id uint64) (OfficialDraft, error) {
	row := q.db.QueryRowContext(ctx, getOfficialDraft, id)
	var i OfficialDraft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EditorID,
		&i.EntityType,
		&i.EntityID,
		&i.ChangeType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.RejectReason,
	)
	return i, err
}

const getOfficialProject = `-- name: GetOfficialProject :one
SELECT id, school, major, subject_code, subject_name, bank_id, stage, editor_ids, authorized_materials, created_by, created_at, updated_at FROM official_projects WHERE id = ?
`

func (q *Queries) GetOfficialProject(ctx context.Context, id uint64) (OfficialProject, error) {
	row := q.db.QueryRowContext(ctx, getOfficialProject, id)
	var i OfficialProject
	err := row.Scan(
		&i.ID,
		&i.School,
		&i.Major,
		&i.SubjectCode,
		&i.SubjectName,
		&i.BankID,
		&i.Stage,
		&i.EditorIds,
		&i.AuthorizedMaterials,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfficialProjectByBank = `-- name: GetOfficialProjectByBank :one
SELECT id, school, major, subject_code, subject_name, bank_id, stage, editor_ids, authorized_materials, created_by, created_at, updated_at FROM official_projects WHERE bank_id = ?
`

func (q *Queries) GetOfficialProjectByBank(ctx context.Context, bankID sql.NullInt64) (OfficialProject, error) {
	row := q.db.QueryRowContext(ctx, getOfficialProjectByBank, bankID)
	var i OfficialProject
	err := row.Scan(
		&i.ID,
		&i.School,
		&i.Major,
		&i.SubjectCode,
		&i.SubjectName,
		&i.BankID,
		&i.Stage,
		&i.EditorIds,
		&i.AuthorizedMaterials,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfficialVersion = `-- name: GetOfficialVersion :one
SELECT id, project_id, version, changelog, published_by, published_at, rolled_back_at, snapshot FROM official_versions WHERE id = ? AND project_id = ?
`

type GetOfficialVersionParams struct {
	ID        uint64
	ProjectID uint64
}

func (q *Queries) GetOfficialVersion(ctx context.Context, arg GetOfficialVersionParams) (OfficialVersion, error) {
	row := q.db.QueryRowContext(ctx, getOfficialVersion, arg.ID, arg.ProjectID)
	var i OfficialVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Changelog,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.RolledBackAt,
		&i.Snapshot,
	)
	return i, err
}

const getReviewTask = `-- name: GetReviewTask :one
SELECT t.id, t.draft_id, t.reviewer_id, t.mode, t.decision, t.reason, t.created_at, t.decided_at, t.edited_payload, d.project_id, d.editor_id, d.entity_type, d.entity_id, d.change_type, d.payload, d.status AS draft_status
FROM review_tasks t JOIN official_drafts d ON d.id = t.draft_id WHERE t.id = ?
`

type GetReviewTaskRow struct {
	ID            uint64
	DraftID       uint64
	ReviewerID    sql.NullInt64
	Mode          ReviewTasksMode
	Decision      ReviewTasksDecision
	Reason        sql.NullString
	CreatedAt     time.Time
	DecidedAt     sql.NullTime
	EditedPayload dbtypes.NullJSON
	ProjectID     uint64
	EditorID      uint64
	EntityType    OfficialDraftsEntityType
	EntityID      sql.NullInt64
	ChangeType    OfficialDraftsChangeType
	Payload       json.RawMessage
	DraftStatus   OfficialDraftsStatus
}

func (q *Queries) GetReviewTask(ctx context.Context, id uint64) (GetReviewTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewTask, id)
	var i GetReviewTaskRow
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ReviewerID,
		&i.Mode,
		&i.Decision,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.EditedPayload,
		&i.ProjectID,
		&i.EditorID,
		&i.EntityType,
		&i.EntityID,
		&i.ChangeType,
		&i.Payload,
		&i.DraftStatus,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT owner_user_id, bank_id, subject_id, use_official_profile, added_at FROM bank_subscriptions WHERE owner_user_id = ? AND bank_id = ?
`

type GetSubscriptionParams struct {
	OwnerUserID uint64
	BankID      uint64
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (BankSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, arg.OwnerUserID, arg.BankID)
	var i BankSubscription
	err := row.Scan(
		&i.OwnerUserID,
		&i.BankID,
		&i.SubjectID,
		&i.UseOfficialProfile,
		&i.AddedAt,
	)
	return i, err
}

const insertOfficialBank = `-- name: InsertOfficialBank :execlastid


INSERT INTO banks (source, owner_user_id, subject_id, title, school_major_tag, subject_code) VALUES ('official', NULL, NULL, ?, ?, ?)
`

type InsertOfficialBankParams struct {
	Title          string
	SchoolMajorTag sql.NullString
	SubjectCode    sql.NullString
}

// 官方题库（T30）。官方内容在 source = official 的题库里，owner_user_id 为空；用户添加后复制到用户自己的题库。
// 用户侧的查询都带 owner_user_id 归属条件。
// ---------- 立项与进度（7.11） ----------
func (q *Queries) InsertOfficialBank(ctx context.Context, arg InsertOfficialBankParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOfficialBank, arg.Title, arg.SchoolMajorTag, arg.SubjectCode)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertOfficialDraft = `-- name: InsertOfficialDraft :execlastid

INSERT INTO official_drafts (project_id, editor_id, entity_type, entity_id, change_type, payload) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertOfficialDraftParams struct {
	ProjectID  uint64
	EditorID   uint64
	EntityType OfficialDraftsEntityType
	EntityID   sql.NullInt64
	ChangeType OfficialDraftsChangeType
	Payload    json.RawMessage
}

// ---------- 草稿与审核（7.12、7.13） ----------
func (q *Queries) InsertOfficialDraft(ctx context.Context, arg InsertOfficialDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOfficialDraft,
		arg.ProjectID,
		arg.EditorID,
		arg.EntityType,
		arg.EntityID,
		arg.ChangeType,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertOfficialKP = `-- name: InsertOfficialKP :execlastid
INSERT INTO knowledge_points (owner_user_id, bank_id, parent_id, level, name, original_text, origin, sort_order) VALUES (NULL, ?, ?, ?, ?, ?, 'official', ?)
`

type InsertOfficialKPParams struct {
	BankID       uint64
	ParentID     sql.NullInt64
	Level        KnowledgePointsLevel
	Name         string
	OriginalText sql.NullString
	SortOrder    uint32
}

func (q *Queries) InsertOfficialKP(ctx context.Context, arg InsertOfficialKPParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOfficialKP,
		arg.BankID,
		arg.ParentID,
		arg.Level,
		arg.Name,
		arg.OriginalText,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertOfficialProject = `-- name: InsertOfficialProject :execlastid
INSERT INTO official_projects (school, major, subject_code, subject_name, bank_id, editor_ids, created_by) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertOfficialProjectParams struct {
	School      string
	Major       string
	SubjectCode string
	SubjectName string
	BankID      sql.NullInt64
	EditorIds   dbtypes.NullJSON
	CreatedBy   sql.NullInt64
}

func (q *Queries) InsertOfficialProject(ctx context.Context, arg InsertOfficialProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOfficialProject,
		arg.School,
		arg.Major,
		arg.SubjectCode,
		arg.SubjectName,
		arg.BankID,
		arg.EditorIds,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertOfficialQuestion = `-- name: InsertOfficialQuestion :execlastid
INSERT INTO questions (owner_user_id, bank_id, qtype, stem, options, answer, answer_origin, analysis, score, source, exam_year, content_hash)
VALUES (NULL, ?, ?, ?, ?, ?, 'official', ?, ?, 'official', ?, ?)
`

type InsertOfficialQuestionParams struct {
	BankID      uint64
	Qtype       QuestionsQtype
	Stem        string
	Options     dbtypes.NullJSON
	Answer      sql.NullString
	Analysis    sql.NullString
	Score       sql.NullString
	ExamYear    sql.NullInt16
	ContentHash string
}

func (q *Queries) InsertOfficialQuestion(ctx context.Context, arg InsertOfficialQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOfficialQuestion,
		arg.BankID,
		arg.Qtype,
		arg.Stem,
		arg.Options,
		arg.Answer,
		arg.Analysis,
		arg.Score,
		arg.ExamYear,
		arg.ContentHash,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertOfficialQuestionKP = `-- name: InsertOfficialQuestionKP :exec
INSERT IGNORE INTO question_kps (question_id, kp_id, is_primary, owner_user_id) VALUES (?, ?, ?, ?)
`

type InsertOfficialQuestionKPParams struct {
	QuestionID  uint64
	KpID        uint64
	IsPrimary   bool
	OwnerUserID sql.NullInt64
}

func (q *Queries) InsertOfficialQuestionKP(ctx context.Context, arg InsertOfficialQuestionKPParams) error {
	_, err := q.db.ExecContext(ctx, insertOfficialQuestionKP,
		arg.QuestionID,
		arg.KpID,
		arg.IsPrimary,
		arg.OwnerUserID,
	)
	return err
}

const insertOfficialRubricPoint = `-- name: InsertOfficialRubricPoint :exec
INSERT INTO rubric_points (owner_user_id, question_id, kp_id, seq, content, keywords, score, origin) VALUES (?, ?, ?, ?, ?, ?, ?, 'official')
`

type InsertOfficialRubricPointParams struct {
	OwnerUserID sql.NullInt64
	QuestionID  sql.NullInt64
	KpID        sql.NullInt64
	Seq         uint16
	Content     string
	Keywords    dbtypes.NullJSON
	Score       sql.NullString
}

func (q *Queries) InsertOfficialRubricPoint(ctx context.Context, arg InsertOfficialRubricPointParams) error {
	_, err := q.db.ExecContext(ctx, insertOfficialRubricPoint,
		arg.OwnerUserID,
		arg.QuestionID,
		arg.KpID,
		arg.Seq,
		arg.Content,
		arg.Keywords,
		arg.Score,
	)
	return err
}

const insertOfficialVersion = `-- name: InsertOfficialVersion :execlastid

INSERT INTO official_versions (project_id, version, changelog, snapshot, published_by, published_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertOfficialVersionParams struct {
	ProjectID   uint64
	Version     string
	Changelog   json.RawMessage
	Snapshot    dbtypes.NullJSON
	PublishedBy uint64
	PublishedAt time.Time
}

// ---------- 版本（7.14） ----------
func (q *Queries) InsertOfficialVersion(ctx context.Context, arg InsertOfficialVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOfficialVersion,
		arg.ProjectID,
		arg.Version,
		arg.Changelog,
		arg.Snapshot,
		arg.PublishedBy,
		arg.PublishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertReviewTask = `-- name: InsertReviewTask :execlastid
INSERT INTO review_tasks (draft_id, mode, decision, decided_at) VALUES (?, ?, ?, ?)
`

type InsertReviewTaskParams struct {
	DraftID   uint64
	Mode      ReviewTasksMode
	Decision  ReviewTasksDecision
	DecidedAt sql.NullTime
}

func (q *Queries) InsertReviewTask(ctx context.Context, arg InsertReviewTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertReviewTask,
		arg.DraftID,
		arg.Mode,
		arg.Decision,
		arg.DecidedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO bank_subscriptions (owner_user_id, bank_id, subject_id) VALUES (?, ?, ?)
`

type InsertSubscriptionParams struct {
	OwnerUserID uint64
	BankID      uint64
	SubjectID   uint64
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertSubscription, arg.OwnerUserID, arg.BankID, arg.SubjectID)
	return err
}

const insertUserKPCopy = `-- name: InsertUserKPCopy :execlastid
INSERT INTO knowledge_points (owner_user_id, bank_id, parent_id, level, name, original_text, origin, official_kp_id, official_hash, official_new_until, sort_order)
VALUES (?, ?, ?, ?, ?, ?, 'official', ?, ?, ?, ?)
`

type InsertUserKPCopyParams struct {
	OwnerUserID      sql.NullInt64
	BankID           uint64
	ParentID         sql.NullInt64
	Level            KnowledgePointsLevel
	Name             string
	OriginalText     sql.NullString
	OfficialKpID     sql.NullInt64
	OfficialHash     sql.NullString
	OfficialNewUntil sql.NullTime
	SortOrder        uint32
}

func (q *Queries) InsertUserKPCopy(ctx context.Context, arg InsertUserKPCopyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertUserKPCopy,
		arg.OwnerUserID,
		arg.BankID,
		arg.ParentID,
		arg.Level,
		arg.Name,
		arg.OriginalText,
		arg.OfficialKpID,
		arg.OfficialHash,
		arg.OfficialNewUntil,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertUserQuestionCopy = `-- name: InsertUserQuestionCopy :execlastid
INSERT INTO questions (owner_user_id, bank_id, qtype, stem, options, answer, answer_origin, analysis, score, source, exam_year, content_hash, official_question_id, official_hash)
VALUES (?, ?, ?, ?, ?, ?, 'official', ?, ?, 'official', ?, ?, ?, ?)
`

type InsertUserQuestionCopyParams struct {
	OwnerUserID        sql.NullInt64
	BankID             uint64
	Qtype              QuestionsQtype
	Stem               string
	Options            dbtypes.NullJSON
	Answer             sql.NullString
	Analysis           sql.NullString
	Score              sql.NullString
	ExamYear           sql.NullInt16
	ContentHash        string
	OfficialQuestionID sql.NullInt64
	OfficialHash       sql.NullString
}

func (q *Queries) InsertUserQuestionCopy(ctx context.Context, arg InsertUserQuestionCopyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertUserQuestionCopy,
		arg.OwnerUserID,
		arg.BankID,
		arg.Qtype,
		arg.Stem,
		arg.Options,
		arg.Answer,
		arg.Analysis,
		arg.Score,
		arg.ExamYear,
		arg.ContentHash,
		arg.OfficialQuestionID,
		arg.OfficialHash,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const linkUserKP = `-- name: LinkUserKP :exec
UPDATE knowledge_points SET official_kp_id = ? WHERE id = ? AND owner_user_id = ?
`

type LinkUserKPParams struct {
	OfficialKpID sql.NullInt64
	ID           uint64
	OwnerUserID  sql.NullInt64
}

// 同名知识点合并：保留用户自己的表述和采分点，只记下对应的官方知识点（PRD 11.15）。
func (q *Queries) LinkUserKP(ctx context.Context, arg LinkUserKPParams) error {
	_, err := q.db.ExecContext(ctx, linkUserKP, arg.OfficialKpID, arg.ID, arg.OwnerUserID)
	return err
}

const listApprovedDrafts = `-- name: ListApprovedDrafts :many
SELECT id, project_id, editor_id, entity_type, entity_id, change_type, payload, status, created_at, updated_at, submitted_at, reject_reason FROM official_drafts WHERE project_id = ? AND status = 'approved' ORDER BY id
`

func (q *Queries) ListApprovedDrafts(ctx context.Context, projectID uint64) ([]OfficialDraft, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedDrafts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfficialDraft{}
	for rows.Next() {
		var i OfficialDraft
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EditorID,
			&i.EntityType,
			&i.EntityID,
			&i.ChangeType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.RejectReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDemandMarks = `-- name: ListDemandMarks :many
SELECT subject_code FROM official_demand_marks
`

func (q *Queries) ListDemandMarks(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDemandMarks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var subject_code string
		if err := rows.Scan(&subject_code); err != nil {
			return nil, err
		}
		items = append(items, subject_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMySubscriptions = `-- name: ListMySubscriptions :many
SELECT bank_id, subject_id, added_at FROM bank_subscriptions WHERE owner_user_id = ?
`

type ListMySubscriptionsRow struct {
	BankID    uint64
	SubjectID uint64
	AddedAt   time.Time
}

func (q *Queries) ListMySubscriptions(ctx context.Context, ownerUserID uint64) ([]ListMySubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMySubscriptions, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMySubscriptionsRow{}
	for rows.Next() {
		var i ListMySubscriptionsRow
		if err := rows.Scan(&i.BankID, &i.SubjectID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialDrafts = `-- name: ListOfficialDrafts :many
SELECT id, project_id, editor_id, entity_type, entity_id, change_type, payload, status, created_at, updated_at, submitted_at, reject_reason FROM official_drafts
WHERE project_id = ? AND (CAST(? AS CHAR) = '' OR status = CAST(? AS CHAR))
  AND (CAST(? AS UNSIGNED) = 0 OR editor_id = CAST(? AS UNSIGNED))
ORDER BY id DESC LIMIT 500
`

type ListOfficialDraftsParams struct {
	ProjectID uint64
	Status    interface{}
	EditorID  int64
}

func (q *Queries) ListOfficialDrafts(ctx context.Context, arg ListOfficialDraftsParams) ([]OfficialDraft, error) {
	rows, err := q.db.QueryContext(ctx, listOfficialDrafts,
		arg.ProjectID,
		arg.Status,
		arg.Status,
		arg.EditorID,
		arg.EditorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfficialDraft{}
	for rows.Next() {
		var i OfficialDraft
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EditorID,
			&i.EntityType,
			&i.EntityID,
			&i.ChangeType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.RejectReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialKPs = `-- name: ListOfficialKPs :many

SELECT id, parent_id, level, name, original_text, sort_order FROM knowledge_points WHERE bank_id = ? AND owner_user_id IS NULL ORDER BY level, sort_order, id
`

type ListOfficialKPsRow struct {
	ID           uint64
	ParentID     sql.NullInt64
	Level        KnowledgePointsLevel
	Name         string
	OriginalText sql.NullString
	SortOrder    uint32
}

// ---------- 官方内容 ----------
func (q *Queries) ListOfficialKPs(ctx context.Context, bankID uint64) ([]ListOfficialKPsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfficialKPs, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfficialKPsRow{}
	for rows.Next() {
		var i ListOfficialKPsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Name,
			&i.OriginalText,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialProjects = `-- name: ListOfficialProjects :many
SELECT p.id, p.school, p.major, p.subject_code, p.subject_name, p.bank_id, p.stage, p.editor_ids, p.authorized_materials, p.created_by, p.created_at, p.updated_at,
  (SELECT COUNT(*) FROM knowledge_points k WHERE k.bank_id = p.bank_id AND k.owner_user_id IS NULL AND k.level = 'point') AS kp_count,
  (SELECT COUNT(*) FROM questions q WHERE q.bank_id = p.bank_id AND q.owner_user_id IS NULL AND q.status = 'active') AS question_count,
  (SELECT COUNT(*) FROM questions q WHERE q.bank_id = p.bank_id AND q.owner_user_id IS NULL AND q.status = 'active' AND q.source = 'official' AND q.exam_year IS NOT NULL) AS exam_count,
  CAST(COALESCE((SELECT v.version FROM official_versions v WHERE v.project_id = p.id AND v.rolled_back_at IS NULL ORDER BY v.id DESC LIMIT 1), '') AS CHAR) AS version,
  (SELECT COUNT(*) FROM bank_subscriptions s WHERE s.bank_id = p.bank_id) AS subscribers
FROM official_projects p ORDER BY p.id DESC
`

type ListOfficialProjectsRow struct {
	ID                  uint64
	School              string
	Major               string
	SubjectCode         string
	SubjectName         string
	BankID              sql.NullInt64
	Stage               OfficialProjectsStage
	EditorIds           dbtypes.NullJSON
	AuthorizedMaterials dbtypes.NullJSON
	CreatedBy           sql.NullInt64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	KpCount             int64
	QuestionCount       int64
	ExamCount           int64
	Version             interface{}
	Subscribers         int64
}

func (q *Queries) ListOfficialProjects(ctx context.Context) ([]ListOfficialProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfficialProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfficialProjectsRow{}
	for rows.Next() {
		var i ListOfficialProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.School,
			&i.Major,
			&i.SubjectCode,
			&i.SubjectName,
			&i.BankID,
			&i.Stage,
			&i.EditorIds,
			&i.AuthorizedMaterials,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KpCount,
			&i.QuestionCount,
			&i.ExamCount,
			&i.Version,
			&i.Subscribers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialQuestionKPs = `-- name: ListOfficialQuestionKPs :many
SELECT qk.question_id, qk.kp_id, qk.is_primary FROM question_kps qk JOIN questions q ON q.id = qk.question_id WHERE q.bank_id = ? AND q.owner_user_id IS NULL
`

type ListOfficialQuestionKPsRow struct {
	QuestionID uint64
	KpID       uint64
	IsPrimary  bool
}

func (q *Queries) ListOfficialQuestionKPs(ctx context.Context, bankID uint64) ([]ListOfficialQuestionKPsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfficialQuestionKPs, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfficialQuestionKPsRow{}
	for rows.Next() {
		var i ListOfficialQuestionKPsRow
		if err := rows.Scan(&i.QuestionID, &i.KpID, &i.IsPrimary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialQuestions = `-- name: ListOfficialQuestions :many
SELECT id, qtype, stem, options, answer, analysis, score, exam_year, status FROM questions WHERE bank_id = ? AND owner_user_id IS NULL ORDER BY id
`

type ListOfficialQuestionsRow struct {
	ID       uint64
	Qtype    QuestionsQtype
	Stem     string
	Options  dbtypes.NullJSON
	Answer   sql.NullString
	Analysis sql.NullString
	Score    sql.NullString
	ExamYear sql.NullInt16
	Status   QuestionsStatus
}

func (q *Queries) ListOfficialQuestions(ctx context.Context, bankID uint64) ([]ListOfficialQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfficialQuestions, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfficialQuestionsRow{}
	for rows.Next() {
		var i ListOfficialQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Qtype,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Analysis,
			&i.Score,
			&i.ExamYear,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialRubric = `-- name: ListOfficialRubric :many
SELECT r.id, r.question_id, r.kp_id, r.seq, r.content, r.keywords, r.score FROM rubric_points r
WHERE r.owner_user_id IS NULL AND (r.question_id IN (SELECT q.id FROM questions q WHERE q.bank_id = ? AND q.owner_user_id IS NULL)
   OR r.kp_id IN (SELECT k.id FROM knowledge_points k WHERE k.bank_id = ? AND k.owner_user_id IS NULL))
ORDER BY r.question_id, r.kp_id, r.seq
`

type ListOfficialRubricParams struct {
	BankID uint64
}

type ListOfficialRubricRow struct {
	ID         uint64
	QuestionID sql.NullInt64
	KpID       sql.NullInt64
	Seq        uint16
	Content    string
	Keywords   dbtypes.NullJSON
	Score      sql.NullString
}

// 官方题库的全部采分点（题目的与知识点的）。
func (q *Queries) ListOfficialRubric(ctx context.Context, arg ListOfficialRubricParams) ([]ListOfficialRubricRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfficialRubric, arg.BankID, arg.BankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfficialRubricRow{}
	for rows.Next() {
		var i ListOfficialRubricRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.KpID,
			&i.Seq,
			&i.Content,
			&i.Keywords,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialVersions = `-- name: ListOfficialVersions :many
SELECT id, project_id, version, changelog, published_by, published_at, rolled_back_at FROM official_versions WHERE project_id = ? ORDER BY id DESC
`

type ListOfficialVersionsRow struct {
	ID           uint64
	ProjectID    uint64
	Version      string
	Changelog    json.RawMessage
	PublishedBy  uint64
	PublishedAt  time.Time
	RolledBackAt sql.NullTime
}

func (q *Queries) ListOfficialVersions(ctx context.Context, projectID uint64) ([]ListOfficialVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfficialVersions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfficialVersionsRow{}
	for rows.Next() {
		var i ListOfficialVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Changelog,
			&i.PublishedBy,
			&i.PublishedAt,
			&i.RolledBackAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReviews = `-- name: ListPendingReviews :many
SELECT t.id, t.draft_id, t.mode, t.created_at, d.project_id, d.editor_id, d.entity_type, d.entity_id, d.change_type, d.payload
FROM review_tasks t JOIN official_drafts d ON d.id = t.draft_id
WHERE t.decision = 'pending' AND (CAST(? AS UNSIGNED) = 0 OR d.project_id = CAST(? AS UNSIGNED))
ORDER BY t.id LIMIT 200
`

type ListPendingReviewsParams struct {
	ProjectID int64
}

type ListPendingReviewsRow struct {
	ID         uint64
	DraftID    uint64
	Mode       ReviewTasksMode
	CreatedAt  time.Time
	ProjectID  uint64
	EditorID   uint64
	EntityType OfficialDraftsEntityType
	EntityID   sql.NullInt64
	ChangeType OfficialDraftsChangeType
	Payload    json.RawMessage
}

func (q *Queries) ListPendingReviews(ctx context.Context, arg ListPendingReviewsParams) ([]ListPendingReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReviews, arg.ProjectID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingReviewsRow{}
	for rows.Next() {
		var i ListPendingReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.Mode,
			&i.CreatedAt,
			&i.ProjectID,
			&i.EditorID,
			&i.EntityType,
			&i.EntityID,
			&i.ChangeType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedOfficialBanks = `-- name: ListPublishedOfficialBanks :many

SELECT b.id AS bank_id, b.title, b.subject_code, p.id AS project_id, p.school, p.major, p.subject_name,
  CAST(COALESCE((SELECT v.version FROM official_versions v WHERE v.project_id = p.id AND v.rolled_back_at IS NULL ORDER BY v.id DESC LIMIT 1), '') AS CHAR) AS version,
  (SELECT COUNT(*) FROM knowledge_points k WHERE k.bank_id = b.id AND k.owner_user_id IS NULL AND k.level = 'point') AS kp_count,
  (SELECT COUNT(*) FROM questions q WHERE q.bank_id = b.id AND q.owner_user_id IS NULL AND q.status = 'active') AS question_count
FROM banks b JOIN official_projects p ON p.bank_id = b.id
WHERE b.source = 'official' AND EXISTS (SELECT 1 FROM official_versions v WHERE v.project_id = p.id AND v.rolled_back_at IS NULL)
ORDER BY b.id
`

type ListPublishedOfficialBanksRow struct {
	BankID        uint64
	Title         string
	SubjectCode   sql.NullString
	ProjectID     uint64
	School        string
	Major         string
	SubjectName   string
	Version       interface{}
	KpCount       int64
	QuestionCount int64
}

// ---------- 用户添加官方题库（11.15） ----------
func (q *Queries) ListPublishedOfficialBanks(ctx context.Context) ([]ListPublishedOfficialBanksRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedOfficialBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedOfficialBanksRow{}
	for rows.Next() {
		var i ListPublishedOfficialBanksRow
		if err := rows.Scan(
			&i.BankID,
			&i.Title,
			&i.SubjectCode,
			&i.ProjectID,
			&i.School,
			&i.Major,
			&i.SubjectName,
			&i.Version,
			&i.KpCount,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT owner_user_id, subject_id FROM bank_subscriptions WHERE bank_id = ?
`

type ListSubscribersRow struct {
	OwnerUserID uint64
	SubjectID   uint64
}

func (q *Queries) ListSubscribers(ctx context.Context, bankID uint64) ([]ListSubscribersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscribers, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribersRow{}
	for rows.Next() {
		var i ListSubscribersRow
		if err := rows.Scan(&i.OwnerUserID, &i.SubjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserKPCopies = `-- name: ListUserKPCopies :many
SELECT id, parent_id, level, name, original_text, origin, official_kp_id, official_hash FROM knowledge_points WHERE bank_id = ? AND owner_user_id = ?
`

type ListUserKPCopiesParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListUserKPCopiesRow struct {
	ID           uint64
	ParentID     sql.NullInt64
	Level        KnowledgePointsLevel
	Name         string
	OriginalText sql.NullString
	Origin       KnowledgePointsOrigin
	OfficialKpID sql.NullInt64
	OfficialHash sql.NullString
}

// 用户题库里的全部知识点（含自建的，同名合并要用）。
func (q *Queries) ListUserKPCopies(ctx context.Context, arg ListUserKPCopiesParams) ([]ListUserKPCopiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserKPCopies, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserKPCopiesRow{}
	for rows.Next() {
		var i ListUserKPCopiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Name,
			&i.OriginalText,
			&i.Origin,
			&i.OfficialKpID,
			&i.OfficialHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserQuestionCopies = `-- name: ListUserQuestionCopies :many
SELECT id, official_question_id, qtype, stem, answer, status, official_hash FROM questions WHERE bank_id = ? AND owner_user_id = ? AND official_question_id IS NOT NULL
`

type ListUserQuestionCopiesParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListUserQuestionCopiesRow struct {
	ID                 uint64
	OfficialQuestionID sql.NullInt64
	Qtype              QuestionsQtype
	Stem               string
	Answer             sql.NullString
	Status             QuestionsStatus
	OfficialHash       sql.NullString
}

func (q *Queries) ListUserQuestionCopies(ctx context.Context, arg ListUserQuestionCopiesParams) ([]ListUserQuestionCopiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserQuestionCopies, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserQuestionCopiesRow{}
	for rows.Next() {
		var i ListUserQuestionCopiesRow
		if err := rows.Scan(
			&i.ID,
			&i.OfficialQuestionID,
			&i.Qtype,
			&i.Stem,
			&i.Answer,
			&i.Status,
			&i.OfficialHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRubricForCopies = `-- name: ListUserRubricForCopies :many
SELECT r.question_id, r.kp_id, r.seq, r.content FROM rubric_points r WHERE r.owner_user_id = ?
  AND (r.question_id IN (SELECT q.id FROM questions q WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.official_question_id IS NOT NULL)
    OR r.kp_id IN (SELECT k.id FROM knowledge_points k WHERE k.bank_id = ? AND k.owner_user_id = ? AND k.official_kp_id IS NOT NULL))
ORDER BY r.question_id, r.kp_id, r.seq
`

type ListUserRubricForCopiesParams struct {
	Owner  sql.NullInt64
	BankID uint64
}

type ListUserRubricForCopiesRow struct {
	QuestionID sql.NullInt64
	KpID       sql.NullInt64
	Seq        uint16
	Content    string
}

func (q *Queries) ListUserRubricForCopies(ctx context.Context, arg ListUserRubricForCopiesParams) ([]ListUserRubricForCopiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRubricForCopies,
		arg.Owner,
		arg.BankID,
		arg.Owner,
		arg.BankID,
		arg.Owner,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRubricForCopiesRow{}
	for rows.Next() {
		var i ListUserRubricForCopiesRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.KpID,
			&i.Seq,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOfficialVersionRolledBack = `-- name: MarkOfficialVersionRolledBack :execrows
UPDATE official_versions SET rolled_back_at = ? WHERE id = ? AND rolled_back_at IS NULL
`

type MarkOfficialVersionRolledBackParams struct {
	RolledBackAt sql.NullTime
	ID           uint64
}

func (q *Queries) MarkOfficialVersionRolledBack(ctx context.Context, arg MarkOfficialVersionRolledBackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOfficialVersionRolledBack, arg.RolledBackAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const notifyOfficialLaunch = `-- name: NotifyOfficialLaunch :execrows
INSERT IGNORE INTO messages (owner_user_id, mtype, title, body, link, dedupe_key)
SELECT DISTINCT s.owner_user_id, 'official_bank', ?, ?, ?, ?
FROM subjects s JOIN users u ON u.id = s.owner_user_id
WHERE s.code = ? AND u.status = 'active'
  AND (EXISTS (SELECT 1 FROM feature_flags f WHERE f.flag_key = 'official_bank' AND f.enabled_for_all = 1)
    OR EXISTS (SELECT 1 FROM feature_flag_users fu WHERE fu.flag_key = 'official_bank' AND fu.user_id = s.owner_user_id))
`

type NotifyOfficialLaunchParams struct {
	Title     string
	Body      string
	Link      dbtypes.NullJSON
	DedupeKey sql.NullString
	Code      sql.NullString
}

// 官方题库首次上线：自建了同一专业课（代码相同）、能看到官方题库开关的用户收到提醒（PRD 5.6）。
func (q *Queries) NotifyOfficialLaunch(ctx context.Context, arg NotifyOfficialLaunchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, notifyOfficialLaunch,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.DedupeKey,
		arg.Code,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reciteReviewAgain = `-- name: ReciteReviewAgain :exec
UPDATE kp_mastery SET recite_next_review_on = ?, recite_interval_step = 0 WHERE kp_id = ? AND owner_user_id = ? AND recite_next_review_on IS NOT NULL
`

type ReciteReviewAgainParams struct {
	ReciteNextReviewOn sql.NullTime
	KpID               uint64
	OwnerUserID        uint64
}

// 官方采分点有实质变化时，对应背诵重新进入复习（PRD 11.15）。
func (q *Queries) ReciteReviewAgain(ctx context.Context, arg ReciteReviewAgainParams) error {
	_, err := q.db.ExecContext(ctx, reciteReviewAgain, arg.ReciteNextReviewOn, arg.KpID, arg.OwnerUserID)
	return err
}

const setOfficialDraftPayload = `-- name: SetOfficialDraftPayload :exec
UPDATE official_drafts SET payload = ? WHERE id = ?
`

type SetOfficialDraftPayloadParams struct {
	Payload json.RawMessage
	ID      uint64
}

func (q *Queries) SetOfficialDraftPayload(ctx context.Context, arg SetOfficialDraftPayloadParams) error {
	_, err := q.db.ExecContext(ctx, setOfficialDraftPayload, arg.Payload, arg.ID)
	return err
}

const setOfficialDraftStatus = `-- name: SetOfficialDraftStatus :exec
UPDATE official_drafts SET status = ?, reject_reason = ? WHERE id = ?
`

type SetOfficialDraftStatusParams struct {
	Status       OfficialDraftsStatus
	RejectReason sql.NullString
	ID           uint64
}

func (q *Queries) SetOfficialDraftStatus(ctx context.Context, arg SetOfficialDraftStatusParams) error {
	_, err := q.db.ExecContext(ctx, setOfficialDraftStatus, arg.Status, arg.RejectReason, arg.ID)
	return err
}

const setOfficialProjectStage = `-- name: SetOfficialProjectStage :exec
UPDATE official_projects SET stage = ? WHERE id = ?
`

type SetOfficialProjectStageParams struct {
	Stage OfficialProjectsStage
	ID    uint64
}

func (q *Queries) SetOfficialProjectStage(ctx context.Context, arg SetOfficialProjectStageParams) error {
	_, err := q.db.ExecContext(ctx, setOfficialProjectStage, arg.Stage, arg.ID)
	return err
}

const setOfficialQuestionStatus = `-- name: SetOfficialQuestionStatus :exec
UPDATE questions SET status = ? WHERE id = ? AND bank_id = ? AND owner_user_id IS NULL
`

type SetOfficialQuestionStatusParams struct {
	Status QuestionsStatus
	ID     uint64
	BankID uint64
}

func (q *Queries) SetOfficialQuestionStatus(ctx context.Context, arg SetOfficialQuestionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setOfficialQuestionStatus, arg.Status, arg.ID, arg.BankID)
	return err
}

const setUserQuestionStatus = `-- name: SetUserQuestionStatus :exec
UPDATE questions SET status = ? WHERE id = ? AND owner_user_id = ?
`

type SetUserQuestionStatusParams struct {
	Status      QuestionsStatus
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) SetUserQuestionStatus(ctx context.Context, arg SetUserQuestionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setUserQuestionStatus, arg.Status, arg.ID, arg.OwnerUserID)
	return err
}

const statDemand = `-- name: StatDemand :many

SELECT s.code,
  COUNT(DISTINCT s.owner_user_id) AS users,
  CAST(COALESCE(AVG((SELECT COUNT(*) FROM questions q WHERE q.bank_id = b.id AND q.owner_user_id = s.owner_user_id AND q.status = 'active')), 0) AS SIGNED) AS avg_questions,
  CAST(SUM(s.created_at >= ?) AS SIGNED) AS week_new,
  CAST(SUM(EXISTS (SELECT 1 FROM study_profiles p WHERE p.user_id = s.owner_user_id AND p.target_school_major IS NOT NULL AND p.target_school_major <> '')) AS SIGNED) AS with_target,
  CAST(SUM(EXISTS (SELECT 1 FROM orders o WHERE o.owner_user_id = s.owner_user_id AND o.status IN ('paid', 'refunding'))) AS SIGNED) AS paid,
  CAST(COALESCE(AVG((SELECT COUNT(*) FROM import_items i WHERE i.owner_user_id = s.owner_user_id AND i.needs_review = 1 AND i.status = 'pending')), 0) AS SIGNED) AS avg_review
FROM subjects s JOIN banks b ON b.subject_id = s.id
WHERE s.code IS NOT NULL AND s.code <> ''
GROUP BY s.code ORDER BY users DESC LIMIT 200
`

type StatDemandRow struct {
	Code         sql.NullString
	Users        int64
	AvgQuestions int64
	WeekNew      int64
	WithTarget   int64
	Paid         int64
	AvgReview    int64
}

// ---------- 需求洞察（7.10，只用统计） ----------
// 按专业课代码聚合：自建用户数、平均题数、本周新增、填了目标院校的人数、付费人数（只有计数）。
func (q *Queries) StatDemand(ctx context.Context, weekStart time.Time) ([]StatDemandRow, error) {
	rows, err := q.db.QueryContext(ctx, statDemand, weekStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatDemandRow{}
	for rows.Next() {
		var i StatDemandRow
		if err := rows.Scan(
			&i.Code,
			&i.Users,
			&i.AvgQuestions,
			&i.WeekNew,
			&i.WithTarget,
			&i.Paid,
			&i.AvgReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitOfficialDraft = `-- name: SubmitOfficialDraft :execrows
UPDATE official_drafts SET status = 'submitted', submitted_at = ?, reject_reason = NULL WHERE id = ? AND editor_id = ? AND status IN ('draft', 'rejected')
`

type SubmitOfficialDraftParams struct {
	SubmittedAt sql.NullTime
	ID          uint64
	EditorID    uint64
}

func (q *Queries) SubmitOfficialDraft(ctx context.Context, arg SubmitOfficialDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, submitOfficialDraft, arg.SubmittedAt, arg.ID, arg.EditorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unlinkUserKP = `-- name: UnlinkUserKP :exec
UPDATE knowledge_points SET official_kp_id = NULL, official_hash = NULL, official_new_until = NULL, origin = IF(origin = 'official', 'user_confirmed', origin) WHERE id = ? AND owner_user_id = ?
`

type UnlinkUserKPParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) UnlinkUserKP(ctx context.Context, arg UnlinkUserKPParams) error {
	_, err := q.db.ExecContext(ctx, unlinkUserKP, arg.ID, arg.OwnerUserID)
	return err
}

const unlinkUserQuestion = `-- name: UnlinkUserQuestion :exec
UPDATE questions SET official_question_id = NULL, official_hash = NULL, source = IF(source = 'official', 'exercise', source) WHERE id = ? AND owner_user_id = ?
`

type UnlinkUserQuestionParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) UnlinkUserQuestion(ctx context.Context, arg UnlinkUserQuestionParams) error {
	_, err := q.db.ExecContext(ctx, unlinkUserQuestion, arg.ID, arg.OwnerUserID)
	return err
}

const updateOfficialDraft = `-- name: UpdateOfficialDraft :execrows
UPDATE official_drafts SET change_type = ?, entity_id = ?, payload = ?, status = 'draft' WHERE id = ? AND editor_id = ? AND status IN ('draft', 'rejected')
`

type UpdateOfficialDraftParams struct {
	ChangeType OfficialDraftsChangeType
	EntityID   sql.NullInt64
	Payload    json.RawMessage
	ID         uint64
	EditorID   uint64
}

// 草稿和被退回的可以改；改完回到草稿。
func (q *Queries) UpdateOfficialDraft(ctx context.Context, arg UpdateOfficialDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOfficialDraft,
		arg.ChangeType,
		arg.EntityID,
		arg.Payload,
		arg.ID,
		arg.EditorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOfficialKP = `-- name: UpdateOfficialKP :exec
UPDATE knowledge_points SET name = ?, original_text = ? WHERE id = ? AND bank_id = ? AND owner_user_id IS NULL
`

type UpdateOfficialKPParams struct {
	Name         string
	OriginalText sql.NullString
	ID           uint64
	BankID       uint64
}

func (q *Queries) UpdateOfficialKP(ctx context.Context, arg UpdateOfficialKPParams) error {
	_, err := q.db.ExecContext(ctx, updateOfficialKP,
		arg.Name,
		arg.OriginalText,
		arg.ID,
		arg.BankID,
	)
	return err
}

const updateOfficialProject = `-- name: UpdateOfficialProject :exec
UPDATE official_projects SET editor_ids = ?, authorized_materials = ?, stage = ? WHERE id = ?
`

type UpdateOfficialProjectParams struct {
	EditorIds           dbtypes.NullJSON
	AuthorizedMaterials dbtypes.NullJSON
	Stage               OfficialProjectsStage
	ID                  uint64
}

func (q *Queries) UpdateOfficialProject(ctx context.Context, arg UpdateOfficialProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateOfficialProject,
		arg.EditorIds,
		arg.AuthorizedMaterials,
		arg.Stage,
		arg.ID,
	)
	return err
}

const updateOfficialQuestion = `-- name: UpdateOfficialQuestion :exec
UPDATE questions SET qtype = ?, stem = ?, options = ?, answer = ?, analysis = ?, score = ?, exam_year = ?, content_hash = ?, rubric_version = rubric_version + 1
WHERE id = ? AND bank_id = ? AND owner_user_id IS NULL
`

type UpdateOfficialQuestionParams struct {
	Qtype       QuestionsQtype
	Stem        string
	Options     dbtypes.NullJSON
	Answer      sql.NullString
	Analysis    sql.NullString
	Score       sql.NullString
	ExamYear    sql.NullInt16
	ContentHash string
	ID          uint64
	BankID      uint64
}

func (q *Queries) UpdateOfficialQuestion(ctx context.Context, arg UpdateOfficialQuestionParams) error {
	_, err := q.db.ExecContext(ctx, updateOfficialQuestion,
		arg.Qtype,
		arg.Stem,
		arg.Options,
		arg.Answer,
		arg.Analysis,
		arg.Score,
		arg.ExamYear,
		arg.ContentHash,
		arg.ID,
		arg.BankID,
	)
	return err
}

const updateUserKPCopy = `-- name: UpdateUserKPCopy :exec
UPDATE knowledge_points SET name = ?, original_text = ?, official_hash = ? WHERE id = ? AND owner_user_id = ?
`

type UpdateUserKPCopyParams struct {
	Name         string
	OriginalText sql.NullString
	OfficialHash sql.NullString
	ID           uint64
	OwnerUserID  sql.NullInt64
}

func (q *Queries) UpdateUserKPCopy(ctx context.Context, arg UpdateUserKPCopyParams) error {
	_, err := q.db.ExecContext(ctx, updateUserKPCopy,
		arg.Name,
		arg.OriginalText,
		arg.OfficialHash,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updateUserQuestionCopy = `-- name: UpdateUserQuestionCopy :exec
UPDATE questions SET qtype = ?, stem = ?, options = ?, answer = ?, analysis = ?, score = ?, exam_year = ?, content_hash = ?, official_hash = ?, status = 'active',
  rubric_version = rubric_version + 1
WHERE id = ? AND owner_user_id = ?
`

type UpdateUserQuestionCopyParams struct {
	Qtype        QuestionsQtype
	Stem         string
	Options      dbtypes.NullJSON
	Answer       sql.NullString
	Analysis     sql.NullString
	Score        sql.NullString
	ExamYear     sql.NullInt16
	ContentHash  string
	OfficialHash sql.NullString
	ID           uint64
	OwnerUserID  sql.NullInt64
}

func (q *Queries) UpdateUserQuestionCopy(ctx context.Context, arg UpdateUserQuestionCopyParams) error {
	_, err := q.db.ExecContext(ctx, updateUserQuestionCopy,
		arg.Qtype,
		arg.Stem,
		arg.Options,
		arg.Answer,
		arg.Analysis,
		arg.Score,
		arg.ExamYear,
		arg.ContentHash,
		arg.OfficialHash,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const upsertDemandMark = `-- name: UpsertDemandMark :exec
INSERT INTO official_demand_marks (subject_code, status, marked_by) VALUES (?, 'unplanned', ?) ON DUPLICATE KEY UPDATE marked_by = VALUES(marked_by), marked_at = CURRENT_TIMESTAMP(3)
`

type UpsertDemandMarkParams struct {
	SubjectCode string
	MarkedBy    sql.NullInt64
}

func (q *Queries) UpsertDemandMark(ctx context.Context, arg UpsertDemandMarkParams) error {
	_, err := q.db.ExecContext(ctx, upsertDemandMark, arg.SubjectCode, arg.MarkedBy)
	return err
}
