// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: paper.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const abandonPaperSession = `-- name: AbandonPaperSession :exec
UPDATE paper_sessions SET status = 'abandoned' WHERE id = ? AND owner_user_id = ? AND status IN ('in_progress', 'paused')
`

type AbandonPaperSessionParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) AbandonPaperSession(ctx context.Context, arg AbandonPaperSessionParams) error {
	_, err := q.db.ExecContext(ctx, abandonPaperSession, arg.ID, arg.OwnerUserID)
	return err
}

const activePaperSession = `-- name: ActivePaperSession :one
SELECT id, owner_user_id, paper_id, subject_id, paper_kind, paper_title, mode, status, started_at, deadline_at, interrupted_at, resume_used, paused_seconds, submitted_at, graded_at, full_score, score, counts_for_estimate, report, idempotency_key, paused_at, quota_period FROM paper_sessions WHERE owner_user_id = ? AND status IN ('in_progress', 'paused') ORDER BY id DESC LIMIT 1
`

// 同一用户同一时间只能有一套进行中（含暂停）。
func (q *Queries) ActivePaperSession(ctx context.Context, ownerUserID uint64) (PaperSession, error) {
	row := q.db.QueryRowContext(ctx, activePaperSession, ownerUserID)
	var i PaperSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PaperID,
		&i.SubjectID,
		&i.PaperKind,
		&i.PaperTitle,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.InterruptedAt,
		&i.ResumeUsed,
		&i.PausedSeconds,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.FullScore,
		&i.Score,
		&i.CountsForEstimate,
		&i.Report,
		&i.IdempotencyKey,
		&i.PausedAt,
		&i.QuotaPeriod,
	)
	return i, err
}

const donePaperQuestionIDs = `-- name: DonePaperQuestionIDs :many
SELECT DISTINCT i.question_id FROM paper_session_items i JOIN paper_sessions s ON s.id = i.paper_session_id
WHERE s.owner_user_id = ? AND s.status IN ('grading', 'graded') AND i.question_id IS NOT NULL
`

// 已在整卷中做过的题（AI 组卷不再出现做过的真题）。
func (q *Queries) DonePaperQuestionIDs(ctx context.Context, ownerUserID uint64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, donePaperQuestionIDs, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var question_id sql.NullInt64
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishPaperGrading = `-- name: FinishPaperGrading :exec
UPDATE paper_sessions SET status = 'graded', graded_at = ?, score = ?, report = ? WHERE id = ? AND owner_user_id = ? AND status = 'grading'
`

type FinishPaperGradingParams struct {
	GradedAt    sql.NullTime
	Score       sql.NullString
	Report      dbtypes.NullJSON
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) FinishPaperGrading(ctx context.Context, arg FinishPaperGradingParams) error {
	_, err := q.db.ExecContext(ctx, finishPaperGrading,
		arg.GradedAt,
		arg.Score,
		arg.Report,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const getPaper = `-- name: GetPaper :one
SELECT p.id, p.owner_user_id, p.bank_id, p.kind, p.title, p.exam_year, p.full_score, p.actual_score, p.duration_minutes, p.structure, p.missing_note, p.source_material_id, p.created_at, b.subject_id FROM papers p JOIN banks b ON b.id = p.bank_id WHERE p.id = ? AND p.owner_user_id = ?
`

type GetPaperParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

type GetPaperRow struct {
	ID               uint64
	OwnerUserID      sql.NullInt64
	BankID           uint64
	Kind             PapersKind
	Title            string
	ExamYear         sql.NullInt16
	FullScore        string
	ActualScore      string
	DurationMinutes  uint16
	Structure        json.RawMessage
	MissingNote      sql.NullString
	SourceMaterialID sql.NullInt64
	CreatedAt        time.Time
	SubjectID        sql.NullInt64
}

func (q *Queries) GetPaper(ctx context.Context, arg GetPaperParams) (GetPaperRow, error) {
	row := q.db.QueryRowContext(ctx, getPaper, arg.ID, arg.OwnerUserID)
	var i GetPaperRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Kind,
		&i.Title,
		&i.ExamYear,
		&i.FullScore,
		&i.ActualScore,
		&i.DurationMinutes,
		&i.Structure,
		&i.MissingNote,
		&i.SourceMaterialID,
		&i.CreatedAt,
		&i.SubjectID,
	)
	return i, err
}

const getPaperSession = `-- name: GetPaperSession :one
SELECT id, owner_user_id, paper_id, subject_id, paper_kind, paper_title, mode, status, started_at, deadline_at, interrupted_at, resume_used, paused_seconds, submitted_at, graded_at, full_score, score, counts_for_estimate, report, idempotency_key, paused_at, quota_period FROM paper_sessions WHERE id = ? AND owner_user_id = ?
`

type GetPaperSessionParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetPaperSession(ctx context.Context, arg GetPaperSessionParams) (PaperSession, error) {
	row := q.db.QueryRowContext(ctx, getPaperSession, arg.ID, arg.OwnerUserID)
	var i PaperSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PaperID,
		&i.SubjectID,
		&i.PaperKind,
		&i.PaperTitle,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.InterruptedAt,
		&i.ResumeUsed,
		&i.PausedSeconds,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.FullScore,
		&i.Score,
		&i.CountsForEstimate,
		&i.Report,
		&i.IdempotencyKey,
		&i.PausedAt,
		&i.QuotaPeriod,
	)
	return i, err
}

const getPaperSessionByKey = `-- name: GetPaperSessionByKey :one
SELECT id, owner_user_id, paper_id, subject_id, paper_kind, paper_title, mode, status, started_at, deadline_at, interrupted_at, resume_used, paused_seconds, submitted_at, graded_at, full_score, score, counts_for_estimate, report, idempotency_key, paused_at, quota_period FROM paper_sessions WHERE owner_user_id = ? AND idempotency_key = ?
`

type GetPaperSessionByKeyParams struct {
	OwnerUserID    uint64
	IdempotencyKey sql.NullString
}

func (q *Queries) GetPaperSessionByKey(ctx context.Context, arg GetPaperSessionByKeyParams) (PaperSession, error) {
	row := q.db.QueryRowContext(ctx, getPaperSessionByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i PaperSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PaperID,
		&i.SubjectID,
		&i.PaperKind,
		&i.PaperTitle,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.InterruptedAt,
		&i.ResumeUsed,
		&i.PausedSeconds,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.FullScore,
		&i.Score,
		&i.CountsForEstimate,
		&i.Report,
		&i.IdempotencyKey,
		&i.PausedAt,
		&i.QuotaPeriod,
	)
	return i, err
}

const getPaperSessionForUpdate = `-- name: GetPaperSessionForUpdate :one
SELECT id, owner_user_id, paper_id, subject_id, paper_kind, paper_title, mode, status, started_at, deadline_at, interrupted_at, resume_used, paused_seconds, submitted_at, graded_at, full_score, score, counts_for_estimate, report, idempotency_key, paused_at, quota_period FROM paper_sessions WHERE id = ? AND owner_user_id = ? FOR UPDATE
`

type GetPaperSessionForUpdateParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetPaperSessionForUpdate(ctx context.Context, arg GetPaperSessionForUpdateParams) (PaperSession, error) {
	row := q.db.QueryRowContext(ctx, getPaperSessionForUpdate, arg.ID, arg.OwnerUserID)
	var i PaperSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PaperID,
		&i.SubjectID,
		&i.PaperKind,
		&i.PaperTitle,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.InterruptedAt,
		&i.ResumeUsed,
		&i.PausedSeconds,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.FullScore,
		&i.Score,
		&i.CountsForEstimate,
		&i.Report,
		&i.IdempotencyKey,
		&i.PausedAt,
		&i.QuotaPeriod,
	)
	return i, err
}

const insertComposedPaper = `-- name: InsertComposedPaper :execlastid
INSERT INTO papers (owner_user_id, bank_id, kind, title, full_score, actual_score, duration_minutes, structure)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertComposedPaperParams struct {
	OwnerUserID     sql.NullInt64
	BankID          uint64
	Kind            PapersKind
	Title           string
	FullScore       string
	ActualScore     string
	DurationMinutes uint16
	Structure       json.RawMessage
}

func (q *Queries) InsertComposedPaper(ctx context.Context, arg InsertComposedPaperParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertComposedPaper,
		arg.OwnerUserID,
		arg.BankID,
		arg.Kind,
		arg.Title,
		arg.FullScore,
		arg.ActualScore,
		arg.DurationMinutes,
		arg.Structure,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertMessage = `-- name: InsertMessage :exec
INSERT IGNORE INTO messages (owner_user_id, mtype, title, body, link, dedupe_key) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	OwnerUserID uint64
	Mtype       MessagesMtype
	Title       string
	Body        string
	Link        dbtypes.NullJSON
	DedupeKey   sql.NullString
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.OwnerUserID,
		arg.Mtype,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.DedupeKey,
	)
	return err
}

const insertPaperAttempt = `-- name: InsertPaperAttempt :execlastid
INSERT INTO attempts (owner_user_id, question_id, paper_session_id, answer_mode, selected, answer_text, is_correct, score, full_score,
  duration_seconds, timed, answered_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPaperAttemptParams struct {
	OwnerUserID     uint64
	QuestionID      uint64
	PaperSessionID  sql.NullInt64
	AnswerMode      AttemptsAnswerMode
	Selected        dbtypes.NullJSON
	AnswerText      sql.NullString
	IsCorrect       sql.NullBool
	Score           sql.NullString
	FullScore       sql.NullString
	DurationSeconds uint32
	Timed           bool
	AnsweredAt      time.Time
}

// 整卷里的一道作答（模拟考试记为限时作答，失分诊断「时间不够」只在这里判定）。
func (q *Queries) InsertPaperAttempt(ctx context.Context, arg InsertPaperAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertPaperAttempt,
		arg.OwnerUserID,
		arg.QuestionID,
		arg.PaperSessionID,
		arg.AnswerMode,
		arg.Selected,
		arg.AnswerText,
		arg.IsCorrect,
		arg.Score,
		arg.FullScore,
		arg.DurationSeconds,
		arg.Timed,
		arg.AnsweredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertPaperSession = `-- name: InsertPaperSession :execlastid
INSERT INTO paper_sessions (owner_user_id, paper_id, subject_id, paper_kind, paper_title, mode, started_at, deadline_at, full_score,
  counts_for_estimate, quota_period, idempotency_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPaperSessionParams struct {
	OwnerUserID       uint64
	PaperID           sql.NullInt64
	SubjectID         uint64
	PaperKind         PaperSessionsPaperKind
	PaperTitle        string
	Mode              PaperSessionsMode
	StartedAt         time.Time
	DeadlineAt        sql.NullTime
	FullScore         string
	CountsForEstimate bool
	QuotaPeriod       sql.NullString
	IdempotencyKey    sql.NullString
}

func (q *Queries) InsertPaperSession(ctx context.Context, arg InsertPaperSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertPaperSession,
		arg.OwnerUserID,
		arg.PaperID,
		arg.SubjectID,
		arg.PaperKind,
		arg.PaperTitle,
		arg.Mode,
		arg.StartedAt,
		arg.DeadlineAt,
		arg.FullScore,
		arg.CountsForEstimate,
		arg.QuotaPeriod,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertPaperSessionItem = `-- name: InsertPaperSessionItem :exec
INSERT INTO paper_session_items (paper_session_id, seq, question_id, qtype, section, score_max) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPaperSessionItemParams struct {
	PaperSessionID uint64
	Seq            uint16
	QuestionID     sql.NullInt64
	Qtype          string
	Section        string
	ScoreMax       string
}

func (q *Queries) InsertPaperSessionItem(ctx context.Context, arg InsertPaperSessionItemParams) error {
	_, err := q.db.ExecContext(ctx, insertPaperSessionItem,
		arg.PaperSessionID,
		arg.Seq,
		arg.QuestionID,
		arg.Qtype,
		arg.Section,
		arg.ScoreMax,
	)
	return err
}

const lastAttemptDays = `-- name: LastAttemptDays :many
SELECT question_id, MAX(answered_at) AS last_at FROM attempts WHERE owner_user_id = ? GROUP BY question_id
`

type LastAttemptDaysRow struct {
	QuestionID uint64
	LastAt     interface{}
}

// 每道题最近一次作答的时间（针对卷避开近 30 天做过的题）。
func (q *Queries) LastAttemptDays(ctx context.Context, ownerUserID uint64) ([]LastAttemptDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, lastAttemptDays, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastAttemptDaysRow{}
	for rows.Next() {
		var i LastAttemptDaysRow
		if err := rows.Scan(&i.QuestionID, &i.LastAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestRealExamPaper = `-- name: LatestRealExamPaper :one
SELECT id, owner_user_id, bank_id, kind, title, exam_year, full_score, actual_score, duration_minutes, structure, missing_note, source_material_id, created_at FROM papers WHERE bank_id = ? AND owner_user_id = ? AND kind = 'real_exam' ORDER BY exam_year DESC, id DESC LIMIT 1
`

type LatestRealExamPaperParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) LatestRealExamPaper(ctx context.Context, arg LatestRealExamPaperParams) (Paper, error) {
	row := q.db.QueryRowContext(ctx, latestRealExamPaper, arg.BankID, arg.OwnerUserID)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Kind,
		&i.Title,
		&i.ExamYear,
		&i.FullScore,
		&i.ActualScore,
		&i.DurationMinutes,
		&i.Structure,
		&i.MissingNote,
		&i.SourceMaterialID,
		&i.CreatedAt,
	)
	return i, err
}

const listBankPapers = `-- name: ListBankPapers :many

SELECT p.id, p.owner_user_id, p.bank_id, p.kind, p.title, p.exam_year, p.full_score, p.actual_score, p.duration_minutes, p.structure, p.missing_note, p.source_material_id, p.created_at, (SELECT COUNT(*) FROM paper_questions pq WHERE pq.paper_id = p.id) AS question_count,
  (SELECT COUNT(*) FROM paper_questions pq JOIN questions q ON q.id = pq.question_id WHERE pq.paper_id = p.id AND q.source = 'ai_generated') AS ai_filled
FROM papers p
WHERE p.bank_id = ? AND p.owner_user_id = ?
ORDER BY p.kind = 'real_exam' DESC, p.exam_year DESC, p.id DESC
`

type ListBankPapersParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListBankPapersRow struct {
	ID               uint64
	OwnerUserID      sql.NullInt64
	BankID           uint64
	Kind             PapersKind
	Title            string
	ExamYear         sql.NullInt16
	FullScore        string
	ActualScore      string
	DurationMinutes  uint16
	Structure        json.RawMessage
	MissingNote      sql.NullString
	SourceMaterialID sql.NullInt64
	CreatedAt        time.Time
	QuestionCount    int64
	AiFilled         int64
}

// 整卷与模拟考试（T21）。每条查询都带归属条件。
func (q *Queries) ListBankPapers(ctx context.Context, arg ListBankPapersParams) ([]ListBankPapersRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankPapers, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankPapersRow{}
	for rows.Next() {
		var i ListBankPapersRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BankID,
			&i.Kind,
			&i.Title,
			&i.ExamYear,
			&i.FullScore,
			&i.ActualScore,
			&i.DurationMinutes,
			&i.Structure,
			&i.MissingNote,
			&i.SourceMaterialID,
			&i.CreatedAt,
			&i.QuestionCount,
			&i.AiFilled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaperQuestions = `-- name: ListPaperQuestions :many
SELECT pq.seq, pq.question_id, pq.section, pq.score, q.qtype, q.source FROM paper_questions pq
JOIN questions q ON q.id = pq.question_id
WHERE pq.paper_id = ? AND q.owner_user_id = ?
ORDER BY pq.seq
`

type ListPaperQuestionsParams struct {
	PaperID     uint64
	OwnerUserID sql.NullInt64
}

type ListPaperQuestionsRow struct {
	Seq        uint16
	QuestionID uint64
	Section    string
	Score      string
	Qtype      QuestionsQtype
	Source     QuestionsSource
}

func (q *Queries) ListPaperQuestions(ctx context.Context, arg ListPaperQuestionsParams) ([]ListPaperQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaperQuestions, arg.PaperID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaperQuestionsRow{}
	for rows.Next() {
		var i ListPaperQuestionsRow
		if err := rows.Scan(
			&i.Seq,
			&i.QuestionID,
			&i.Section,
			&i.Score,
			&i.Qtype,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaperSessionItems = `-- name: ListPaperSessionItems :many
SELECT i.paper_session_id, i.seq, i.question_id, i.qtype, i.section, i.score_max, i.attempt_id, i.draft_text, i.marked, i.time_spent_seconds, q.stem, q.options, q.source, q.required_words, a.score AS got,
  CAST(COALESCE((SELECT g.id FROM gradings g WHERE g.attempt_id = i.attempt_id AND g.status = 'done' ORDER BY g.id DESC LIMIT 1), 0) AS UNSIGNED) AS grading_id
FROM paper_session_items i
JOIN paper_sessions s ON s.id = i.paper_session_id
LEFT JOIN questions q ON q.id = i.question_id
LEFT JOIN attempts a ON a.id = i.attempt_id
WHERE i.paper_session_id = ? AND s.owner_user_id = ?
ORDER BY i.seq
`

type ListPaperSessionItemsParams struct {
	PaperSessionID uint64
	OwnerUserID    uint64
}

type ListPaperSessionItemsRow struct {
	PaperSessionID   uint64
	Seq              uint16
	QuestionID       sql.NullInt64
	Qtype            string
	Section          string
	ScoreMax         string
	AttemptID        sql.NullInt64
	DraftText        sql.NullString
	Marked           bool
	TimeSpentSeconds uint32
	Stem             sql.NullString
	Options          dbtypes.NullJSON
	Source           NullQuestionsSource
	RequiredWords    sql.NullInt16
	Got              sql.NullString
	GradingID        int64
}

func (q *Queries) ListPaperSessionItems(ctx context.Context, arg ListPaperSessionItemsParams) ([]ListPaperSessionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaperSessionItems, arg.PaperSessionID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaperSessionItemsRow{}
	for rows.Next() {
		var i ListPaperSessionItemsRow
		if err := rows.Scan(
			&i.PaperSessionID,
			&i.Seq,
			&i.QuestionID,
			&i.Qtype,
			&i.Section,
			&i.ScoreMax,
			&i.AttemptID,
			&i.DraftText,
			&i.Marked,
			&i.TimeSpentSeconds,
			&i.Stem,
			&i.Options,
			&i.Source,
			&i.RequiredWords,
			&i.Got,
			&i.GradingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaperSessionsOfUser = `-- name: ListPaperSessionsOfUser :many
SELECT id, paper_id, mode, status, started_at, submitted_at, score, full_score FROM paper_sessions
WHERE owner_user_id = ? AND subject_id = ? AND status <> 'abandoned'
ORDER BY id DESC
`

type ListPaperSessionsOfUserParams struct {
	OwnerUserID uint64
	SubjectID   uint64
}

type ListPaperSessionsOfUserRow struct {
	ID          uint64
	PaperID     sql.NullInt64
	Mode        PaperSessionsMode
	Status      PaperSessionsStatus
	StartedAt   time.Time
	SubmittedAt sql.NullTime
	Score       sql.NullString
	FullScore   string
}

// 整卷列表的状态：每套卷最近的作答。
func (q *Queries) ListPaperSessionsOfUser(ctx context.Context, arg ListPaperSessionsOfUserParams) ([]ListPaperSessionsOfUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaperSessionsOfUser, arg.OwnerUserID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaperSessionsOfUserRow{}
	for rows.Next() {
		var i ListPaperSessionsOfUserRow
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.Mode,
			&i.Status,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.Score,
			&i.FullScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pausePaperSession = `-- name: PausePaperSession :exec
UPDATE paper_sessions SET status = 'paused', paused_at = ? WHERE id = ? AND owner_user_id = ? AND status = 'in_progress'
`

type PausePaperSessionParams struct {
	PausedAt    sql.NullTime
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) PausePaperSession(ctx context.Context, arg PausePaperSessionParams) error {
	_, err := q.db.ExecContext(ctx, pausePaperSession, arg.PausedAt, arg.ID, arg.OwnerUserID)
	return err
}

const qTypeScoreRates = `-- name: QTypeScoreRates :many
SELECT q.qtype, CAST(COALESCE(SUM(a.score), 0) AS DECIMAL(12,2)) AS got, CAST(COALESCE(SUM(a.full_score), 0) AS DECIMAL(12,2)) AS full
FROM attempts a JOIN questions q ON q.id = a.question_id
WHERE a.owner_user_id = ? AND a.score IS NOT NULL AND a.full_score IS NOT NULL
GROUP BY q.qtype
`

type QTypeScoreRatesRow struct {
	Qtype QuestionsQtype
	Got   string
	Full  string
}

// 用户各题型的平均得分率（估计时间失分，PRD 11.9）。
func (q *Queries) QTypeScoreRates(ctx context.Context, ownerUserID uint64) ([]QTypeScoreRatesRow, error) {
	rows, err := q.db.QueryContext(ctx, qTypeScoreRates, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QTypeScoreRatesRow{}
	for rows.Next() {
		var i QTypeScoreRatesRow
		if err := rows.Scan(&i.Qtype, &i.Got, &i.Full); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverPaperSession = `-- name: RecoverPaperSession :exec
UPDATE paper_sessions SET deadline_at = ?, interrupted_at = ?, resume_used = 1 WHERE id = ? AND owner_user_id = ? AND resume_used = 0
`

type RecoverPaperSessionParams struct {
	DeadlineAt    sql.NullTime
	InterruptedAt sql.NullTime
	ID            uint64
	OwnerUserID   uint64
}

// 模拟考试中断恢复：补回中断时长，只能用一次（PRD 11.9）。
func (q *Queries) RecoverPaperSession(ctx context.Context, arg RecoverPaperSessionParams) error {
	_, err := q.db.ExecContext(ctx, recoverPaperSession,
		arg.DeadlineAt,
		arg.InterruptedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const resumePaperSession = `-- name: ResumePaperSession :exec
UPDATE paper_sessions SET status = 'in_progress', paused_seconds = paused_seconds + ?, paused_at = NULL WHERE id = ? AND owner_user_id = ?
`

type ResumePaperSessionParams struct {
	PausedSeconds uint32
	ID            uint64
	OwnerUserID   uint64
}

func (q *Queries) ResumePaperSession(ctx context.Context, arg ResumePaperSessionParams) error {
	_, err := q.db.ExecContext(ctx, resumePaperSession, arg.PausedSeconds, arg.ID, arg.OwnerUserID)
	return err
}

const setPaperItemAttempt = `-- name: SetPaperItemAttempt :exec
UPDATE paper_session_items i JOIN paper_sessions s ON s.id = i.paper_session_id
SET i.attempt_id = ? WHERE i.paper_session_id = ? AND i.seq = ? AND s.owner_user_id = ?
`

type SetPaperItemAttemptParams struct {
	AttemptID      sql.NullInt64
	PaperSessionID uint64
	Seq            uint16
	OwnerUserID    uint64
}

func (q *Queries) SetPaperItemAttempt(ctx context.Context, arg SetPaperItemAttemptParams) error {
	_, err := q.db.ExecContext(ctx, setPaperItemAttempt,
		arg.AttemptID,
		arg.PaperSessionID,
		arg.Seq,
		arg.OwnerUserID,
	)
	return err
}

const submitPaperSession = `-- name: SubmitPaperSession :exec
UPDATE paper_sessions SET status = 'grading', submitted_at = ?, paused_seconds = paused_seconds + ?, paused_at = NULL
WHERE id = ? AND owner_user_id = ? AND status IN ('in_progress', 'paused')
`

type SubmitPaperSessionParams struct {
	SubmittedAt   sql.NullTime
	PausedSeconds uint32
	ID            uint64
	OwnerUserID   uint64
}

func (q *Queries) SubmitPaperSession(ctx context.Context, arg SubmitPaperSessionParams) error {
	_, err := q.db.ExecContext(ctx, submitPaperSession,
		arg.SubmittedAt,
		arg.PausedSeconds,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const updatePaperItem = `-- name: UpdatePaperItem :execrows
UPDATE paper_session_items i JOIN paper_sessions s ON s.id = i.paper_session_id
SET i.draft_text = ?, i.marked = ?, i.time_spent_seconds = i.time_spent_seconds + ?
WHERE i.paper_session_id = ? AND i.seq = ? AND s.owner_user_id = ?
`

type UpdatePaperItemParams struct {
	DraftText        sql.NullString
	Marked           bool
	TimeSpentSeconds uint32
	PaperSessionID   uint64
	Seq              uint16
	OwnerUserID      uint64
}

func (q *Queries) UpdatePaperItem(ctx context.Context, arg UpdatePaperItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePaperItem,
		arg.DraftText,
		arg.Marked,
		arg.TimeSpentSeconds,
		arg.PaperSessionID,
		arg.Seq,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
