// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const getMyOrder = `-- name: GetMyOrder :one
SELECT id, order_no, owner_user_id, tier, channel, amount_cents, status, transaction_id, notify_hash, membership_id, paid_at, created_at, updated_at, app_account_token, idempotency_key FROM orders WHERE order_no = ? AND owner_user_id = ?
`

type GetMyOrderParams struct {
	OrderNo     string
	OwnerUserID sql.NullInt64
}

func (q *Queries) GetMyOrder(ctx context.Context, arg GetMyOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getMyOrder, arg.OrderNo, arg.OwnerUserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.OwnerUserID,
		&i.Tier,
		&i.Channel,
		&i.AmountCents,
		&i.Status,
		&i.TransactionID,
		&i.NotifyHash,
		&i.MembershipID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppAccountToken,
		&i.IdempotencyKey,
	)
	return i, err
}

const getOrderByIdem = `-- name: GetOrderByIdem :one
SELECT id, order_no, owner_user_id, tier, channel, amount_cents, status, transaction_id, notify_hash, membership_id, paid_at, created_at, updated_at, app_account_token, idempotency_key FROM orders WHERE owner_user_id = ? AND idempotency_key = ?
`

type GetOrderByIdemParams struct {
	OwnerUserID    sql.NullInt64
	IdempotencyKey sql.NullString
}

func (q *Queries) GetOrderByIdem(ctx context.Context, arg GetOrderByIdemParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByIdem, arg.OwnerUserID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.OwnerUserID,
		&i.Tier,
		&i.Channel,
		&i.AmountCents,
		&i.Status,
		&i.TransactionID,
		&i.NotifyHash,
		&i.MembershipID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppAccountToken,
		&i.IdempotencyKey,
	)
	return i, err
}

const getOrderByTransaction = `-- name: GetOrderByTransaction :one
SELECT id, order_no, owner_user_id, tier, channel, amount_cents, status, transaction_id, notify_hash, membership_id, paid_at, created_at, updated_at, app_account_token, idempotency_key FROM orders WHERE channel = ? AND transaction_id = ?
`

type GetOrderByTransactionParams struct {
	Channel       OrdersChannel
	TransactionID sql.NullString
}

func (q *Queries) GetOrderByTransaction(ctx context.Context, arg GetOrderByTransactionParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByTransaction, arg.Channel, arg.TransactionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.OwnerUserID,
		&i.Tier,
		&i.Channel,
		&i.AmountCents,
		&i.Status,
		&i.TransactionID,
		&i.NotifyHash,
		&i.MembershipID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppAccountToken,
		&i.IdempotencyKey,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, order_no, owner_user_id, tier, channel, amount_cents, status, transaction_id, notify_hash, membership_id, paid_at, created_at, updated_at, app_account_token, idempotency_key FROM orders WHERE order_no = ? FOR UPDATE
`

// 回调与退款：锁住订单行，重复回调串行执行，第二次看到已支付直接返回。
func (q *Queries) GetOrderForUpdate(ctx context.Context, orderNo string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderForUpdate, orderNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.OwnerUserID,
		&i.Tier,
		&i.Channel,
		&i.AmountCents,
		&i.Status,
		&i.TransactionID,
		&i.NotifyHash,
		&i.MembershipID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppAccountToken,
		&i.IdempotencyKey,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :execlastid

INSERT INTO orders (order_no, owner_user_id, tier, channel, amount_cents, app_account_token, idempotency_key, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertOrderParams struct {
	OrderNo         string
	OwnerUserID     sql.NullInt64
	Tier            OrdersTier
	Channel         OrdersChannel
	AmountCents     uint32
	AppAccountToken sql.NullString
	IdempotencyKey  sql.NullString
	CreatedAt       time.Time
}

// 会员与支付（T25）。用户发起的查询都带归属条件；支付回调没有登录用户，按全局唯一的订单号定位（验签之后）。
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOrder,
		arg.OrderNo,
		arg.OwnerUserID,
		arg.Tier,
		arg.Channel,
		arg.AmountCents,
		arg.AppAccountToken,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertRefund = `-- name: InsertRefund :execlastid
INSERT INTO refunds (order_id, refund_no, amount_cents, reason, status, handled_by, handled_at, created_at) VALUES (?, ?, ?, ?, 'done', ?, ?, ?)
`

type InsertRefundParams struct {
	OrderID     uint64
	RefundNo    sql.NullString
	AmountCents sql.NullInt32
	Reason      string
	HandledBy   sql.NullInt64
	HandledAt   sql.NullTime
	CreatedAt   time.Time
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertRefund,
		arg.OrderID,
		arg.RefundNo,
		arg.AmountCents,
		arg.Reason,
		arg.HandledBy,
		arg.HandledAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const markOrderPaid = `-- name: MarkOrderPaid :execrows
UPDATE orders SET status = 'paid', transaction_id = ?, notify_hash = ?, membership_id = ?, paid_at = ? WHERE id = ? AND status = 'created'
`

type MarkOrderPaidParams struct {
	TransactionID sql.NullString
	NotifyHash    sql.NullString
	MembershipID  sql.NullInt64
	PaidAt        sql.NullTime
	ID            uint64
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOrderPaid,
		arg.TransactionID,
		arg.NotifyHash,
		arg.MembershipID,
		arg.PaidAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOrderRefunded = `-- name: MarkOrderRefunded :execrows
UPDATE orders SET status = 'refunded' WHERE id = ? AND status = 'paid'
`

func (q *Queries) MarkOrderRefunded(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOrderRefunded, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeMembership = `-- name: RevokeMembership :exec
UPDATE memberships SET revoked_at = ? WHERE id = ? AND owner_user_id = ? AND revoked_at IS NULL
`

type RevokeMembershipParams struct {
	RevokedAt   sql.NullTime
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) RevokeMembership(ctx context.Context, arg RevokeMembershipParams) error {
	_, err := q.db.ExecContext(ctx, revokeMembership, arg.RevokedAt, arg.ID, arg.OwnerUserID)
	return err
}
