// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: practice.sql

package dbq

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"peetraining-server/internal/dbtypes"
)

const bumpQuestionReport = `-- name: BumpQuestionReport :exec
UPDATE questions SET report_count = report_count + 1,
  status = IF(source = 'ai_generated' AND report_count >= ?, 'offline', status)
WHERE id = ? AND owner_user_id = ?
`

type BumpQuestionReportParams struct {
	ReportCount uint32
	ID          uint64
	OwnerUserID sql.NullInt64
}

// 每次报错计数；AI 出的题累计 3 次自动下线（PRD 4.3）。SET 从左到右执行，判断时 report_count 已经加过 1。
func (q *Queries) BumpQuestionReport(ctx context.Context, arg BumpQuestionReportParams) error {
	_, err := q.db.ExecContext(ctx, bumpQuestionReport, arg.ReportCount, arg.ID, arg.OwnerUserID)
	return err
}

const countAttempts = `-- name: CountAttempts :one
SELECT COUNT(*) FROM attempts WHERE owner_user_id = ? AND question_id = ?
`

type CountAttemptsParams struct {
	OwnerUserID uint64
	QuestionID  uint64
}

func (q *Queries) CountAttempts(ctx context.Context, arg CountAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttempts, arg.OwnerUserID, arg.QuestionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReciteDue = `-- name: CountReciteDue :one
SELECT COUNT(*) FROM knowledge_points k
LEFT JOIN kp_mastery m ON m.kp_id = k.id AND m.owner_user_id = k.owner_user_id
WHERE k.bank_id = ? AND k.owner_user_id = ? AND k.level = 'point'
  AND (m.recite_next_review_on IS NULL OR m.recite_next_review_on <= ?)
`

type CountReciteDueParams struct {
	BankID             uint64
	OwnerUserID        sql.NullInt64
	ReciteNextReviewOn sql.NullTime
}

// 待背诵：知识点有采分关键词，从没背过或背诵复习日已到。
func (q *Queries) CountReciteDue(ctx context.Context, arg CountReciteDueParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReciteDue, arg.BankID, arg.OwnerUserID, arg.ReciteNextReviewOn)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsSince = `-- name: CountSessionsSince :one
SELECT COUNT(*) FROM practice_sessions
WHERE owner_user_id = ? AND subject_id = ? AND kind = ? AND status = 'finished' AND started_at >= ?
`

type CountSessionsSinceParams struct {
	OwnerUserID uint64
	SubjectID   sql.NullInt64
	Kind        PracticeSessionsKind
	StartedAt   time.Time
}

func (q *Queries) CountSessionsSince(ctx context.Context, arg CountSessionsSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsSince,
		arg.OwnerUserID,
		arg.SubjectID,
		arg.Kind,
		arg.StartedAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishPracticeSession = `-- name: FinishPracticeSession :exec
UPDATE practice_sessions SET status = 'finished', summary = ?, finished_at = ? WHERE id = ? AND owner_user_id = ?
`

type FinishPracticeSessionParams struct {
	Summary     dbtypes.NullJSON
	FinishedAt  sql.NullTime
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) FinishPracticeSession(ctx context.Context, arg FinishPracticeSessionParams) error {
	_, err := q.db.ExecContext(ctx, finishPracticeSession,
		arg.Summary,
		arg.FinishedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}

const getAttemptByKey = `-- name: GetAttemptByKey :one
SELECT id, owner_user_id, question_id, practice_session_id, paper_session_id, answer_mode, selected, answer_text, photo_keys, is_correct, score, full_score, revealed_answer, self_assess, duration_seconds, timed, offline, verified_at, idempotency_key, answered_at, created_at FROM attempts WHERE owner_user_id = ? AND idempotency_key = ?
`

type GetAttemptByKeyParams struct {
	OwnerUserID    uint64
	IdempotencyKey sql.NullString
}

func (q *Queries) GetAttemptByKey(ctx context.Context, arg GetAttemptByKeyParams) (Attempt, error) {
	row := q.db.QueryRowContext(ctx, getAttemptByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.QuestionID,
		&i.PracticeSessionID,
		&i.PaperSessionID,
		&i.AnswerMode,
		&i.Selected,
		&i.AnswerText,
		&i.PhotoKeys,
		&i.IsCorrect,
		&i.Score,
		&i.FullScore,
		&i.RevealedAnswer,
		&i.SelfAssess,
		&i.DurationSeconds,
		&i.Timed,
		&i.Offline,
		&i.VerifiedAt,
		&i.IdempotencyKey,
		&i.AnsweredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getKPMasteryForUpdate = `-- name: GetKPMasteryForUpdate :one
SELECT owner_user_id, kp_id, m, state, viewed, answered, last_self_assess, last_self_assess_at, correct_dates, next_review_on, interval_step, recite_next_review_on, recite_interval_step, decay_applied_on, updated_at FROM kp_mastery WHERE owner_user_id = ? AND kp_id = ? FOR UPDATE
`

type GetKPMasteryForUpdateParams struct {
	OwnerUserID uint64
	KpID        uint64
}

func (q *Queries) GetKPMasteryForUpdate(ctx context.Context, arg GetKPMasteryForUpdateParams) (KpMastery, error) {
	row := q.db.QueryRowContext(ctx, getKPMasteryForUpdate, arg.OwnerUserID, arg.KpID)
	var i KpMastery
	err := row.Scan(
		&i.OwnerUserID,
		&i.KpID,
		&i.M,
		&i.State,
		&i.Viewed,
		&i.Answered,
		&i.LastSelfAssess,
		&i.LastSelfAssessAt,
		&i.CorrectDates,
		&i.NextReviewOn,
		&i.IntervalStep,
		&i.ReciteNextReviewOn,
		&i.ReciteIntervalStep,
		&i.DecayAppliedOn,
		&i.UpdatedAt,
	)
	return i, err
}

const getPracticeSession = `-- name: GetPracticeSession :one
SELECT id, owner_user_id, subject_id, kind, title, config, question_ids, cursor_index, status, summary, started_at, finished_at FROM practice_sessions WHERE id = ? AND owner_user_id = ?
`

type GetPracticeSessionParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetPracticeSession(ctx context.Context, arg GetPracticeSessionParams) (PracticeSession, error) {
	row := q.db.QueryRowContext(ctx, getPracticeSession, arg.ID, arg.OwnerUserID)
	var i PracticeSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.Kind,
		&i.Title,
		&i.Config,
		&i.QuestionIds,
		&i.CursorIndex,
		&i.Status,
		&i.Summary,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getPracticeSessionForUpdate = `-- name: GetPracticeSessionForUpdate :one
SELECT id, owner_user_id, subject_id, kind, title, config, question_ids, cursor_index, status, summary, started_at, finished_at FROM practice_sessions WHERE id = ? AND owner_user_id = ? FOR UPDATE
`

type GetPracticeSessionForUpdateParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) GetPracticeSessionForUpdate(ctx context.Context, arg GetPracticeSessionForUpdateParams) (PracticeSession, error) {
	row := q.db.QueryRowContext(ctx, getPracticeSessionForUpdate, arg.ID, arg.OwnerUserID)
	var i PracticeSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.Kind,
		&i.Title,
		&i.Config,
		&i.QuestionIds,
		&i.CursorIndex,
		&i.Status,
		&i.Summary,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getQuestionStatus = `-- name: GetQuestionStatus :one
SELECT status, report_count, source FROM questions WHERE id = ? AND owner_user_id = ?
`

type GetQuestionStatusParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

type GetQuestionStatusRow struct {
	Status      QuestionsStatus
	ReportCount uint32
	Source      QuestionsSource
}

func (q *Queries) GetQuestionStatus(ctx context.Context, arg GetQuestionStatusParams) (GetQuestionStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestionStatus, arg.ID, arg.OwnerUserID)
	var i GetQuestionStatusRow
	err := row.Scan(&i.Status, &i.ReportCount, &i.Source)
	return i, err
}

const getWrongBookForUpdate = `-- name: GetWrongBookForUpdate :one
SELECT owner_user_id, question_id, status, added_reason, last_loss_type, wrong_count, last_score_rate, correct_dates, next_review_on, added_at, removed_at FROM wrong_book WHERE owner_user_id = ? AND question_id = ? FOR UPDATE
`

type GetWrongBookForUpdateParams struct {
	OwnerUserID uint64
	QuestionID  uint64
}

func (q *Queries) GetWrongBookForUpdate(ctx context.Context, arg GetWrongBookForUpdateParams) (WrongBook, error) {
	row := q.db.QueryRowContext(ctx, getWrongBookForUpdate, arg.OwnerUserID, arg.QuestionID)
	var i WrongBook
	err := row.Scan(
		&i.OwnerUserID,
		&i.QuestionID,
		&i.Status,
		&i.AddedReason,
		&i.LastLossType,
		&i.WrongCount,
		&i.LastScoreRate,
		&i.CorrectDates,
		&i.NextReviewOn,
		&i.AddedAt,
		&i.RemovedAt,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :execlastid
INSERT INTO attempts (owner_user_id, question_id, practice_session_id, answer_mode, selected, answer_text, is_correct, score, full_score,
  revealed_answer, self_assess, duration_seconds, offline, verified_at, idempotency_key, answered_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAttemptParams struct {
	OwnerUserID       uint64
	QuestionID        uint64
	PracticeSessionID sql.NullInt64
	AnswerMode        AttemptsAnswerMode
	Selected          dbtypes.NullJSON
	AnswerText        sql.NullString
	IsCorrect         sql.NullBool
	Score             sql.NullString
	FullScore         sql.NullString
	RevealedAnswer    bool
	SelfAssess        NullAttemptsSelfAssess
	DurationSeconds   uint32
	Offline           bool
	VerifiedAt        sql.NullTime
	IdempotencyKey    sql.NullString
	AnsweredAt        time.Time
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAttempt,
		arg.OwnerUserID,
		arg.QuestionID,
		arg.PracticeSessionID,
		arg.AnswerMode,
		arg.Selected,
		arg.AnswerText,
		arg.IsCorrect,
		arg.Score,
		arg.FullScore,
		arg.RevealedAnswer,
		arg.SelfAssess,
		arg.DurationSeconds,
		arg.Offline,
		arg.VerifiedAt,
		arg.IdempotencyKey,
		arg.AnsweredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertPracticeSession = `-- name: InsertPracticeSession :execlastid
INSERT INTO practice_sessions (owner_user_id, subject_id, kind, title, config, question_ids) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPracticeSessionParams struct {
	OwnerUserID uint64
	SubjectID   sql.NullInt64
	Kind        PracticeSessionsKind
	Title       string
	Config      dbtypes.NullJSON
	QuestionIds json.RawMessage
}

func (q *Queries) InsertPracticeSession(ctx context.Context, arg InsertPracticeSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertPracticeSession,
		arg.OwnerUserID,
		arg.SubjectID,
		arg.Kind,
		arg.Title,
		arg.Config,
		arg.QuestionIds,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const latestInProgressSession = `-- name: LatestInProgressSession :one
SELECT id, owner_user_id, subject_id, kind, title, config, question_ids, cursor_index, status, summary, started_at, finished_at FROM practice_sessions
WHERE owner_user_id = ? AND subject_id = ? AND status = 'in_progress'
ORDER BY started_at DESC, id DESC LIMIT 1
`

type LatestInProgressSessionParams struct {
	OwnerUserID uint64
	SubjectID   sql.NullInt64
}

func (q *Queries) LatestInProgressSession(ctx context.Context, arg LatestInProgressSessionParams) (PracticeSession, error) {
	row := q.db.QueryRowContext(ctx, latestInProgressSession, arg.OwnerUserID, arg.SubjectID)
	var i PracticeSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SubjectID,
		&i.Kind,
		&i.Title,
		&i.Config,
		&i.QuestionIds,
		&i.CursorIndex,
		&i.Status,
		&i.Summary,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listPracticePool = `-- name: ListPracticePool :many

SELECT q.id, q.qtype, q.source, q.exam_year,
  CAST(COALESCE((SELECT qk.kp_id FROM question_kps qk WHERE qk.question_id = q.id ORDER BY qk.is_primary DESC, qk.kp_id LIMIT 1), 0) AS UNSIGNED) AS primary_kp,
  CAST(COALESCE((SELECT COUNT(*) FROM attempts a WHERE a.question_id = q.id AND a.owner_user_id = q.owner_user_id), 0) AS UNSIGNED) AS attempt_count
FROM questions q
WHERE q.bank_id = ? AND q.owner_user_id = ? AND q.status = 'active'
ORDER BY q.id
`

type ListPracticePoolParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListPracticePoolRow struct {
	ID           uint64
	Qtype        QuestionsQtype
	Source       QuestionsSource
	ExamYear     sql.NullInt16
	PrimaryKp    int64
	AttemptCount int64
}

// 练习、作答、错题本（T17）。每条查询都带归属条件。
// 选题池：题库里在用的题、主知识点、错题本状态。
func (q *Queries) ListPracticePool(ctx context.Context, arg ListPracticePoolParams) ([]ListPracticePoolRow, error) {
	rows, err := q.db.QueryContext(ctx, listPracticePool, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPracticePoolRow{}
	for rows.Next() {
		var i ListPracticePoolRow
		if err := rows.Scan(
			&i.ID,
			&i.Qtype,
			&i.Source,
			&i.ExamYear,
			&i.PrimaryKp,
			&i.AttemptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionAttempts = `-- name: ListSessionAttempts :many
SELECT a.id, a.question_id, a.is_correct, a.revealed_answer, a.self_assess, a.selected, a.duration_seconds, q.qtype, q.source
FROM attempts a JOIN questions q ON q.id = a.question_id
WHERE a.practice_session_id = ? AND a.owner_user_id = ?
ORDER BY a.id
`

type ListSessionAttemptsParams struct {
	PracticeSessionID sql.NullInt64
	OwnerUserID       uint64
}

type ListSessionAttemptsRow struct {
	ID              uint64
	QuestionID      uint64
	IsCorrect       sql.NullBool
	RevealedAnswer  bool
	SelfAssess      NullAttemptsSelfAssess
	Selected        dbtypes.NullJSON
	DurationSeconds uint32
	Qtype           QuestionsQtype
	Source          QuestionsSource
}

func (q *Queries) ListSessionAttempts(ctx context.Context, arg ListSessionAttemptsParams) ([]ListSessionAttemptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionAttempts, arg.PracticeSessionID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionAttemptsRow{}
	for rows.Next() {
		var i ListSessionAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.IsCorrect,
			&i.RevealedAnswer,
			&i.SelfAssess,
			&i.Selected,
			&i.DurationSeconds,
			&i.Qtype,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWrongBook = `-- name: ListWrongBook :many
SELECT w.question_id, w.status, w.added_reason, w.last_loss_type, w.wrong_count, w.last_score_rate, w.next_review_on, w.added_at, w.removed_at,
  q.qtype, q.stem, q.source, q.exam_year,
  CAST(COALESCE((SELECT qk.kp_id FROM question_kps qk WHERE qk.question_id = q.id ORDER BY qk.is_primary DESC, qk.kp_id LIMIT 1), 0) AS UNSIGNED) AS kp_id,
  CAST(COALESCE((SELECT k.name FROM question_kps qk JOIN knowledge_points k ON k.id = qk.kp_id WHERE qk.question_id = q.id ORDER BY qk.is_primary DESC, qk.kp_id LIMIT 1), '') AS CHAR) AS kp_name
FROM wrong_book w JOIN questions q ON q.id = w.question_id
WHERE w.owner_user_id = ? AND q.bank_id = ? AND q.status = 'active'
ORDER BY w.next_review_on IS NULL, w.next_review_on, w.added_at
`

type ListWrongBookParams struct {
	OwnerUserID uint64
	BankID      uint64
}

type ListWrongBookRow struct {
	QuestionID    uint64
	Status        WrongBookStatus
	AddedReason   WrongBookAddedReason
	LastLossType  NullWrongBookLastLossType
	WrongCount    uint32
	LastScoreRate sql.NullString
	NextReviewOn  sql.NullTime
	AddedAt       time.Time
	RemovedAt     sql.NullTime
	Qtype         QuestionsQtype
	Stem          string
	Source        QuestionsSource
	ExamYear      sql.NullInt16
	KpID          int64
	KpName        interface{}
}

func (q *Queries) ListWrongBook(ctx context.Context, arg ListWrongBookParams) ([]ListWrongBookRow, error) {
	rows, err := q.db.QueryContext(ctx, listWrongBook, arg.OwnerUserID, arg.BankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWrongBookRow{}
	for rows.Next() {
		var i ListWrongBookRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.Status,
			&i.AddedReason,
			&i.LastLossType,
			&i.WrongCount,
			&i.LastScoreRate,
			&i.NextReviewOn,
			&i.AddedAt,
			&i.RemovedAt,
			&i.Qtype,
			&i.Stem,
			&i.Source,
			&i.ExamYear,
			&i.KpID,
			&i.KpName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const qTypeCounts = `-- name: QTypeCounts :many
SELECT qtype, COUNT(*) AS n FROM questions WHERE bank_id = ? AND owner_user_id = ? AND status = 'active' GROUP BY qtype
`

type QTypeCountsParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type QTypeCountsRow struct {
	Qtype QuestionsQtype
	N     int64
}

func (q *Queries) QTypeCounts(ctx context.Context, arg QTypeCountsParams) ([]QTypeCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, qTypeCounts, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QTypeCountsRow{}
	for rows.Next() {
		var i QTypeCountsRow
		if err := rows.Scan(&i.Qtype, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWrongBook = `-- name: RemoveWrongBook :execrows
UPDATE wrong_book SET status = 'removed', removed_at = ? WHERE owner_user_id = ? AND question_id = ? AND status = 'active'
`

type RemoveWrongBookParams struct {
	RemovedAt   sql.NullTime
	OwnerUserID uint64
	QuestionID  uint64
}

func (q *Queries) RemoveWrongBook(ctx context.Context, arg RemoveWrongBookParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeWrongBook, arg.RemovedAt, arg.OwnerUserID, arg.QuestionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setDailyPlanSession = `-- name: SetDailyPlanSession :exec
UPDATE daily_plans SET practice_session_id = ? WHERE owner_user_id = ? AND plan_date = ?
`

type SetDailyPlanSessionParams struct {
	PracticeSessionID sql.NullInt64
	OwnerUserID       uint64
	PlanDate          time.Time
}

func (q *Queries) SetDailyPlanSession(ctx context.Context, arg SetDailyPlanSessionParams) error {
	_, err := q.db.ExecContext(ctx, setDailyPlanSession, arg.PracticeSessionID, arg.OwnerUserID, arg.PlanDate)
	return err
}

const setQuestionGeneratedFrom = `-- name: SetQuestionGeneratedFrom :exec
UPDATE questions SET generated_from_kp_id = ?, answer_origin = 'ai_generated' WHERE id = ? AND owner_user_id = ?
`

type SetQuestionGeneratedFromParams struct {
	GeneratedFromKpID sql.NullInt64
	ID                uint64
	OwnerUserID       sql.NullInt64
}

func (q *Queries) SetQuestionGeneratedFrom(ctx context.Context, arg SetQuestionGeneratedFromParams) error {
	_, err := q.db.ExecContext(ctx, setQuestionGeneratedFrom, arg.GeneratedFromKpID, arg.ID, arg.OwnerUserID)
	return err
}

const setSessionCursor = `-- name: SetSessionCursor :exec
UPDATE practice_sessions SET cursor_index = ? WHERE id = ? AND owner_user_id = ?
`

type SetSessionCursorParams struct {
	CursorIndex uint32
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) SetSessionCursor(ctx context.Context, arg SetSessionCursorParams) error {
	_, err := q.db.ExecContext(ctx, setSessionCursor, arg.CursorIndex, arg.ID, arg.OwnerUserID)
	return err
}

const upsertKPMasteryAnswer = `-- name: UpsertKPMasteryAnswer :exec
INSERT INTO kp_mastery (owner_user_id, kp_id, m, state, answered, correct_dates, next_review_on, interval_step, decay_applied_on)
VALUES (?, ?, ?, ?, 1, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE m = VALUES(m), state = VALUES(state), answered = 1, correct_dates = VALUES(correct_dates),
  next_review_on = VALUES(next_review_on), interval_step = VALUES(interval_step), decay_applied_on = VALUES(decay_applied_on)
`

type UpsertKPMasteryAnswerParams struct {
	OwnerUserID    uint64
	KpID           uint64
	M              string
	State          KpMasteryState
	CorrectDates   dbtypes.NullJSON
	NextReviewOn   sql.NullTime
	IntervalStep   uint8
	DecayAppliedOn sql.NullTime
}

// 作答验证后的掌握分、状态、答对日期与复习排期（PRD 11.1–11.3）。
func (q *Queries) UpsertKPMasteryAnswer(ctx context.Context, arg UpsertKPMasteryAnswerParams) error {
	_, err := q.db.ExecContext(ctx, upsertKPMasteryAnswer,
		arg.OwnerUserID,
		arg.KpID,
		arg.M,
		arg.State,
		arg.CorrectDates,
		arg.NextReviewOn,
		arg.IntervalStep,
		arg.DecayAppliedOn,
	)
	return err
}

const upsertQuestionReport = `-- name: UpsertQuestionReport :exec
INSERT INTO question_reports (question_id, owner_user_id, reason) VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE reason = VALUES(reason), created_at = CURRENT_TIMESTAMP(3)
`

type UpsertQuestionReportParams struct {
	QuestionID  uint64
	OwnerUserID uint64
	Reason      sql.NullString
}

func (q *Queries) UpsertQuestionReport(ctx context.Context, arg UpsertQuestionReportParams) error {
	_, err := q.db.ExecContext(ctx, upsertQuestionReport, arg.QuestionID, arg.OwnerUserID, arg.Reason)
	return err
}

const upsertWrongBook = `-- name: UpsertWrongBook :exec
INSERT INTO wrong_book (owner_user_id, question_id, status, added_reason, last_loss_type, wrong_count, last_score_rate, correct_dates, next_review_on, added_at, removed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE status = VALUES(status), added_reason = VALUES(added_reason), last_loss_type = VALUES(last_loss_type),
  wrong_count = VALUES(wrong_count), last_score_rate = VALUES(last_score_rate), correct_dates = VALUES(correct_dates),
  next_review_on = VALUES(next_review_on), added_at = VALUES(added_at), removed_at = VALUES(removed_at)
`

type UpsertWrongBookParams struct {
	OwnerUserID   uint64
	QuestionID    uint64
	Status        WrongBookStatus
	AddedReason   WrongBookAddedReason
	LastLossType  NullWrongBookLastLossType
	WrongCount    uint32
	LastScoreRate sql.NullString
	CorrectDates  dbtypes.NullJSON
	NextReviewOn  sql.NullTime
	AddedAt       time.Time
	RemovedAt     sql.NullTime
}

func (q *Queries) UpsertWrongBook(ctx context.Context, arg UpsertWrongBookParams) error {
	_, err := q.db.ExecContext(ctx, upsertWrongBook,
		arg.OwnerUserID,
		arg.QuestionID,
		arg.Status,
		arg.AddedReason,
		arg.LastLossType,
		arg.WrongCount,
		arg.LastScoreRate,
		arg.CorrectDates,
		arg.NextReviewOn,
		arg.AddedAt,
		arg.RemovedAt,
	)
	return err
}
