// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package dbq

import (
	"context"
	"database/sql"
	"time"

	"peetraining-server/internal/dbtypes"
)

const countSubjects = `-- name: CountSubjects :one
SELECT COUNT(*) FROM subjects WHERE owner_user_id = ?
`

func (q *Queries) CountSubjects(ctx context.Context, ownerUserID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubjects, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubject = `-- name: CreateSubject :execlastid
INSERT INTO subjects (owner_user_id, name, code, full_score, target_score, sort_order) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSubjectParams struct {
	OwnerUserID uint64
	Name        string
	Code        sql.NullString
	FullScore   uint16
	TargetScore sql.NullInt16
	SortOrder   uint8
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSubject,
		arg.OwnerUserID,
		arg.Name,
		arg.Code,
		arg.FullScore,
		arg.TargetScore,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createUserBank = `-- name: CreateUserBank :execlastid
INSERT INTO banks (source, owner_user_id, subject_id, title, subject_code) VALUES ('user', ?, ?, ?, ?)
`

type CreateUserBankParams struct {
	OwnerUserID sql.NullInt64
	SubjectID   sql.NullInt64
	Title       string
	SubjectCode sql.NullString
}

func (q *Queries) CreateUserBank(ctx context.Context, arg CreateUserBankParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUserBank,
		arg.OwnerUserID,
		arg.SubjectID,
		arg.Title,
		arg.SubjectCode,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteSubject = `-- name: DeleteSubject :execrows
DELETE FROM subjects WHERE id = ? AND owner_user_id = ?
`

type DeleteSubjectParams struct {
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) DeleteSubject(ctx context.Context, arg DeleteSubjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubject, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSubjectExports = `-- name: DeleteSubjectExports :exec
DELETE FROM export_jobs WHERE owner_user_id = ? AND subject_id = ?
`

type DeleteSubjectExportsParams struct {
	OwnerUserID uint64
	SubjectID   uint64
}

func (q *Queries) DeleteSubjectExports(ctx context.Context, arg DeleteSubjectExportsParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubjectExports, arg.OwnerUserID, arg.SubjectID)
	return err
}

const deleteSubjectPracticeSessions = `-- name: DeleteSubjectPracticeSessions :exec
DELETE FROM practice_sessions WHERE owner_user_id = ? AND subject_id = ?
`

type DeleteSubjectPracticeSessionsParams struct {
	OwnerUserID uint64
	SubjectID   sql.NullInt64
}

func (q *Queries) DeleteSubjectPracticeSessions(ctx context.Context, arg DeleteSubjectPracticeSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubjectPracticeSessions, arg.OwnerUserID, arg.SubjectID)
	return err
}

const deleteSubjectSessions = `-- name: DeleteSubjectSessions :exec
DELETE FROM paper_sessions WHERE owner_user_id = ? AND subject_id = ?
`

type DeleteSubjectSessionsParams struct {
	OwnerUserID uint64
	SubjectID   uint64
}

func (q *Queries) DeleteSubjectSessions(ctx context.Context, arg DeleteSubjectSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubjectSessions, arg.OwnerUserID, arg.SubjectID)
	return err
}

const getExamDate = `-- name: GetExamDate :one
SELECT exam_year, label, first_exam_start, first_exam_end, subject_exam_date, updated_at FROM exam_dates WHERE exam_year = ?
`

func (q *Queries) GetExamDate(ctx context.Context, examYear uint16) (ExamDate, error) {
	row := q.db.QueryRowContext(ctx, getExamDate, examYear)
	var i ExamDate
	err := row.Scan(
		&i.ExamYear,
		&i.Label,
		&i.FirstExamStart,
		&i.FirstExamEnd,
		&i.SubjectExamDate,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudyProfile = `-- name: GetStudyProfile :one
SELECT user_id, exam_year, stage, stage_manual, pending_stage, daily_minutes, pending_daily_minutes, pending_effective_on, reminder_times, target_school_major, essay_weekly_goal, mock_time_reminders, notify_daily, notify_review_due, notify_task_done, stage_prompted, created_at, updated_at FROM study_profiles WHERE user_id = ?
`

func (q *Queries) GetStudyProfile(ctx context.Context, userID uint64) (StudyProfile, error) {
	row := q.db.QueryRowContext(ctx, getStudyProfile, userID)
	var i StudyProfile
	err := row.Scan(
		&i.UserID,
		&i.ExamYear,
		&i.Stage,
		&i.StageManual,
		&i.PendingStage,
		&i.DailyMinutes,
		&i.PendingDailyMinutes,
		&i.PendingEffectiveOn,
		&i.ReminderTimes,
		&i.TargetSchoolMajor,
		&i.EssayWeeklyGoal,
		&i.MockTimeReminders,
		&i.NotifyDaily,
		&i.NotifyReviewDue,
		&i.NotifyTaskDone,
		&i.StagePrompted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubject = `-- name: GetSubject :one
SELECT s.id, s.owner_user_id, s.name, s.code, s.full_score, s.target_score, s.is_essay, s.essay_set_by, s.sort_order, s.created_at, s.updated_at, b.id AS bank_id FROM subjects s JOIN banks b ON b.subject_id = s.id
WHERE s.id = ? AND s.owner_user_id = ?
`

type GetSubjectParams struct {
	ID          uint64
	OwnerUserID uint64
}

type GetSubjectRow struct {
	ID          uint64
	OwnerUserID uint64
	Name        string
	Code        sql.NullString
	FullScore   uint16
	TargetScore sql.NullInt16
	IsEssay     bool
	EssaySetBy  NullSubjectsEssaySetBy
	SortOrder   uint8
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BankID      uint64
}

func (q *Queries) GetSubject(ctx context.Context, arg GetSubjectParams) (GetSubjectRow, error) {
	row := q.db.QueryRowContext(ctx, getSubject, arg.ID, arg.OwnerUserID)
	var i GetSubjectRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Code,
		&i.FullScore,
		&i.TargetScore,
		&i.IsEssay,
		&i.EssaySetBy,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankID,
	)
	return i, err
}

const insertStudyProfile = `-- name: InsertStudyProfile :exec
INSERT INTO study_profiles (user_id, exam_year, stage, stage_manual, daily_minutes, reminder_times, target_school_major,
  essay_weekly_goal, mock_time_reminders, notify_daily, notify_review_due, notify_task_done)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStudyProfileParams struct {
	UserID            uint64
	ExamYear          uint16
	Stage             StudyProfilesStage
	StageManual       bool
	DailyMinutes      uint16
	ReminderTimes     dbtypes.NullJSON
	TargetSchoolMajor sql.NullString
	EssayWeeklyGoal   uint8
	MockTimeReminders bool
	NotifyDaily       bool
	NotifyReviewDue   bool
	NotifyTaskDone    bool
}

func (q *Queries) InsertStudyProfile(ctx context.Context, arg InsertStudyProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertStudyProfile,
		arg.UserID,
		arg.ExamYear,
		arg.Stage,
		arg.StageManual,
		arg.DailyMinutes,
		arg.ReminderTimes,
		arg.TargetSchoolMajor,
		arg.EssayWeeklyGoal,
		arg.MockTimeReminders,
		arg.NotifyDaily,
		arg.NotifyReviewDue,
		arg.NotifyTaskDone,
	)
	return err
}

const listExamDatesFrom = `-- name: ListExamDatesFrom :many

SELECT exam_year, label, first_exam_start, first_exam_end, subject_exam_date, updated_at FROM exam_dates WHERE subject_exam_date >= ? ORDER BY exam_year
`

// 备考档案与专业课（T07）。每条查询都带 owner_user_id / user_id 归属条件。
func (q *Queries) ListExamDatesFrom(ctx context.Context, subjectExamDate time.Time) ([]ExamDate, error) {
	rows, err := q.db.QueryContext(ctx, listExamDatesFrom, subjectExamDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamDate{}
	for rows.Next() {
		var i ExamDate
		if err := rows.Scan(
			&i.ExamYear,
			&i.Label,
			&i.FirstExamStart,
			&i.FirstExamEnd,
			&i.SubjectExamDate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT s.id, s.owner_user_id, s.name, s.code, s.full_score, s.target_score, s.is_essay, s.essay_set_by, s.sort_order, s.created_at, s.updated_at, b.id AS bank_id,
  (SELECT COUNT(*) FROM questions q WHERE q.bank_id = b.id AND q.status = 'active') AS question_count,
  (SELECT COUNT(*) FROM knowledge_points k WHERE k.bank_id = b.id AND k.level = 'point') AS kp_count,
  (SELECT COUNT(*) FROM materials m WHERE m.bank_id = b.id) AS material_count
FROM subjects s JOIN banks b ON b.subject_id = s.id
WHERE s.owner_user_id = ?
ORDER BY s.sort_order, s.id
`

type ListSubjectsRow struct {
	ID            uint64
	OwnerUserID   uint64
	Name          string
	Code          sql.NullString
	FullScore     uint16
	TargetScore   sql.NullInt16
	IsEssay       bool
	EssaySetBy    NullSubjectsEssaySetBy
	SortOrder     uint8
	CreatedAt     time.Time
	UpdatedAt     time.Time
	BankID        uint64
	QuestionCount int64
	KpCount       int64
	MaterialCount int64
}

func (q *Queries) ListSubjects(ctx context.Context, ownerUserID uint64) ([]ListSubjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubjects, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectsRow{}
	for rows.Next() {
		var i ListSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Code,
			&i.FullScore,
			&i.TargetScore,
			&i.IsEssay,
			&i.EssaySetBy,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BankID,
			&i.QuestionCount,
			&i.KpCount,
			&i.MaterialCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankForSubject = `-- name: UpdateBankForSubject :exec
UPDATE banks SET title = ?, subject_code = ? WHERE subject_id = ? AND owner_user_id = ?
`

type UpdateBankForSubjectParams struct {
	Title       string
	SubjectCode sql.NullString
	SubjectID   sql.NullInt64
	OwnerUserID sql.NullInt64
}

func (q *Queries) UpdateBankForSubject(ctx context.Context, arg UpdateBankForSubjectParams) error {
	_, err := q.db.ExecContext(ctx, updateBankForSubject,
		arg.Title,
		arg.SubjectCode,
		arg.SubjectID,
		arg.OwnerUserID,
	)
	return err
}

const updateStudyProfile = `-- name: UpdateStudyProfile :exec
UPDATE study_profiles SET
  exam_year = ?, stage = ?, stage_manual = ?, daily_minutes = ?,
  pending_stage = ?, pending_daily_minutes = ?, pending_effective_on = ?,
  reminder_times = ?, target_school_major = ?, essay_weekly_goal = ?, mock_time_reminders = ?,
  notify_daily = ?, notify_review_due = ?, notify_task_done = ?
WHERE user_id = ?
`

type UpdateStudyProfileParams struct {
	ExamYear            uint16
	Stage               StudyProfilesStage
	StageManual         bool
	DailyMinutes        uint16
	PendingStage        NullStudyProfilesPendingStage
	PendingDailyMinutes sql.NullInt16
	PendingEffectiveOn  sql.NullTime
	ReminderTimes       dbtypes.NullJSON
	TargetSchoolMajor   sql.NullString
	EssayWeeklyGoal     uint8
	MockTimeReminders   bool
	NotifyDaily         bool
	NotifyReviewDue     bool
	NotifyTaskDone      bool
	UserID              uint64
}

func (q *Queries) UpdateStudyProfile(ctx context.Context, arg UpdateStudyProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateStudyProfile,
		arg.ExamYear,
		arg.Stage,
		arg.StageManual,
		arg.DailyMinutes,
		arg.PendingStage,
		arg.PendingDailyMinutes,
		arg.PendingEffectiveOn,
		arg.ReminderTimes,
		arg.TargetSchoolMajor,
		arg.EssayWeeklyGoal,
		arg.MockTimeReminders,
		arg.NotifyDaily,
		arg.NotifyReviewDue,
		arg.NotifyTaskDone,
		arg.UserID,
	)
	return err
}

const updateSubject = `-- name: UpdateSubject :exec
UPDATE subjects SET name = ?, code = ?, full_score = ?, target_score = ?, is_essay = ?, essay_set_by = ?
WHERE id = ? AND owner_user_id = ?
`

type UpdateSubjectParams struct {
	Name        string
	Code        sql.NullString
	FullScore   uint16
	TargetScore sql.NullInt16
	IsEssay     bool
	EssaySetBy  NullSubjectsEssaySetBy
	ID          uint64
	OwnerUserID uint64
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) error {
	_, err := q.db.ExecContext(ctx, updateSubject,
		arg.Name,
		arg.Code,
		arg.FullScore,
		arg.TargetScore,
		arg.IsEssay,
		arg.EssaySetBy,
		arg.ID,
		arg.OwnerUserID,
	)
	return err
}
