// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"
)

type Querier interface {
	// 用户与刷新令牌。规矩：查询用户内容一律带 owner_user_id 条件（CLAUDE.md 必须遵守第 4 条）。
	GetUserByID(ctx context.Context, id uint64) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
}

var _ Querier = (*Queries)(nil)
