// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quota.sql

package dbq

import (
	"context"
	"database/sql"
)

const ensureQuotaCounter = `-- name: EnsureQuotaCounter :exec

INSERT IGNORE INTO quota_counters (owner_user_id, quota_type, period_key) VALUES (?, ?, ?)
`

type EnsureQuotaCounterParams struct {
	OwnerUserID uint64
	QuotaType   QuotaCountersQuotaType
	PeriodKey   string
}

// 额度计数与流水（T08，PRD 13.1）。扣减时先锁计数行，防止并发超额；流水的幂等键防止重复扣。
func (q *Queries) EnsureQuotaCounter(ctx context.Context, arg EnsureQuotaCounterParams) error {
	_, err := q.db.ExecContext(ctx, ensureQuotaCounter, arg.OwnerUserID, arg.QuotaType, arg.PeriodKey)
	return err
}

const getQuotaCounter = `-- name: GetQuotaCounter :one
SELECT owner_user_id, quota_type, period_key, used, reserved, updated_at FROM quota_counters WHERE owner_user_id = ? AND quota_type = ? AND period_key = ?
`

type GetQuotaCounterParams struct {
	OwnerUserID uint64
	QuotaType   QuotaCountersQuotaType
	PeriodKey   string
}

func (q *Queries) GetQuotaCounter(ctx context.Context, arg GetQuotaCounterParams) (QuotaCounter, error) {
	row := q.db.QueryRowContext(ctx, getQuotaCounter, arg.OwnerUserID, arg.QuotaType, arg.PeriodKey)
	var i QuotaCounter
	err := row.Scan(
		&i.OwnerUserID,
		&i.QuotaType,
		&i.PeriodKey,
		&i.Used,
		&i.Reserved,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotaLedgerByKey = `-- name: GetQuotaLedgerByKey :one
SELECT id, owner_user_id, quota_type, period_key, action, amount, ref_type, ref_id, idempotency_key, note, created_at FROM quota_ledger WHERE owner_user_id = ? AND idempotency_key = ?
`

type GetQuotaLedgerByKeyParams struct {
	OwnerUserID    uint64
	IdempotencyKey string
}

func (q *Queries) GetQuotaLedgerByKey(ctx context.Context, arg GetQuotaLedgerByKeyParams) (QuotaLedger, error) {
	row := q.db.QueryRowContext(ctx, getQuotaLedgerByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i QuotaLedger
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.QuotaType,
		&i.PeriodKey,
		&i.Action,
		&i.Amount,
		&i.RefType,
		&i.RefID,
		&i.IdempotencyKey,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuotaLedger = `-- name: InsertQuotaLedger :exec
INSERT INTO quota_ledger (owner_user_id, quota_type, period_key, action, amount, ref_type, ref_id, idempotency_key, note)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertQuotaLedgerParams struct {
	OwnerUserID    uint64
	QuotaType      QuotaLedgerQuotaType
	PeriodKey      string
	Action         QuotaLedgerAction
	Amount         int32
	RefType        sql.NullString
	RefID          sql.NullInt64
	IdempotencyKey string
	Note           sql.NullString
}

func (q *Queries) InsertQuotaLedger(ctx context.Context, arg InsertQuotaLedgerParams) error {
	_, err := q.db.ExecContext(ctx, insertQuotaLedger,
		arg.OwnerUserID,
		arg.QuotaType,
		arg.PeriodKey,
		arg.Action,
		arg.Amount,
		arg.RefType,
		arg.RefID,
		arg.IdempotencyKey,
		arg.Note,
	)
	return err
}

const lockQuotaCounter = `-- name: LockQuotaCounter :one
SELECT owner_user_id, quota_type, period_key, used, reserved, updated_at FROM quota_counters WHERE owner_user_id = ? AND quota_type = ? AND period_key = ? FOR UPDATE
`

type LockQuotaCounterParams struct {
	OwnerUserID uint64
	QuotaType   QuotaCountersQuotaType
	PeriodKey   string
}

func (q *Queries) LockQuotaCounter(ctx context.Context, arg LockQuotaCounterParams) (QuotaCounter, error) {
	row := q.db.QueryRowContext(ctx, lockQuotaCounter, arg.OwnerUserID, arg.QuotaType, arg.PeriodKey)
	var i QuotaCounter
	err := row.Scan(
		&i.OwnerUserID,
		&i.QuotaType,
		&i.PeriodKey,
		&i.Used,
		&i.Reserved,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotaCounter = `-- name: UpdateQuotaCounter :exec
UPDATE quota_counters SET used = ?, reserved = ? WHERE owner_user_id = ? AND quota_type = ? AND period_key = ?
`

type UpdateQuotaCounterParams struct {
	Used        uint32
	Reserved    uint32
	OwnerUserID uint64
	QuotaType   QuotaCountersQuotaType
	PeriodKey   string
}

func (q *Queries) UpdateQuotaCounter(ctx context.Context, arg UpdateQuotaCounterParams) error {
	_, err := q.db.ExecContext(ctx, updateQuotaCounter,
		arg.Used,
		arg.Reserved,
		arg.OwnerUserID,
		arg.QuotaType,
		arg.PeriodKey,
	)
	return err
}
