// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recite.sql

package dbq

import (
	"context"
	"database/sql"
	"time"

	"peetraining-server/internal/dbtypes"
)

const getReciteRecordByKey = `-- name: GetReciteRecordByKey :one
SELECT id, owner_user_id, kp_id, practice_session_id, mode, result, coverage, created_at, idempotency_key FROM recite_records WHERE owner_user_id = ? AND idempotency_key = ?
`

type GetReciteRecordByKeyParams struct {
	OwnerUserID    uint64
	IdempotencyKey sql.NullString
}

func (q *Queries) GetReciteRecordByKey(ctx context.Context, arg GetReciteRecordByKeyParams) (ReciteRecord, error) {
	row := q.db.QueryRowContext(ctx, getReciteRecordByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i ReciteRecord
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.KpID,
		&i.PracticeSessionID,
		&i.Mode,
		&i.Result,
		&i.Coverage,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const insertReciteRecord = `-- name: InsertReciteRecord :execlastid
INSERT INTO recite_records (owner_user_id, kp_id, practice_session_id, mode, result, coverage, idempotency_key, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReciteRecordParams struct {
	OwnerUserID       uint64
	KpID              uint64
	PracticeSessionID sql.NullInt64
	Mode              ReciteRecordsMode
	Result            NullReciteRecordsResult
	Coverage          dbtypes.NullJSON
	IdempotencyKey    sql.NullString
	CreatedAt         time.Time
}

func (q *Queries) InsertReciteRecord(ctx context.Context, arg InsertReciteRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertReciteRecord,
		arg.OwnerUserID,
		arg.KpID,
		arg.PracticeSessionID,
		arg.Mode,
		arg.Result,
		arg.Coverage,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listReciteCandidates = `-- name: ListReciteCandidates :many

SELECT k.id, k.name, k.parent_id, k.original_text, k.source_material_id, k.source_page,
  COALESCE(m.m, 0) AS m, m.recite_next_review_on, COALESCE(m.recite_interval_step, 0) AS recite_interval_step
FROM knowledge_points k
LEFT JOIN kp_mastery m ON m.kp_id = k.id AND m.owner_user_id = k.owner_user_id
WHERE k.bank_id = ? AND k.owner_user_id = ? AND k.level = 'point'
  AND k.original_text IS NOT NULL AND k.original_text <> ''
ORDER BY k.sort_order, k.id
`

type ListReciteCandidatesParams struct {
	BankID      uint64
	OwnerUserID sql.NullInt64
}

type ListReciteCandidatesRow struct {
	ID                 uint64
	Name               string
	ParentID           sql.NullInt64
	OriginalText       sql.NullString
	SourceMaterialID   sql.NullInt64
	SourcePage         sql.NullInt32
	M                  string
	ReciteNextReviewOn sql.NullTime
	ReciteIntervalStep uint8
}

// 背诵（T20）。每条查询都带归属条件。
// 可背的知识点：有原文表述的知识点，带掌握分与背诵复习日。
func (q *Queries) ListReciteCandidates(ctx context.Context, arg ListReciteCandidatesParams) ([]ListReciteCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReciteCandidates, arg.BankID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReciteCandidatesRow{}
	for rows.Next() {
		var i ListReciteCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.OriginalText,
			&i.SourceMaterialID,
			&i.SourcePage,
			&i.M,
			&i.ReciteNextReviewOn,
			&i.ReciteIntervalStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionRecites = `-- name: ListSessionRecites :many
SELECT kp_id, result, mode FROM recite_records WHERE practice_session_id = ? AND owner_user_id = ? ORDER BY id
`

type ListSessionRecitesParams struct {
	PracticeSessionID sql.NullInt64
	OwnerUserID       uint64
}

type ListSessionRecitesRow struct {
	KpID   uint64
	Result NullReciteRecordsResult
	Mode   ReciteRecordsMode
}

func (q *Queries) ListSessionRecites(ctx context.Context, arg ListSessionRecitesParams) ([]ListSessionRecitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionRecites, arg.PracticeSessionID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionRecitesRow{}
	for rows.Next() {
		var i ListSessionRecitesRow
		if err := rows.Scan(&i.KpID, &i.Result, &i.Mode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previousFinishedSession = `-- name: PreviousFinishedSession :one
SELECT summary FROM practice_sessions
WHERE owner_user_id = ? AND subject_id = ? AND kind = ? AND status = 'finished' AND id < ?
ORDER BY id DESC LIMIT 1
`

type PreviousFinishedSessionParams struct {
	OwnerUserID uint64
	SubjectID   sql.NullInt64
	Kind        PracticeSessionsKind
	ID          uint64
}

func (q *Queries) PreviousFinishedSession(ctx context.Context, arg PreviousFinishedSessionParams) (dbtypes.NullJSON, error) {
	row := q.db.QueryRowContext(ctx, previousFinishedSession,
		arg.OwnerUserID,
		arg.SubjectID,
		arg.Kind,
		arg.ID,
	)
	var summary dbtypes.NullJSON
	err := row.Scan(&summary)
	return summary, err
}

const upsertKPRecite = `-- name: UpsertKPRecite :exec
INSERT INTO kp_mastery (owner_user_id, kp_id, m, state, viewed, recite_next_review_on, recite_interval_step)
VALUES (?, ?, ?, ?, 1, ?, ?)
ON DUPLICATE KEY UPDATE m = VALUES(m), state = VALUES(state), viewed = 1,
  recite_next_review_on = VALUES(recite_next_review_on), recite_interval_step = VALUES(recite_interval_step)
`

type UpsertKPReciteParams struct {
	OwnerUserID        uint64
	KpID               uint64
	M                  string
	State              KpMasteryState
	ReciteNextReviewOn sql.NullTime
	ReciteIntervalStep uint8
}

// 背诵只改掌握分与背诵复习日，不算作答验证（PRD 11.1 补充）。
func (q *Queries) UpsertKPRecite(ctx context.Context, arg UpsertKPReciteParams) error {
	_, err := q.db.ExecContext(ctx, upsertKPRecite,
		arg.OwnerUserID,
		arg.KpID,
		arg.M,
		arg.State,
		arg.ReciteNextReviewOn,
		arg.ReciteIntervalStep,
	)
	return err
}
