// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: score.sql

package dbq

import (
	"context"
	"database/sql"
	"time"

	"peetraining-server/internal/dbtypes"
)

const insertScoreEstimate = `-- name: InsertScoreEstimate :exec
INSERT INTO score_estimates (owner_user_id, subject_id, low, high, mid, basis_papers, basis_questions, main_gap_qtype, details, trigger_reason, computed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertScoreEstimateParams struct {
	OwnerUserID    uint64
	SubjectID      uint64
	Low            uint16
	High           uint16
	Mid            string
	BasisPapers    uint8
	BasisQuestions uint16
	MainGapQtype   sql.NullString
	Details        dbtypes.NullJSON
	TriggerReason  string
	ComputedAt     time.Time
}

func (q *Queries) InsertScoreEstimate(ctx context.Context, arg InsertScoreEstimateParams) error {
	_, err := q.db.ExecContext(ctx, insertScoreEstimate,
		arg.OwnerUserID,
		arg.SubjectID,
		arg.Low,
		arg.High,
		arg.Mid,
		arg.BasisPapers,
		arg.BasisQuestions,
		arg.MainGapQtype,
		arg.Details,
		arg.TriggerReason,
		arg.ComputedAt,
	)
	return err
}

const lastScoreEstimateBefore = `-- name: LastScoreEstimateBefore :one
SELECT id, low, high, mid, computed_at
FROM score_estimates
WHERE owner_user_id = ? AND subject_id = ? AND computed_at < ?
ORDER BY computed_at DESC, id DESC
LIMIT 1
`

type LastScoreEstimateBeforeParams struct {
	OwnerUserID uint64
	SubjectID   uint64
	ComputedAt  time.Time
}

type LastScoreEstimateBeforeRow struct {
	ID         uint64
	Low        uint16
	High       uint16
	Mid        string
	ComputedAt time.Time
}

func (q *Queries) LastScoreEstimateBefore(ctx context.Context, arg LastScoreEstimateBeforeParams) (LastScoreEstimateBeforeRow, error) {
	row := q.db.QueryRowContext(ctx, lastScoreEstimateBefore, arg.OwnerUserID, arg.SubjectID, arg.ComputedAt)
	var i LastScoreEstimateBeforeRow
	err := row.Scan(
		&i.ID,
		&i.Low,
		&i.High,
		&i.Mid,
		&i.ComputedAt,
	)
	return i, err
}

const latestScoreEstimate = `-- name: LatestScoreEstimate :one
SELECT id, low, high, mid, basis_papers, basis_questions, main_gap_qtype, computed_at
FROM score_estimates
WHERE owner_user_id = ? AND subject_id = ?
ORDER BY computed_at DESC, id DESC
LIMIT 1
`

type LatestScoreEstimateParams struct {
	OwnerUserID uint64
	SubjectID   uint64
}

type LatestScoreEstimateRow struct {
	ID             uint64
	Low            uint16
	High           uint16
	Mid            string
	BasisPapers    uint8
	BasisQuestions uint16
	MainGapQtype   sql.NullString
	ComputedAt     time.Time
}

func (q *Queries) LatestScoreEstimate(ctx context.Context, arg LatestScoreEstimateParams) (LatestScoreEstimateRow, error) {
	row := q.db.QueryRowContext(ctx, latestScoreEstimate, arg.OwnerUserID, arg.SubjectID)
	var i LatestScoreEstimateRow
	err := row.Scan(
		&i.ID,
		&i.Low,
		&i.High,
		&i.Mid,
		&i.BasisPapers,
		&i.BasisQuestions,
		&i.MainGapQtype,
		&i.ComputedAt,
	)
	return i, err
}

const listGradedPaperSessions = `-- name: ListGradedPaperSessions :many

SELECT id, paper_id, paper_kind, paper_title, mode, started_at, submitted_at, graded_at, paused_seconds, full_score, score, counts_for_estimate, report
FROM paper_sessions
WHERE owner_user_id = ? AND subject_id = ? AND status = 'graded'
ORDER BY graded_at DESC, id DESC
LIMIT 50
`

type ListGradedPaperSessionsParams struct {
	OwnerUserID uint64
	SubjectID   uint64
}

type ListGradedPaperSessionsRow struct {
	ID                uint64
	PaperID           sql.NullInt64
	PaperKind         PaperSessionsPaperKind
	PaperTitle        string
	Mode              PaperSessionsMode
	StartedAt         time.Time
	SubmittedAt       sql.NullTime
	GradedAt          sql.NullTime
	PausedSeconds     uint32
	FullScore         string
	Score             sql.NullString
	CountsForEstimate bool
	Report            dbtypes.NullJSON
}

// 预估分、整卷报告与提分看板（T22，PRD 11.6、4.24、4.25、6.2）。
// 一门课批改完成的整卷，新的在前（预估分、较上次、趋势、最近成绩）。
func (q *Queries) ListGradedPaperSessions(ctx context.Context, arg ListGradedPaperSessionsParams) ([]ListGradedPaperSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGradedPaperSessions, arg.OwnerUserID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGradedPaperSessionsRow{}
	for rows.Next() {
		var i ListGradedPaperSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.PaperKind,
			&i.PaperTitle,
			&i.Mode,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.GradedAt,
			&i.PausedSeconds,
			&i.FullScore,
			&i.Score,
			&i.CountsForEstimate,
			&i.Report,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoreEstimates = `-- name: ListScoreEstimates :many
SELECT id, low, high, mid, basis_papers, basis_questions, main_gap_qtype, computed_at
FROM score_estimates
WHERE owner_user_id = ? AND subject_id = ? AND computed_at >= ?
ORDER BY computed_at DESC, id DESC
`

type ListScoreEstimatesParams struct {
	OwnerUserID uint64
	SubjectID   uint64
	ComputedAt  time.Time
}

type ListScoreEstimatesRow struct {
	ID             uint64
	Low            uint16
	High           uint16
	Mid            string
	BasisPapers    uint8
	BasisQuestions uint16
	MainGapQtype   sql.NullString
	ComputedAt     time.Time
}

// 一门课的预估分历史，新的在前（当前值、今天的变化、按周趋势）。
func (q *Queries) ListScoreEstimates(ctx context.Context, arg ListScoreEstimatesParams) ([]ListScoreEstimatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listScoreEstimates, arg.OwnerUserID, arg.SubjectID, arg.ComputedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScoreEstimatesRow{}
	for rows.Next() {
		var i ListScoreEstimatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Low,
			&i.High,
			&i.Mid,
			&i.BasisPapers,
			&i.BasisQuestions,
			&i.MainGapQtype,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectGradingLoss = `-- name: ListSubjectGradingLoss :many
SELECT g.loss
FROM gradings g
JOIN attempts a ON a.id = g.attempt_id
JOIN questions q ON q.id = a.question_id
JOIN banks b ON b.id = q.bank_id
WHERE g.owner_user_id = ? AND b.subject_id = ? AND b.owner_user_id = g.owner_user_id
  AND g.status = 'done' AND g.created_at >= ? AND g.loss IS NOT NULL
`

type ListSubjectGradingLossParams struct {
	OwnerUserID uint64
	SubjectID   sql.NullInt64
	Since       time.Time
}

// 一门课近 N 天主观题批改的失分归因（提分看板）。
func (q *Queries) ListSubjectGradingLoss(ctx context.Context, arg ListSubjectGradingLossParams) ([]dbtypes.NullJSON, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectGradingLoss, arg.OwnerUserID, arg.SubjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []dbtypes.NullJSON{}
	for rows.Next() {
		var loss dbtypes.NullJSON
		if err := rows.Scan(&loss); err != nil {
			return nil, err
		}
		items = append(items, loss)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectRecentRates = `-- name: ListSubjectRecentRates :many
SELECT q.qtype, a.score, a.full_score, a.is_correct
FROM attempts a
JOIN questions q ON q.id = a.question_id
JOIN banks b ON b.id = q.bank_id
WHERE a.owner_user_id = ? AND b.subject_id = ? AND b.owner_user_id = a.owner_user_id
  AND a.answer_mode <> 'self_assess'
  AND ((a.score IS NOT NULL AND a.full_score IS NOT NULL AND a.full_score > 0) OR a.is_correct IS NOT NULL)
ORDER BY a.answered_at DESC, a.id DESC
LIMIT 1000
`

type ListSubjectRecentRatesParams struct {
	OwnerUserID uint64
	SubjectID   sql.NullInt64
}

type ListSubjectRecentRatesRow struct {
	Qtype     QuestionsQtype
	Score     sql.NullString
	FullScore sql.NullString
	IsCorrect sql.NullBool
}

// 一门课最近的作答得分（模型分用各题型近 20 题得分率）；自评不算。
func (q *Queries) ListSubjectRecentRates(ctx context.Context, arg ListSubjectRecentRatesParams) ([]ListSubjectRecentRatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectRecentRates, arg.OwnerUserID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectRecentRatesRow{}
	for rows.Next() {
		var i ListSubjectRecentRatesRow
		if err := rows.Scan(
			&i.Qtype,
			&i.Score,
			&i.FullScore,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsWithPapers = `-- name: ListSubjectsWithPapers :many
SELECT DISTINCT subject_id FROM paper_sessions WHERE owner_user_id = ? AND status = 'graded' AND counts_for_estimate = 1
`

func (q *Queries) ListSubjectsWithPapers(ctx context.Context, ownerUserID uint64) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectsWithPapers, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var subject_id uint64
		if err := rows.Scan(&subject_id); err != nil {
			return nil, err
		}
		items = append(items, subject_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectOfQuestion = `-- name: SubjectOfQuestion :one
SELECT b.subject_id FROM questions q JOIN banks b ON b.id = q.bank_id WHERE q.id = ? AND b.owner_user_id = ?
`

type SubjectOfQuestionParams struct {
	ID          uint64
	OwnerUserID sql.NullInt64
}

func (q *Queries) SubjectOfQuestion(ctx context.Context, arg SubjectOfQuestionParams) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, subjectOfQuestion, arg.ID, arg.OwnerUserID)
	var subject_id sql.NullInt64
	err := row.Scan(&subject_id)
	return subject_id, err
}
