// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbq

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one

SELECT id, phone, nickname, avatar_key, invite_code, status, onboarding_step, deletion_requested_at, deletion_due_at, last_active_at, created_at, updated_at FROM users WHERE id = ?
`

// 用户与刷新令牌。规矩：查询用户内容一律带 owner_user_id 条件（CLAUDE.md 必须遵守第 4 条）。
func (q *Queries) GetUserByID(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Nickname,
		&i.AvatarKey,
		&i.InviteCode,
		&i.Status,
		&i.OnboardingStep,
		&i.DeletionRequestedAt,
		&i.DeletionDueAt,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, nickname, avatar_key, invite_code, status, onboarding_step, deletion_requested_at, deletion_due_at, last_active_at, created_at, updated_at FROM users WHERE phone = ?
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Nickname,
		&i.AvatarKey,
		&i.InviteCode,
		&i.Status,
		&i.OnboardingStep,
		&i.DeletionRequestedAt,
		&i.DeletionDueAt,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
