// Code generated by internal/http/stubgen. DO NOT EDIT.

package http

import (
	"github.com/gin-gonic/gin"

	"peetraining-server/internal/gen"
)

// CreateKnowledgeNode 尚未实现，返回 501。
func (h *Handlers) CreateKnowledgeNode(c *gin.Context, _ gen.SubjectId) {
	_ = c.Error(ErrNotImplemented())
}

// CreateQuestion 尚未实现，返回 501。
func (h *Handlers) CreateQuestion(c *gin.Context, _ gen.SubjectId) { _ = c.Error(ErrNotImplemented()) }

// DeleteKnowledgePoint 尚未实现，返回 501。
func (h *Handlers) DeleteKnowledgePoint(c *gin.Context, _ gen.KpId) { _ = c.Error(ErrNotImplemented()) }

// DeleteQuestion 尚未实现，返回 501。
func (h *Handlers) DeleteQuestion(c *gin.Context, _ gen.QuestionId) { _ = c.Error(ErrNotImplemented()) }

// GetBankOverview 尚未实现，返回 501。
func (h *Handlers) GetBankOverview(c *gin.Context, _ gen.SubjectId) { _ = c.Error(ErrNotImplemented()) }

// GetKnowledgePoint 尚未实现，返回 501。
func (h *Handlers) GetKnowledgePoint(c *gin.Context, _ gen.KpId) { _ = c.Error(ErrNotImplemented()) }

// GetKnowledgeTree 尚未实现，返回 501。
func (h *Handlers) GetKnowledgeTree(c *gin.Context, _ gen.SubjectId, _ gen.GetKnowledgeTreeParams) {
	_ = c.Error(ErrNotImplemented())
}

// GetMaterialPage 尚未实现，返回 501。
func (h *Handlers) GetMaterialPage(c *gin.Context, _ gen.MaterialId, _ int, _ gen.GetMaterialPageParams) {
	_ = c.Error(ErrNotImplemented())
}

// GetQuestion 尚未实现，返回 501。
func (h *Handlers) GetQuestion(c *gin.Context, _ gen.QuestionId) { _ = c.Error(ErrNotImplemented()) }

// ListQuestions 尚未实现，返回 501。
func (h *Handlers) ListQuestions(c *gin.Context, _ gen.SubjectId, _ gen.ListQuestionsParams) {
	_ = c.Error(ErrNotImplemented())
}

// MergeKnowledgePoint 尚未实现，返回 501。
func (h *Handlers) MergeKnowledgePoint(c *gin.Context, _ gen.KpId) { _ = c.Error(ErrNotImplemented()) }

// RegenerateExplanation 尚未实现，返回 501。
func (h *Handlers) RegenerateExplanation(c *gin.Context, _ gen.KpId) {
	_ = c.Error(ErrNotImplemented())
}

// SearchBank 尚未实现，返回 501。
func (h *Handlers) SearchBank(c *gin.Context, _ gen.SubjectId, _ gen.SearchBankParams) {
	_ = c.Error(ErrNotImplemented())
}

// SelfAssessKnowledgePoint 尚未实现，返回 501。
func (h *Handlers) SelfAssessKnowledgePoint(c *gin.Context, _ gen.KpId) {
	_ = c.Error(ErrNotImplemented())
}

// SplitKnowledgePoint 尚未实现，返回 501。
func (h *Handlers) SplitKnowledgePoint(c *gin.Context, _ gen.KpId) { _ = c.Error(ErrNotImplemented()) }

// UpdateKnowledgePoint 尚未实现，返回 501。
func (h *Handlers) UpdateKnowledgePoint(c *gin.Context, _ gen.KpId) { _ = c.Error(ErrNotImplemented()) }

// UpdateQuestion 尚未实现，返回 501。
func (h *Handlers) UpdateQuestion(c *gin.Context, _ gen.QuestionId) { _ = c.Error(ErrNotImplemented()) }
