// stubgen 为 gen.ServerInterface 里还没实现的接口生成返回 501 的占位处理器（internal/http/stubs_gen.go）。
//
// 契约先行：接口先进 openapi.yaml，处理器由各任务卡逐个实现；实现了的方法自动从占位文件里消失。
// 由 make gen 调用，不要手动修改 stubs_gen.go。
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if err := run("internal/gen/api.gen.go", "internal/http", "internal/http/stubs_gen.go"); err != nil {
		fmt.Fprintln(os.Stderr, "stubgen:", err)
		os.Exit(1)
	}
}

type method struct {
	name   string
	params string
}

func run(genFile, pkgDir, out string) error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, genFile, nil, 0)
	if err != nil {
		return err
	}
	var methods []method
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != "ServerInterface" {
			return true
		}
		for _, m := range ts.Type.(*ast.InterfaceType).Methods.List {
			ft := m.Type.(*ast.FuncType)
			var params []string
			for _, p := range ft.Params.List {
				var buf bytes.Buffer
				_ = format.Node(&buf, fset, p.Type)
				typ := buf.String()
				if !strings.Contains(typ, ".") && typ != "string" && typ != "int" && typ != "int64" && typ != "bool" {
					typ = "gen." + typ
				}
				for _, name := range p.Names {
					params = append(params, "_ "+typ)
					_ = name
				}
			}
			methods = append(methods, method{name: m.Names[0].Name, params: strings.Join(params, ", ")})
		}
		return false
	})

	implemented, err := implementedMethods(fset, pkgDir, out)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by internal/http/stubgen. DO NOT EDIT.\n\n")
	b.WriteString("package http\n\n")
	var stubs []method
	for _, m := range methods {
		if !implemented[m.name] {
			stubs = append(stubs, m)
		}
	}
	sort.Slice(stubs, func(i, j int) bool { return stubs[i].name < stubs[j].name })
	needGen := false
	for _, m := range stubs {
		if strings.Contains(m.params, "gen.") {
			needGen = true
		}
	}
	b.WriteString("import (\n\t\"github.com/gin-gonic/gin\"\n")
	if needGen {
		b.WriteString("\n\t\"peetraining-server/internal/gen\"\n")
	}
	b.WriteString(")\n\n")
	for _, m := range stubs {
		params := strings.Replace(m.params, "_ *gin.Context", "c *gin.Context", 1)
		fmt.Fprintf(&b, "// %s 尚未实现，返回 501。\nfunc (h *Handlers) %s(%s) { _ = c.Error(ErrNotImplemented()) }\n\n", m.name, m.name, params)
	}
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("格式化：%w\n%s", err, b.String())
	}
	return os.WriteFile(out, src, 0o644) //nolint:gosec // 生成的源码文件，需要与仓库里其他源码相同的权限
}

// implementedMethods 找出包里（除占位文件外）已经在 *Handlers 上实现的方法。
func implementedMethods(fset *token.FileSet, dir, skip string) (map[string]bool, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}
	done := map[string]bool{}
	for _, path := range files {
		if path == skip || strings.HasSuffix(path, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, err
		}
		for _, d := range f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || len(fd.Recv.List) != 1 {
				continue
			}
			if star, ok := fd.Recv.List[0].Type.(*ast.StarExpr); ok {
				if id, ok := star.X.(*ast.Ident); ok && id.Name == "Handlers" {
					done[fd.Name.Name] = true
				}
			}
		}
	}
	return done, nil
}
